### ISSUE TITLE
Layer list position in GL Inspect viewer

### ISSUE THREAD

**Issue by daliborjanak** [klokantech/tileserver-gl#106]
Is there any reason why layer list in mapbox inspector has position bottom: 60%? On smaller screens and embedding, which we are using, is a lot of white space under and scroller. See screenshot:

![image](https://cloud.githubusercontent.com/assets/1891090/21987393/9f28cc3a-dc03-11e6-92bb-1aad8bb3a9db.png)

Would it be possible to fix that? Bottom should have 10px (ends at bottom and 10px space) instead of 60%.
The code is at line 16 in:
https://github.com/klokantech/tileserver-gl/blob/473e7b6f4a579f10ed8440862b20a18540c83bc1/public/templates/data.tmpl#L16

**Comment by petrsloup** [comment]
@daliborjanak Thanks for reporting, the empty space was previously used to display the feature properties, but that was moved to the popup.

**Comment by klokan** [comment]
@petrsloup - can we set the font on the right sidebar to Arial, sans-serif or similar. Now it is Times, serif which does not appear anywhere else.

**Comment by petrsloup** [comment]
@klokan It was not specified at all, so the browser default was used. Changed to `Arial, sans-serif`.
