### ISSUE TITLE
WARN: MBTiles not in "openmaptiles" format

### ISSUE THREAD

**Issue by SantiagoHorcajo** [klokantech/tileserver-gl#107]
Hi there,
I have installed tileserver-gl version 1.3.0 with npm, but without -g option, and downloaded a fresh version of spain.mbtiles from [http://osm2vectortiles.org/](url). When I try to start tileserver-gl I get a warning related to the format of osm2vectortile file. Take into account that the version of tileserver-gl is not a beta version.

<pre>root@core ~/node_modules# node tileserver-gl --verbose ../spain.mbtiles
Starting tileserver-gl v1.3.0
Automatically creating config file for ../spain.mbtiles
WARN: MBTiles not in "openmaptiles" format. Serving raw data only...
{
  "options": {
    "paths": {
      "root": "/root/node_modules/tileserver-gl/node_modules/tileserver-gl-styles",
      "fonts": "fonts",
      "styles": "styles",
      "mbtiles": "/root"
    }
  },
  "styles": {},
  "data": {
    "osm2vectortiles": {
      "mbtiles": "spain.mbtiles"
    }
  }
}
terminate called after throwing an instance of ´std::runtime_error´
  what(): Failed to open X display
Aborted
root@core ~/node_modules#</pre>

The last part of attached command output is another problem that I will report in other thread.

Thanks in advance,
Santiago Horcajo

**Comment by petrsloup** [comment]
If you downloaded tiles from http://osm2vectortiles.org/, the tiles are in OSM2VectorTiles format.

The OSM2VectorTiles project is no longer maintained and we recommend using tiles from https://openmaptiles.org/.

The default map styles embedded in TileServer-GL v1.3+ are compatible with OpenMapTiles, but styles for OSM2VectorTiles are no longer included.

If you really need to use these tiles, either use older TileServer-GL (v1.2.0) or create your own config file and supply your own styles for the tiles.

Another problem is that you are probably running tileserver-gl somewhere without X server, but the software needs an X display to properly initialize OpenGL. Either use docker image or launch the tileserver-gl with xvfb (see https://github.com/klokantech/tileserver-gl/blob/master/run.sh).

**Comment by SantiagoHorcajo** [comment]
Ok, thanks, I'm not sure why I didn't realize that I have to use openmaptiles tiles, it's clearly written in the main project page. My fault.

**Comment by cs09g** [comment]
In my case, happening the same issue with docker or node itself. but with tileserver-gl in kitematic, there's fine. weird though. why this shows differently? How can I display the same result in my docker as in the kitematic's container?

**Comment by htrex** [comment]
> Hi, does this mean I cannot used tiles I created via tippecanoe?

I'm serving with tileserver-gl v2.5.0 some mbtiles generated with tippecanoe v1.32.9 and it's working well.

**Comment by petrsloup** [comment]
You can use the tiles without any issues, but the styles bundled with tileserver-gl are created specifically for openmaptiles schema, so they cannot be used -- you need to create your own styles, otherwise you will only get an "inspect" viewer.

See also https://github.com/klokantech/tileserver-gl/issues/271

**Comment by nyurik** [comment]
Note that if your data matches the style, it is enough to update metadata table in the mbtiles file -- ensure it has `format` field set to `pbf`, and the `name` field must contain `openmaptiles` word somewhere in it.  See https://github.com/maptiler/tileserver-gl/blob/08369a666dab8889f9ead0138ae356763c77f31c/src/main.js#L127
