### ISSUE TITLE
Index styling

### ISSUE THREAD

**Issue by petrsloup** [klokantech/tileserver-gl#11]
To be discussed

**Comment by klokan** [comment]
We have to make a distinguishable branding (header of the front page / logo?).
The viewers itself are fullscreen without branding.

Ideal index view a la:
![screen shot 2016-03-10 at 15 09 28](https://cloud.githubusercontent.com/assets/59284/13946563/9c737934-f015-11e5-9880-f7ae23477791.png)

**Comment by daliborjanak** [comment]
Initial done:
![image](https://cloud.githubusercontent.com/assets/1891090/14285422/b9cce3ee-fb4b-11e5-9608-a06fa98fca69.png)
@klokan can you add me commit access to this repo please??

**Comment by klokan** [comment]
Commit access granted.

**Comment by petrsloup** [comment]
Maybe we could add links to the style jsons (`/styles/{{@key}}.json`) as well?

**Comment by daliborjanak** [comment]
This is done a long time ago. Other changes will be good after discusses with a designer (+new ticket). This is not necessary yet.
