### ISSUE TITLE
Possible to serve multiple mbtiles without editing config?

### ISSUE THREAD

**Issue by reyemtm** [klokantech/tileserver-gl#110]
What would be great is if running the server would find all mbtiles in current or x path, check if they are openmaptiles, if so serve them with default styles, if not just serve up the data/inspector. It does this now but with just one file, not all the files. Is this a config setting that I haven't found or can it be added? I do not want to edit the config everytime I upload more data.

**Comment by klokan** [comment]
What is the advantage of having multiple MBTiles from OpenMapTiles?
Why not to have one big MBTiles which cover the complete area you need - or use the planet?

**Comment by reyemtm** [comment]
I just want to sftp over a bunch of data to my server and have this thing
serve it out.

I am using my current mbtiles-server as a GIS server of sorts with a wide
variety of data, accessing the raw source zxy pbfs in many web maps, while
also using it for basemaps. I like some of the additional features of
Tileserver-gl-light and might switch to this. I especially like the index
page. So for me neither project is perfect and since this project is
actively maintained, already has an index page, and in the PHP version has
source code for webmaps, I think this project is closer to my vision.

**Comment by reyemtm** [comment]
Yes, that said I only have one mbtiles openmaptiles basemaps file.

**Comment by Namec** [comment]
i have similar needs,

the purpos of getting more than data source (more than one Mbtile File) is to reuse old Styles created for OSM and MAPBOX.

while the layers heve different names, it's impossible to reuse a style witout rewtiting it

**Comment by reyemtm** [comment]
I will switch from mbtiles-server to this (light version) if I can get the ability to use this as a GIS server - ie many mbtile files, searchable, with the inspector. Any work on this or ideas on how to implement? Otherwise I will continue to tweak the mbtiles-server to meet my needs and you can close this issue.

**Comment by ricadete** [comment]
I also have the same need. Let me know if you got some news.

**Comment by reyemtm** [comment]
There's been no comments or work on this here... meanwhile I have been tweaking a version of the mbtiles-server. See https://github.com/ovrdc/tileserver

**Comment by spatialillusions** [comment]
Would it be possible to serve several mbtiles files as one service? 
At the moment I can't figure out if this is possible and the use case would be to serve the contour lines and osm from one server container, so that it would be possible to serve the Terrain map without having several servers.

**Comment by petrsloup** [comment]
You can specify multiple datasets in the config file. See http://tileserver.readthedocs.io/en/latest/config.html

**Comment by karakostis** [comment]
@petrsloup  Where is the config file?

**Comment by petrsloup** [comment]
You have to create the config file. See https://tileserver.readthedocs.io/en/latest/usage.html

**Comment by Alex-Horlock** [comment]
> You can specify multiple datasets in the config file. See http://tileserver.readthedocs.io/en/latest/config.html

I have been trying for the last few hours to specify multiple data sources... it s=just doesn't seem to work. Each data source works great by itself but if you create a style that has two sources, it simply uses the first one. I'm sure i'm missing something but is there a working example of this somewhere because it's not clear how you do it even from here: https://tileserver.readthedocs.io/en/latest/config.html

**Comment by umbe1987** [comment]
It does work. All you have to do is to specify the MBTILES under "data" key like so:

**config.json**
```
"data": {
        "test1": {
            "mbtiles": "first_data.mbtiles"
        },
        "test2": {
            "mbtiles": "second_data.mbtiles"
        }
    }
```

Then, just launch the tileserver specifying using **config.json** and you'll be able to see the tiles at:

- http://localhost:8080/data/test1
- http://localhost:8080/data/test2
