### ISSUE TITLE
Tileserver-gl-light behind IIS

### ISSUE THREAD

**Issue by scpeterson** [klokantech/tileserver-gl#114]
I wasn't certain where else to ask this, but I need to serve a basemap using IIS and HTTPS.  I am not an IIS expert, so I'm uncertain how to make IIS aware of tileserver-gl-light.  I see that there is a bind option.  Do I just run tileserver-gl-light with the IP of my server?  Any input or advice would be a big help.

**Comment by petrsloup** [comment]
This question is IIS-specific. Try asking the question on StackOverflow (for example) with proper tags... You might have better luck there.
