### ISSUE TITLE
Tileserver-gl-light missing mapbox-gl.js.map file on Windows

### ISSUE THREAD

**Issue by scpeterson** [klokantech/tileserver-gl#115]
We are running tileserver-gl-light 1.3.2 on Windows Server 2012 and we are getting 404 errors on the mapbox-gl,js.map file:

![image](https://cloud.githubusercontent.com/assets/1301178/22759693/61e33e66-ee21-11e6-93ec-d3d27fc94c28.png)

We ran the same version on Ubuntu, and did not receive this error.  We are stuck using Windows, and are having trouble making tileserver work.

I also notice the same behavior in version 1.4.1 on Windows

**Comment by petrsloup** [comment]
These files are only for easier debugging and not needed at all for regular use.
The browser should not actually request these during normal usage. (Chrome requests these only when you have the developer tools open.)
