### ISSUE TITLE
More informative error messages for config issues

### ISSUE THREAD

**Issue by stephent** [klokantech/tileserver-gl#116]
I'm trying to get tileserver-gl running with my own config file (so far without success). The only error message I seem to get is as follows:

`docker run -it -v $(pwd):/data -p 8080:80 klokantech/tileserver-gl --verbose -c crookneck.config
Starting tileserver-gl v1.3.2
Using specified config file from crookneck.config
Starting server
ERROR: Config file not found or invalid!
       See README.md for instructions and sample data.`

It would be great if the error message could include more information about the problem (I can't see what's wrong with it as yet).

Also, if I deliberately give an invalid path to a config file, the server autogenerates a config, therefore it seems that the "file not found" part of the error message cannot be true and it must be an issue with the contents of the file.

Thanks for all the amazing work on this project.

**Comment by klokan** [comment]
`ERROR: Config file not found or invalid!`
I expect your file is not a valid JSON or is invalid. Pass it to a JSON validator, please.
Or it is not found (not in the actual directory).
Why don't you name it config.json instead - as it is expected?

**Comment by stephent** [comment]
The file is valid json (that was one of the first things I checked).

> Why don't you name it config.json instead - as it is expected?

It wasn't clear to me from the way the [docs](http://tileserver.readthedocs.io/en/latest/usage.html#default-styles-and-configuration) are written that the file must be named config.json, however, having renamed it to that it looks like I'm getting further.

Thanks for the suggestion.

**Comment by michalrus** [comment]
For anyone in the future, config file’s extension just needs to be `.json`.
