### ISSUE TITLE
Other vector tile providers than mbtiles

### ISSUE THREAD

**Issue by hannesj** [klokantech/tileserver-gl#12]
Currently the vector tiles are hardcoded to be served from an mbtiles file. It would be nice if you could provide your own Tilelive module to be a vector tile source.

**Comment by klokan** [comment]
Vector tiles can be served from a remote source over HTTP - where you can render these on demand from Posgres with Tilelive or GeoServer or other project. This way you can chain TileServer-GL with a different PBF backends.

The tileserver-gl project is not powered by TileLive and does not contain Mapnik now.

Would the chaining described above cover your use case - or is would it be inefficient for you?

**Comment by klokan** [comment]
@hannesj shall we close this ticket?

All what you have to do is to modify your GL JSON styles to point to a different source - typically link it to `http://...`.
