### ISSUE TITLE
Config option for static image larger than @4x

### ISSUE THREAD

**Issue by denkan** [klokantech/tileserver-gl#121]
Hi,
Working on a case where I need to convert a 500x500 html5 canvas to large printable image.

Is there any way to use even larger values than `@4x` on this endpoint?
`/styles/{id}/static/{lon},{lat},{zoom}[@{bearing}[,{pitch}]]/{width}x{height}[@2x].{format}`

I've tried to adjust the width/height + zoom to increase overall sizes, and it works pretty good. But some map layouts vary a lot depending on zoom level etc, and I need it to look exactly the same - which the `@x{Num}` solves, but I need even larger :) 

Any tip?

**Comment by denkan** [comment]
Looking at the source, I suppose I need to fork and alter this line accordingly. 
https://github.com/klokantech/tileserver-gl/blob/master/src/serve_rendered.js#L27

No plans to increase the values on a docker-build in near future? :)

**Comment by klokan** [comment]
IMHO it makes a sense to make it an option in config, so it is easier to change during the deploy.
