### ISSUE TITLE
tileserver-gl-light cannot find styles

### ISSUE THREAD

**Issue by wmsatsea** [klokantech/tileserver-gl#122]
I an trying to migrate from tileserver-gl-light v1.2.0 and osm2vectortiles mbtiles to v1.4.1 and openmaptiles. I am not using a custom configuration file, rather the one that is automatically generated, which seems to work fine in v1.2.0:

<pre><code>
Starting tileserver-gl-light v1.2.0
Automatically creating config file for /usr/local/lib/planet_z0-z8.mbtiles
{
  "options": {
    "paths": {
      "root": "/usr/lib/node_modules/tileserver-gl-light/node_modules/tileserver-gl-styles",
      "fonts": "glyphs",
      "sprites": "sprites",
      "styles": "styles",
      "mbtiles": "/usr/local/lib"
    }
  },
  "styles": {
    "basic-v9": {
      "style": "basic-v9.json",
      "tilejson": {
        "bounds": [
          -180,
          -85.0511,
          180,
          85.0511
        ]
      }
    },
    "bright-v9": {
      "style": "bright-v9.json",
      "tilejson": {
        "bounds": [
          -180,
          -85.0511,
          180,
          85.0511
        ]
      }
    }
  },
  "data": {
    "osm2vectortiles": {
      "mbtiles": "planet_z0-z8.mbtiles"
    }
  }
}
Starting server
Listening at http://:::8080/
GET /styles/bright-v9.json 200 6.875 ms - 7290
GET /data/osm2vectortiles.json 200 3.672 ms - 46917
GET /styles/bright-v9/sprite.json 200 1.434 ms - 11042
GET /styles/bright-v9/sprite.png 200 0.699 ms - 30153
GET /data/osm2vectortiles/1/0/1.pbf 200 2.193 ms - 7544
GET /data/osm2vectortiles/1/1/0.pbf 200 0.593 ms - 14058
GET /data/osm2vectortiles/1/0/0.pbf 200 0.807 ms - 15186
GET /data/osm2vectortiles/1/1/1.pbf 200 0.485 ms - 7177
GET /fonts/Open%20Sans%20Regular/0-255.pbf 200 10.229 ms - 74696
</pre></code>

This minimal auto-generated config file seems to work fine; as the documentation suggests, it starts at the root, appends 'styles' and finds the style there. Version 1.4.1, however, cannot find the style:

<pre><code>
Starting tileserver-gl-light v1.4.1
Automatically creating config file for /usr/local/lib/planet_z0_z14.mbtiles
{
  "options": {
    "paths": {
      "root": "/usr/lib/node_modules/tileserver-gl-light/node_modules/tileserver-gl-styles",
      "fonts": "fonts",
      "styles": "styles",
      "mbtiles": "/usr/local/lib"
    }
  },
  "styles": {
    "klokantech-basic": {
      "style": "klokantech-basic/style.json",
      "tilejson": {
        "bounds": [
          -180,
          -85.0511,
          180,
          85.0511
        ]
      }
    },
    "osm-bright": {
      "style": "osm-bright/style.json",
      "tilejson": {
        "bounds": [
          -180,
          -85.0511,
          180,
          85.0511
        ]
      }
    }
  },
  "data": {
    "v3": {
      "mbtiles": "planet_z0_z14.mbtiles"
    }
  }
}
Starting server
Listening at http://:::8080/
GET /styles/osm-bright/style.json 404 42.054 ms - 41
</pre></code>

Both installations are default out-of-the box installations.  I have verified that the directory '/usr/lib/node_modules/tileserver-gl-light/node_modules/tileserver-gl-style/styles/osm-bright' exists; the ownerships of all the files and directories in the 'styles' directory are 'nobody:root'; all flat files are readable to owner/group/world, and all directories are readable/executable to o/g/w:

<pre><code>
[root@osmserver%/] ls -ld /usr/lib/node_modules/tileserver-gl-light/node_modules/tileserver-gl-styles/styles
drwxr-xr-x 4 nobody root 4096 Feb 10 23:35 /usr/lib/node_modules/tileserver-gl-light/node_modules/tileserver-gl-styles/styles
[root@osmserver%/] ls -ld /usr/lib/node_modules/tileserver-gl-light/node_modules/tileserver-gl-styles/styles/osm-bright/
drwxr-xr-x 2 nobody root 4096 Feb 10 23:35 /usr/lib/node_modules/tileserver-gl-light/node_modules/tileserver-gl-styles/styles/osm-bright/
[root@osmserver%/] ls -l /usr/lib/node_modules/tileserver-gl-light/node_modules/tileserver-gl-styles/styles/osm-bright/
total 148
-rw-r--r-- 1 nobody root  9179 Jan 17 19:46 sprite.json
-rw-r--r-- 1 nobody root 14475 Jan 17 19:46 sprite.png
-rw-r--r-- 1 nobody root  9244 Jan 17 19:46 sprite@2x.json
-rw-r--r-- 1 nobody root 36098 Jan 17 19:46 sprite@2x.png
-rw-r--r-- 1 nobody root 70371 Jan 17 19:46 style.json
</pre></code>

I have read the documentation and tried to tinker with the config file, all to no avail. I would think that in this respect, v1.4.1 should perform in a similar way to v1.2.0. If I am doing something wrong, please advise.

**Comment by klokan** [comment]
Are you sure you use OpenMapTiles MBTiles with the latest version of TileServer GL?
Is your tileserver-gl-styles module updated to the latest version (1.1.0) which contains updated styles for both klokantech-basic and osm-bright?

**Comment by petrsloup** [comment]
@wmsatsea 
The url `/styles/osm-bright/style.json` is incorrect and returns 404 as expected.
Try `/styles/osm-bright.json` -- that's the endpoint (same as before -- the URLs are compatible).
The `"style": "osm-bright/style.json",` inside the config is just a filesystem path.

Does this resolve your problem?

**Comment by wmsatsea** [comment]
It did indeed.  Thank you very much.
