### ISSUE TITLE
Difficulty Rendering Custom Styles

### ISSUE THREAD

**Issue by rmrice** [klokantech/tileserver-gl#123]
Hi, happy to announce I have tileserver-gl working with node on my Centos machine and my local Ubuntu machine! 

I am trying to load in custom styles with my own mbtiles data. I believe I have configged everything correctly, and I am unsure what else I need to do to get this to work. On my tileserver I have 4 styles: the two that come prepackaged with tileserver-gl-styles, my custom style (which is extremely basic, just one color applied to all data as fills), and your Positron style which I configged to match Kloklantech-Basic and OSM-Bright. Kolkantech-Basic and OSM-Bright work as expected, but Positron and my custom style do not. This is the output I'm getting:

```
$ node . --verbose
Starting tileserver-gl v1.4.1
Using specified config file from config.json
Starting server
Listening at http://:::8080/
GET / 304 51.994 ms - -
GET /index.css 304 2.714 ms - -
GET /images/logo.png 304 0.740 ms - -
GET /styles/basic/rendered/NaN/NaN/NaN.png 404 3.769 ms - 50
ERROR: Font not found: Klokantech Noto Sans Regular
ERROR: Trying to use Open Sans Bold as a fallback
GET /styles/klokantech-basic/rendered/11/1072/717.png 200 58.630 ms - 54143
GET /styles/positron/rendered/NaN/NaN/NaN.png 404 1.554 ms - 53
GET /images/placeholder.png 304 0.811 ms - -
GET /images/klokantech.png 304 0.264 ms - -
GET /styles/basic/rendered/NaN/NaN/NaN.png 404 1.428 ms - 50
GET /images/header-map-2560px.png 304 0.945 ms - -
GET /fonts/OpenSans-Regular.ttf 304 0.632 ms - -
GET /fonts/OpenSans-Bold.ttf 304 0.453 ms - -
GET /styles/osm-bright/rendered/11/1072/717.png 200 77.932 ms - 67195
GET /favicon.ico 200 1.658 ms - 5430
```

And this in browser:
![screenshot from 2017-02-15 09-16-04](https://cloud.githubusercontent.com/assets/17434033/22983412/05708eaa-f370-11e6-8c61-44671e6b04f4.png)

The `NaN/NaN/NaN` is perplexing since I have specified the center and zooms, and changed the center/zoom/bounds/source in Positron style to match the two that work. Those are the only things I changed.

I also tried adding a more complicated custom style (still not super complicated, just filtered based on attributes and zoom levels) and got the same output in addition to this, which I'm assuming is a mapbox-gl issue:
```
mbgl: { class: 'ParseStyle',
  severity: 'WARNING',
  text: 'function stop zoom level must be a number' }
```

Any ideas as to why any styles I load in are broken?

Thanks!

**Comment by klokan** [comment]
Hi Rebeca,

- Could you please show your config.json and your style.json? (gist.github.com?)
- What about errors printed on the console?

Clearly a problem with a wrong configuration on your side...

This is how Positron should look like probably:
https://github.com/openmaptiles/positron-gl-style/blob/gh-pages/style-local.json

IMHO it would be better if you deploy all your styles on your own - from GitHub repos from https://openmaptiles.org/styles/
 
If we solve this problem together - are you going to help with documenting the process for others?

**Comment by rmrice** [comment]
@klokan I will definitely help with the documentation. Let me know where you'd like it added. The script for running it on Centos is rather long.

After some messing around, I got everything to work. I figured out that my problem was that the config bounds were incorrect. In the config.json, the bounds need to match the bounds found in the tilejson *exactly* or else you'll get the `NaN/NaN/NaN` output. So I will close this issue.

The mbgl warning I'm getting for my custom style is still causing me some problems. The style works in Viewer/vector mode but raster/xyz urls are outputting empty tiles. I think it's because I'm specifying colors by attributes for different zoom levels, which may not be fully supported by mapbox-gl for rendering pngs. I *think* that's the problem.

Anyway, thanks for developing this and making it available to us!

**Comment by klokan** [comment]
Thanks for the offer of help!

The page https://github.com/klokantech/tileserver-gl/blob/master/docs/installation.rst could be improved. If you have CentOS specific instructions mention them there. If the scripts are long - just put them on gist and link them please - for people to follow.

Any help with documentation improvement is very welcome. ;-)

**Comment by klokan** [comment]
BTW I don't think you have to specify bounds in config - normally these comes from TileJSON / MBTiles metadata table.

**Comment by zhali** [comment]
@rmrice , thank for your help about tileserver-gl node installation on Centos, as the steps, i have run    the program, but when the raster tile fonts dot’t render correctly in the image, as #245 
Any ideas as to why the fonts wrong ?
Thanks!

**Comment by rmrice** [comment]
Hi @zhali! I don't know if I can help you. I haven't worked with tileserver-gl in almost a year and don't have any time to invest in investigating this issue, but I know this is definitely a problem with mapbox-gl-native or the version of mapbox-gl-native that tileserver-gl currently uses. Maybe update the dependencies that tileserver uses, otherwise I'm not really sure. Sorry I'm not much help.
