### ISSUE TITLE
Add support "proj4" in mbtiles metadata

### ISSUE THREAD

**Issue by petrsloup** [klokantech/tileserver-gl#127]
If "proj4" is present in the mbtiles, the static endpoint should accept WGS84 values and transform internally using proj4js

See also https://github.com/klokantech/tilejson-spec/blob/custom-projection/2.2.0/README.md

**Comment by rroset** [comment]
Serving tiles, both vector and raster, in different projections would be really useful. Don't stop at 4326, we could use 25831 too  =)
