### ISSUE TITLE
Use tileserver-gl as wms server for kibana

### ISSUE THREAD

**Issue by omnidepp** [klokantech/tileserver-gl#132]
Can I use this excellent and simple to set up mapserver as a WMS compliant webeserver for elasticsearch/kibana tile-map visualizations?

The only available settings are these:

![screenshot](https://cloud.githubusercontent.com/assets/14217074/23751049/0e7a7fe4-04d0-11e7-97f5-372adc784cc6.png)

Any chance to use tileserver-gl "out of the box" with kibana?

**Comment by klokan** [comment]
You can if you use OpenMapTiles Server: https://openmaptiles.com/server/

It does support WMS natively out of the box.

**Comment by micking** [comment]
I've successfully installed an OpenMapTiles Map Server but I'm unable to get to the WMS option - is there a specific url for WMS?

**Comment by klokan** [comment]
There is WMTS and WMS link next to the thumbnail of each map available via OpenMapTiles Server...

**Comment by KonstantinEmelyanov** [comment]
> There is WMTS and WMS link next to the thumbnail of each map available via OpenMapTiles Server...

I try get request GetFeatureInfo of my OpenMapTiles Map Server. But i get response:
```
<![CDATA[
received wms getfeatureinfo request for unqueryable layer klokantech-terrain
]]>
```
On Server i see layer property. All layers is queryable="0"
```
<Layer cascaded="1" queryable="0">
<Name>klokantech-terrain</Name>
<Title>klokantech-terrain</Title>
```
I think this is the reason what i cant get request GetFeatureInfo. If so, how do I make a layer on OpenMapTiles Map Server is queryable="1"?
