### ISSUE TITLE
POI and Highway Shields Chopped off in Raster Mode

### ISSUE THREAD

**Issue by lincomatic** [klokantech/tileserver-gl#135]
When rendering raster tiles, there are a lot of instances where things get cut off at tile boundaries.

POI labels at center top:

![image](https://cloud.githubusercontent.com/assets/1422186/23963674/52ad628c-096f-11e7-9927-188aea30e1d7.png)

Highway shields:

![image](https://cloud.githubusercontent.com/assets/1422186/23963779/a1621d78-096f-11e7-94c1-576c85c753fc.png)

What's strange is that sometimes, text that spans tile boundaries is rendered correctly.

**Comment by lincomatic** [comment]
Another example:

![image](https://cloud.githubusercontent.com/assets/1422186/23963865/e0ce4da6-096f-11e7-90c2-9b65f4fc75ff.png)

**Comment by klokan** [comment]
Nothing to be done on the TileServer GL side.

This issue can be solved on the side of GL style definition and by adjusting the structure of the vector tiles (increasing internal buffers).

For details see:
https://github.com/openmaptiles/openmaptiles/issues/224

**Comment by lincomatic** [comment]
Could you point me to where I can learn how to increase the internal buffers in the vector tiles? Thanks.
