### ISSUE TITLE
'mapbox' is not in the npm registry 

### ISSUE THREAD

**Issue by strech345** [klokantech/tileserver-gl#136]
Get the error that mapbox is not in the reposetory.
Is it a problem from mapbox? and how to solve?
Thanks!
Stephan

 npm install -g tileserver-gl
npm http GET https://registry.npmjs.org/tileserver-gl
npm http 200 https://registry.npmjs.org/tileserver-gl
npm http GET https://registry.npmjs.org/tileserver-gl/-/tileserver-gl-1.4.1.tgz
npm http 200 https://registry.npmjs.org/tileserver-gl/-/tileserver-gl-1.4.1.tgz
npm WARN engine tileserver-gl@1.4.1: wanted: {"node":">=4.2.1 <5"} (current: {"node":"v0.10.26","npm":"1.4.3"})
npm http GET https://registry.npmjs.org/base64url/2.0.0
npm http GET https://registry.npmjs.org/canvas/1.6.2
npm http GET https://registry.npmjs.org/clone/2.1.0
npm http GET https://registry.npmjs.org/color/1.0.3
npm http GET https://registry.npmjs.org/cors/2.8.1
npm http GET https://registry.npmjs.org/express/4.14.1
npm http GET https://registry.npmjs.org/glyph-pbf-composite/0.0.2
npm http GET https://registry.npmjs.org/handlebars/4.0.6
npm http GET https://registry.npmjs.org/mbtiles/0.9.0
npm http GET https://registry.npmjs.org/morgan/1.7.0
npm http GET https://registry.npmjs.org/node-pngquant-native/1.0.4
npm http GET https://registry.npmjs.org/nomnom/1.8.1
npm http GET https://registry.npmjs.org/pbf/3.0.5
npm http GET https://registry.npmjs.org/request/2.79.0
npm http GET https://registry.npmjs.org/sharp/0.17.1
npm http GET https://registry.npmjs.org/tileserver-gl-styles/1.1.0
npm http GET https://registry.npmjs.org/vector-tile/1.3.0
npm http GET https://registry.npmjs.org/async/2.1.4
npm http GET https://registry.npmjs.org/tileshrink-gl
npm http GET https://registry.npmjs.org/advanced-pool/0.3.2
npm http GET https://registry.npmjs.org/mapbox/mapbox-gl-native/3.4.4
npm http GET https://registry.npmjs.org/mapbox/sphericalmercator/1.0.5
npm http 200 https://registry.npmjs.org/base64url/2.0.0
npm http GET https://registry.npmjs.org/base64url/-/base64url-2.0.0.tgz
npm http 200 https://registry.npmjs.org/color/1.0.3
npm http GET https://registry.npmjs.org/color/-/color-1.0.3.tgz
npm http 200 https://registry.npmjs.org/clone/2.1.0
npm http 200 https://registry.npmjs.org/cors/2.8.1
npm http GET https://registry.npmjs.org/clone/-/clone-2.1.0.tgz
npm http GET https://registry.npmjs.org/cors/-/cors-2.8.1.tgz
npm http 200 https://registry.npmjs.org/base64url/-/base64url-2.0.0.tgz
npm http 200 https://registry.npmjs.org/canvas/1.6.2
npm http GET https://registry.npmjs.org/canvas/-/canvas-1.6.2.tgz
npm http 200 https://registry.npmjs.org/color/-/color-1.0.3.tgz
npm http 200 https://registry.npmjs.org/clone/-/clone-2.1.0.tgz
npm http 200 https://registry.npmjs.org/cors/-/cors-2.8.1.tgz
npm http 200 https://registry.npmjs.org/canvas/-/canvas-1.6.2.tgz
npm http 200 https://registry.npmjs.org/glyph-pbf-composite/0.0.2
npm http GET https://registry.npmjs.org/glyph-pbf-composite/-/glyph-pbf-composite-0.0.2.tgz
npm http 200 https://registry.npmjs.org/handlebars/4.0.6
npm http GET https://registry.npmjs.org/handlebars/-/handlebars-4.0.6.tgz
npm http 200 https://registry.npmjs.org/mbtiles/0.9.0
npm http GET https://registry.npmjs.org/mbtiles/-/mbtiles-0.9.0.tgz
npm http 200 https://registry.npmjs.org/glyph-pbf-composite/-/glyph-pbf-composite-0.0.2.tgz
npm http 200 https://registry.npmjs.org/morgan/1.7.0
npm http GET https://registry.npmjs.org/morgan/-/morgan-1.7.0.tgz
npm http 200 https://registry.npmjs.org/handlebars/-/handlebars-4.0.6.tgz
npm http 200 https://registry.npmjs.org/mbtiles/-/mbtiles-0.9.0.tgz
npm http 200 https://registry.npmjs.org/morgan/-/morgan-1.7.0.tgz
npm http 200 https://registry.npmjs.org/express/4.14.1
npm http GET https://registry.npmjs.org/express/-/express-4.14.1.tgz
npm http 200 https://registry.npmjs.org/express/-/express-4.14.1.tgz
npm http 200 https://registry.npmjs.org/node-pngquant-native/1.0.4
npm http GET https://registry.npmjs.org/node-pngquant-native/-/node-pngquant-native-1.0.4.tgz
npm http 200 https://registry.npmjs.org/nomnom/1.8.1
npm http GET https://registry.npmjs.org/nomnom/-/nomnom-1.8.1.tgz
npm http 200 https://registry.npmjs.org/node-pngquant-native/-/node-pngquant-native-1.0.4.tgz
npm http 200 https://registry.npmjs.org/request/2.79.0
npm http 200 https://registry.npmjs.org/pbf/3.0.5
npm http GET https://registry.npmjs.org/request/-/request-2.79.0.tgz
npm http GET https://registry.npmjs.org/pbf/-/pbf-3.0.5.tgz
npm http 200 https://registry.npmjs.org/nomnom/-/nomnom-1.8.1.tgz
npm http 200 https://registry.npmjs.org/request/-/request-2.79.0.tgz
npm http 200 https://registry.npmjs.org/tileshrink-gl
npm WARN optional dep failed, continuing tileshrink-gl@./plugins/tileshrink-gl
npm http 200 https://registry.npmjs.org/sharp/0.17.1
npm http 200 https://registry.npmjs.org/pbf/-/pbf-3.0.5.tgz
npm http GET https://registry.npmjs.org/sharp/-/sharp-0.17.1.tgz
npm http 200 https://registry.npmjs.org/sharp/-/sharp-0.17.1.tgz
npm http 200 https://registry.npmjs.org/tileserver-gl-styles/1.1.0
npm http GET https://registry.npmjs.org/tileserver-gl-styles/-/tileserver-gl-styles-1.1.0.tgz
npm http 200 https://registry.npmjs.org/vector-tile/1.3.0
npm http GET https://registry.npmjs.org/vector-tile/-/vector-tile-1.3.0.tgz
npm http 200 https://registry.npmjs.org/tileserver-gl-styles/-/tileserver-gl-styles-1.1.0.tgz
npm http 200 https://registry.npmjs.org/vector-tile/-/vector-tile-1.3.0.tgz
npm http 200 https://registry.npmjs.org/advanced-pool/0.3.2
npm http GET https://registry.npmjs.org/advanced-pool/-/advanced-pool-0.3.2.tgz
npm http 200 https://registry.npmjs.org/async/2.1.4
npm http GET https://registry.npmjs.org/async/-/async-2.1.4.tgz
npm http 200 https://registry.npmjs.org/advanced-pool/-/advanced-pool-0.3.2.tgz
npm http 200 https://registry.npmjs.org/async/-/async-2.1.4.tgz
npm http 404 https://registry.npmjs.org/mapbox/mapbox-gl-native/3.4.4
npm ERR! 404 'mapbox' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'tileserver-gl'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.12.49-11-default
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "tileserver-gl"
npm ERR! cwd /home/enersis
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code E404
npm http 404 https://registry.npmjs.org/mapbox/sphericalmercator/1.0.5
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/enersis/npm-debug.log
npm ERR! not ok code 0

**Comment by petrsloup** [comment]
Scoped packages are supported in npm 2+ (https://docs.npmjs.com/misc/scope)

Update your npm (and node). You are using very old versions.

**Comment by strech345** [comment]
ok thanks!

**Comment by strech345** [comment]
is it ok to use nodejs4? or should i use 6?

**Comment by petrsloup** [comment]
You should use 4 (at least 4.2.1 should be enough)
