### ISSUE TITLE
possible to use https?

### ISSUE THREAD

**Issue by strech345** [klokantech/tileserver-gl#137]
Hey, we are using https in our solutions. Is it possible to use it also in this server? Or it it otherwise a probleme to this this http in a https page without any error messenges?

**Comment by klokan** [comment]
Setup an nginx with https - and make it a proxy for TileServer GL.

Nginx will pass the X-Forwaded-Proto header automatically and TileServer GL reacts appropriately.

http://tileserver.readthedocs.io/en/latest/deployment.html

We offer support with production deployment: https://openmaptiles.com/support/

**Comment by strech345** [comment]
ok thanks.
