### ISSUE TITLE
Use docker in windows for tileserver

### ISSUE THREAD

**Issue by nijs9** [klokantech/tileserver-gl#138]
I've setup a tile server with docker on windows. Works nice for raster tiles, but when I want to view vector tiles, a blank screen is showing in Chrome.

Another thing is not very clear. How can I add another style to the project? Where can I find the root folder for the tileserver running with docker on windows?

I start the tileserver in this way: docker run -it -v /c/users/001/documents/tiles:/test -p 5200:80 klokantech/tileserver-gl /test/belgium.mbtiles

I have to add styles in /test folder, but where to find that folder?

**Comment by petrsloup** [comment]
- Your Chrome probably does not support WebGL properly, so the vector viewer can not work.

- If you want to serve another style or more mbtiles you need to manually create a config file (instead of the auto-generated one). See http://tileserver.readthedocs.io/en/latest/config.html
