### ISSUE TITLE
Merge geojson file to mbtiles file and use as a source

### ISSUE THREAD

**Issue by JINCHUNGEUN** [klokantech/tileserver-gl#139]
In  style file ,I  used mbtiles and multiple geojson files as sources 
``` 
 "sources": {
    "openmaptiles": {
      "type": "vector",
      "url": "mbtiles://{planet-vector}"
    },
    "bangkok_subway": {
      "type": "geojson",
      "data": "https://rawgit.com/JINCHUNGEUN/data/master/bangkok_subway.geojson"
    },
    "delhi_subway": {
      "type": "geojson",
      "data": "https://rawgit.com/JINCHUNGEUN/data/master/delhi_subway.geojson"
    },
    "malaysia_subway": {
      "type": "geojson",
      "data": "https://rawgit.com/JINCHUNGEUN/data/master/malaysia_subway.geojson"
    },
    "korea_traffic_signals": {
      "type": "geojson",
      "data": "https://rawgit.com/JINCHUNGEUN/data/master/korea_traffic_signals.geojson"
    }
  } 
```
But i want to merge all geojson files to mbtiles file to simplify the source,Is there some tools to do it?

**Comment by klokan** [comment]
https://github.com/mapbox/tippecanoe or mapnik-vt

https://openmaptiles.com/support/

**Comment by JINCHUNGEUN** [comment]
i try the tippecanoe,but it only creates new mbtiles file, not merge geojson file to existing mbtiles file

**Comment by klokan** [comment]
This discussion is not about an issue or bug of TileSever GL software.

We can help you to solve the problem. Please get https://openmaptiles.com/support/
