### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by lukasmartinelli** [klokantech/tileserver-gl#14]
We forked tileserver-gl and removed the serverside rendering part so it is installable via npm.
Perhaps you can publish tileserver-gl to npm and make it work for any Node environment?
This makes it much more usable.

To make it installable from npm and that it can be used as binary you need to expose tileserver-gl as binary. Add entry like `"bin": "bin/tileserver-vector.js"` to `package.json`.

**Comment by klokan** [comment]
I would be very glad id the "tileserver-gl-light" would be the main package OSM2VectorTiles uses.

This is very important for KlokanTech team. I like the idea of having light version of the tileserver which does not have binary compiled dependencies and runs everywhere.

**Comment by petrsloup** [comment]
https://www.npmjs.com/package/tileserver-gl
https://www.npmjs.com/package/tileserver-gl-light
