### ISSUE TITLE
native install tileserver-gl Windows Server 2012

### ISSUE THREAD

**Issue by nijs9** [klokantech/tileserver-gl#141]
I'm running Windows Server 2012, with node.js 4.0 installed. I want to install native tilleserver (docker doesn't work on Windows virtual machine). When I run this command: 

npm install -g tileserver-gl

I get lot of errors. Is this a bug or do I forget something?

Thanks in advance.

**Comment by petrsloup** [comment]
There are some native dependencies for the `tileserver-gl` package. Not all of them support building under Windows.

If you are not able to run Docker, you can use `tileserver-gl-light` variant (without raster tiles generated on the server side).
