### ISSUE TITLE
local city names

### ISSUE THREAD

**Issue by nijs9** [klokantech/tileserver-gl#143]
Very nice project. I want to mention one thing: names of cities are not 'localized'.  For example: The Hague in The netherlands must be 'Den Haag'. On openstreetmap.org these names are localized...

Is this configurable?

**Comment by petrsloup** [comment]
This is a question related to data (I assume you use OpenMapTiles) and styles -- not directly related to the server itself.

There has been some work on multilingual support in OpenMapTiles (see https://github.com/openmaptiles/openmaptiles/pull/190).
