### ISSUE TITLE
 Failed to open X display.

### ISSUE THREAD

**Issue by elvirbts** [klokantech/tileserver-gl#145]
Hi, 1 months ago I use npm and install tileserver and mbtiles from osm2vectortiles and all was working fine, but I try to install it again and after I start all I get this error:

tileserver-gl zurich_switzerland.mbtiles
Starting tileserver-gl v1.5.0
Automatically creating config file for zurich_switzerland.mbtiles
Run with --verbose to see the config file here.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open X display.
Aborted

any help?

**Comment by klokan** [comment]
Duplicate: https://github.com/klokantech/tileserver-gl/issues?utf8=%E2%9C%93&q=is%3Aissue%20Failed%20to%20open%20X%20display.%20

Use Docker or XVFB
