### ISSUE TITLE
Rivers and wateruse not visible on lower zoomlevels

### ISSUE THREAD

**Issue by nijs9** [klokantech/tileserver-gl#146]
Some rivers and other wateruse are not visible on lower zoomlevels in Klokantech basic style, or they are visible but only a thin blue line, even if this is a river wider then 500 meters. Example: Antwerp in Belgium. On zoomlevel 11 you see a thin blue line, when you zoom in you can see a mich wider river and other wateruse you can't see one zoomlevel lower.

**Comment by petrsloup** [comment]
This is not related to the server software, but rather the data (https://openmaptiles.org/) + the style.
