### ISSUE TITLE
TypeError while loading osm-2017-03-27-planet.mbtiles

### ISSUE THREAD

**Issue by stephent** [klokantech/tileserver-gl#147]
I just downloaded 'osm-2017-03-27-planet.mbtiles' last night and am attempting to load them using tileserver-gl 1.5.0. I get a TypeError on startup:

`tileserver_1  | Starting tileserver-gl v1.5.0
tileserver_1  | No MBTiles specified, using osm-2017-03-27-planet.mbtiles
tileserver_1  | Automatically creating config file for osm-2017-03-27-planet.mbtiles
tileserver_1  | /usr/src/app/src/main.js:73
tileserver_1  |       var bounds = info.bounds;
tileserver_1  |                        ^
tileserver_1  | 
tileserver_1  | TypeError: Cannot read property 'bounds' of undefined
tileserver_1  |     at /usr/src/app/src/main.js:73:24
tileserver_1  |     at /usr/src/app/node_modules/mbtiles/lib/mbtiles.js:232:44
tileserver_1  |     at Statement.errBack
(/usr/src/app/node_modules/mbtiles/node_modules/sqlite3/lib/sqlite3.js:16:21)
`

The same config loads the previous version of the planet tiles just fine (osm-2017-01-31-planet.mbtiles).

Any ideas? Thanks!

**Comment by MartinMikita** [comment]
Hello,

There seems to be an error within your downloaded MBTiles. I was able to download the planet and use tileserver-gl correctly.

You may check the MD5 sum of your file with my: `122fb25f38124f452131271d737b927c`
The command: `md5sum osm-2017-03-27-planet.mbtiles`
Note, it will take some time to return a result, please, be patient.

**Comment by stephent** [comment]
Yep...

`md5 osm-2017-03-27-planet.mbtiles
MD5 (osm-2017-03-27-planet.mbtiles) = d44dda58a760d6cb692b4effddf00c75`

That google drive download seems pretty flaky... I see now that it returned a ` 206 Partial Content` to wget when I downloaded the file.

Thanks!

**Comment by petrsloup** [comment]
I will add more sensible error when metada is missing in the mbtiles
