### ISSUE TITLE
Cannot install on Node 6.2 Mac OSX 10.9.5

### ISSUE THREAD

**Issue by aplimovil** [klokantech/tileserver-gl#15]
The npm install process seems to be stopping at the mason compile step:

> /Users/ablopez/Desktop/tileserver-gl/node_modules/mapbox-gl-native/node_modules/.bin/node-pre-gyp configure --clang -- -I./build/node-osx-x86_64/config.gypi -Dcoverage=0 -Dcxx_host= -Goutput_dir=. --depth=. --generator-output=./build/node-osx-x86_64 \
> 	  -Dlibuv_cflags= -Dlibuv_ldflags= -Dlibuv_static_libs=
> /Users/ablopez/Desktop/tileserver-gl/node_modules/mapbox-gl-native/node_modules/.bin/node-pre-gyp build --clang
>   ACTION binding_gyp_core_target_Build_Version_Header Release/obj/gen/include/mbgl/util/version.hpp
>   RULE binding_gyp_core_target_Build_Shaders_0 Release/obj/gen/include/mbgl/shader/box.fragment.hpp
>   RULE binding_gyp_core_target_Build_Shaders_1 Release/obj/gen/include/mbgl/shader/box.vertex.hpp
>   RULE binding_gyp_core_target_Build_Shaders_2 Release/obj/gen/include/mbgl/shader/circle.fragment.hpp
>   RULE binding_gyp_core_target_Build_Shaders_3 Release/obj/gen/include/mbgl/shader/circle.vertex.hpp
>   RULE binding_gyp_core_target_Build_Shaders_4 Release/obj/gen/include/mbgl/shader/dot.fragment.hpp
>   RULE binding_gyp_core_target_Build_Shaders_5 Release/obj/gen/include/mbgl/shader/dot.vertex.hpp
>   RULE binding_gyp_core_target_Build_Shaders_6 Release/obj/gen/include/mbgl/shader/icon.fragment.hpp
>   RULE binding_gyp_core_target_Build_Shaders_7 Release/obj/gen/include/mbgl/shader/icon.vertex.hpp
>   RULE binding_gyp_core_target_Build_Shaders_8 Release/obj/gen/include/mbgl/shader/line.fragment.hpp
>   RULE binding_gyp_core_target_Build_Shaders_9 Release/obj/gen/include/mbgl/shader/line.vertex.hpp
>   RULE binding_gyp_core_target_Build_Shaders_10 Release/obj/gen/include/mbgl/shader/linepattern.fragment.hpp
>   RULE binding_gyp_core_target_Build_Shaders_11 Release/obj/gen/include/mbgl/shader/linepattern.vertex.hpp
>   RULE binding_gyp_core_target_Build_Shaders_12 Release/obj/gen/include/mbgl/shader/linesdf.fragment.hpp
>   RULE binding_gyp_core_target_Build_Shaders_13 Release/obj/gen/include/mbgl/shader/linesdf.vertex.hpp
>   RULE binding_gyp_core_target_Build_Shaders_14 Release/obj/gen/include/mbgl/shader/outline.fragment.hpp
>   RULE binding_gyp_core_target_Build_Shaders_15 Release/obj/gen/include/mbgl/shader/outline.vertex.hpp
>   RULE binding_gyp_core_target_Build_Shaders_16 Release/obj/gen/include/mbgl/shader/pattern.fragment.hpp
>   RULE binding_gyp_core_target_Build_Shaders_17 Release/obj/gen/include/mbgl/shader/pattern.vertex.hpp
>   RULE binding_gyp_core_target_Build_Shaders_18 Release/obj/gen/include/mbgl/shader/plain.fragment.hpp
>   RULE binding_gyp_core_target_Build_Shaders_19 Release/obj/gen/include/mbgl/shader/plain.vertex.hpp
>   RULE binding_gyp_core_target_Build_Shaders_20 Release/obj/gen/include/mbgl/shader/raster.fragment.hpp
>   RULE binding_gyp_core_target_Build_Shaders_21 Release/obj/gen/include/mbgl/shader/raster.vertex.hpp
>   RULE binding_gyp_core_target_Build_Shaders_22 Release/obj/gen/include/mbgl/shader/sdf.fragment.hpp
>   RULE binding_gyp_core_target_Build_Shaders_23 Release/obj/gen/include/mbgl/shader/sdf.vertex.hpp
>   COPY Release/ca-bundle.crt
>   TOUCH Release/obj.target/copy_certificate_bundle.stamp
>   CXX(target) Release/obj.target/core/src/clipper/clipper.o
>   CXX(target) Release/obj.target/core/src/csscolorparser/csscolorparser.o
>   CXX(target) Release/obj.target/core/src/mbgl/annotation/annotation_manager.o
>   CXX(target) Release/obj.target/core/src/mbgl/annotation/annotation_tile.o
> error: invalid value 'c++14' in '-std=c++14'
> error: invalid value 'c++14' in '-std=c++14'
> error: invalid value 'c++14' in '-std=c++14'
> make[2]: *** [Release/obj.target/core/src/csscolorparser/csscolorparser.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> make[2]: *** [Release/obj.target/core/src/mbgl/annotation/annotation_manager.o] Error 1
> make[2]: *** [Release/obj.target/core/src/clipper/clipper.o] Error 1
> error: invalid value 'c++14' in '-std=c++14'
> make[2]: *** [Release/obj.target/core/src/mbgl/annotation/annotation_tile.o] Error 1
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
> gyp ERR! System Darwin 13.4.0
> gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--clang" "--module=/Users/ablopez/Desktop/tileserver-gl/node_modules/mapbox-gl-native/lib/mapbox-gl-native.node" "--module_name=mapbox-gl-native" "--module_path=/Users/ablopez/Desktop/tileserver-gl/node_modules/mapbox-gl-native/lib"
> gyp ERR! cwd /Users/ablopez/Desktop/tileserver-gl/node_modules/mapbox-gl-native
> gyp ERR! node -v v6.2.0
> gyp ERR! node-gyp -v v3.3.1
> gyp ERR! not ok 
> node-pre-gyp ERR! build error 
> node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --clang --module=/Users/ablopez/Desktop/tileserver-gl/node_modules/mapbox-gl-native/lib/mapbox-gl-native.node --module_name=mapbox-gl-native --module_path=/Users/ablopez/Desktop/tileserver-gl/node_modules/mapbox-gl-native/lib' (1)
> node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/ablopez/Desktop/tileserver-gl/node_modules/mapbox-gl-native/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
> node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
> node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:850:16)
> node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
> node-pre-gyp ERR! System Darwin 13.4.0
> node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/ablopez/Desktop/tileserver-gl/node_modules/mapbox-gl-native/node_modules/.bin/node-pre-gyp" "build" "--clang"
> node-pre-gyp ERR! cwd /Users/ablopez/Desktop/tileserver-gl/node_modules/mapbox-gl-native
> node-pre-gyp ERR! node -v v6.2.0
> node-pre-gyp ERR! node-pre-gyp -v v0.6.28
> node-pre-gyp ERR! not ok 
> Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --clang --module=/Users/ablopez/Desktop/tileserver-gl/node_modules/mapbox-gl-native/lib/mapbox-gl-native.node --module_name=mapbox-gl-native --module_path=/Users/ablopez/Desktop/tileserver-gl/node_modules/mapbox-gl-native/lib' (1)
> make[1]: *** [Makefile/node] Error 1
> make: *** [node] Error 2
> npm WARN tileserver-gl@0.0.3 No license field.
> npm ERR! Darwin 13.4.0
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
> npm ERR! node v6.2.0
> npm ERR! npm  v3.8.9
> npm ERR! code ELIFECYCLE
> 
> npm ERR! mapbox-gl-native@3.1.2 install: `node-pre-gyp install --fallback-to-build=false || make node`
> npm ERR! Exit status 2
> npm ERR! 
> npm ERR! Failed at the mapbox-gl-native@3.1.2 install script 'node-pre-gyp install --fallback-to-build=false || make node'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the mapbox-gl-native package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-pre-gyp install --fallback-to-build=false || make node
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs mapbox-gl-native
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls mapbox-gl-native
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/ablopez/Desktop/tileserver-gl/npm-debug.log

Attached is the npm-debug.log

[npm-debug.log.txt](https://github.com/klokantech/tileserver-gl/files/271622/npm-debug.log.txt)

**Comment by klokan** [comment]
Installation via Docker (or Kitematic) is easy and runs fine under Mac OS X.

Direct instalation requires Node v4 - as it is described in README.md.

If you wish to create a Pull Request implementing support for Node v6.2 - we would be glad to review and accept. Right now, we have not a need to make the implementation ourselfs.

Related:
https://github.com/mapbox/mapbox-gl-native/tree/master/platform/node

**Comment by petrsloup** [comment]
Node 6 is not supported. Closing..
