### ISSUE TITLE
Error when running on Windows

### ISSUE THREAD

**Issue by joshas** [klokantech/tileserver-gl#151]
Install local version:
`> npm install tileserver-gl-light`

Run server:
`> node_modules\.bin\tileserver-gl-light zurich_switzerland.mbtiles`

Get an error message complaining about missing styles directory:
> Error: ENOENT: no such file or directory, scandir 'd:\temp\maps\node_modules\til
eserver-gl-light\node_modules\tileserver-gl-styles\styles'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at d:\temp\maps\node_modules\tileserver-gl-light\src\main.js:99:25
    at d:\temp\maps\node_modules\mbtiles\lib\mbtiles.js:267:28
    at ensureCenter (d:\temp\maps\node_modules\mbtiles\lib\mbtiles.js:334:38)
    at d:\temp\maps\node_modules\mbtiles\lib\mbtiles.js:264:17
    at ensureBounds (d:\temp\maps\node_modules\mbtiles\lib\mbtiles.js:305:38)
    at d:\temp\maps\node_modules\mbtiles\lib\mbtiles.js:262:13
    at ensureZooms (d:\temp\maps\node_modules\mbtiles\lib\mbtiles.js:273:60)
    at Statement.<anonymous> (d:\temp\maps\node_modules\mbtiles\lib\mbtiles.js:2 60:9)

tileserver-gl-light is expecting to find styles directory in
`d:\temp\maps\node_modules\tileserver-gl-light\node_modules\tileserver-gl-styles\styles` , but tileserver-gl-styles is actually at `d:\temp\maps\node_modules\tileserver-gl-styles\styles`

Windows 7 64bit, node version 6.10.0

**Comment by klokan** [comment]
You may need to use node version 4.
Be sure to get latest version of tileserver-gl-light - see #113

**Comment by petrsloup** [comment]
The `tileserver-gl-styles` is a dependency of `tileserver-gl-light`, so it should be installed under the `tileserver-gl-light\node_modules\tileserver-gl-styles` path.

```
petr@petrPC:~$ mkdir ~/tmptmp
petr@petrPC:~$ cd ~/tmptmp/
petr@petrPC:~/tmptmp$ npm install tileserver-gl-light
[...]
petr@petrPC:~/tmptmp$ tree -d -L 4
.
└── node_modules
    └── tileserver-gl-light
        ├── docs
        ├── node_modules
        │   ├── advanced-pool
        │   ├── async
        │   ├── base64url
        │   ├── clone
        │   ├── color
        │   ├── cors
        │   ├── express
        │   ├── glyph-pbf-composite
        │   ├── handlebars
        │   ├── http-shutdown
        │   ├── @mapbox
        │   ├── mbtiles
        │   ├── morgan
        │   ├── nomnom
        │   ├── pbf
        │   ├── proj4
        │   ├── request
        │   ├── tileserver-gl-styles
        │   └── vector-tile
        ├── public
        │   ├── resources
        │   └── templates
        ├── src
        └── test

28 directories
```

You can try running `npm install -g tileserver-gl-light` to install the package as a global package rather than in the local node_modules folder.
