### ISSUE TITLE
Responce on GetTile

### ISSUE THREAD

**Issue by PaulJurich** [klokantech/tileserver-gl#153]
I apologize for my poor English, but would like to ask for advice in setting up your product.
When you type the following in the address bar of the browser:
`http: //<ipadress>/tileserver/tileserver.php?service=wmts&reguest=gettile&version=1.0.0`
service returns me the answer:
**_wmts&reguest ([]);_**
Please explain to me that I'm doing wrong, maybe additional settings are required?
Also I ask to explain, in what directory in relation to the file tileserver.php should I place the cache of tiles?

**Comment by klokan** [comment]
This is the repository for TileServer GL project...

It seems you are setting up a different project - the TileServer.php.
The relevant repository is https://github.com/klokantech/tileserver-php. 

We can offer you personal support from the project developers via https://openmaptiles.com/support/
