### ISSUE TITLE
Nginx in front of tileserver [Question]

### ISSUE THREAD

**Issue by sweco-semtne** [klokantech/tileserver-gl#158]
Hi,
I'm trying to setup tileserver-gl as a docker container with nginx in front of it and I'm obviously doint something wrong. 

I would like to map "host/yyy/map/styles " to docker the docker container "/styles" etc. 

It works for the initial loading of the styles but the actual paths in the returned response from tileserver-gl doesn't reflect the additional path from nginx. 

```
 location /yyy/map/ {
            proxy_pass http://tileserver/;
            #proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Accept-Encoding "";
            sub_filter "http://host.domain.com/styles/" "http://host.domain.com/yyy/map/styles/";
            sub_filter "http://host.domain.com/data/" "http://host.domain.com/yyy/map/data/";
            sub_filter_once off;
        }

```

Is there a more elaborate example of setting up tileserver-gl behind a proxy with docker?

Best regards,
Mats

**Comment by petrsloup** [comment]
It's currently not possible to serve the tiles on other paths (the URLs in the styles and TileJSONs can not be changed).

You can take a look at https://github.com/klokantech/tileserver-gl/pull/86.

Or contact info@klokantech.com and we can provide paid support and help you setup production-ready environment for your exact use case.
