### ISSUE TITLE
Install fail debian 8

### ISSUE THREAD

**Issue by devistar** [klokantech/tileserver-gl#162]
root@seattle-tileserver:/home/gisadmin# npm install -g tileserver-gl
npm WARN deprecated mbtiles@0.9.0: This module has moved: please install @mapbox/mbtiles instead
npm WARN deprecated vector-tile@1.3.0: This module has moved: please install @mapbox/vector-tile instead
npm WARN deprecated tiletype@0.1.0: This module is now under the @mapbox namespace: install @mapbox/tiletype instead
npm WARN deprecated sphericalmercator@1.0.5: This module is now under the @mapbox namespace: install @mapbox/sphericalmercator instead
npm WARN deprecated point-geometry@0.0.0: This module has moved: please install @mapbox/point-geometry instead
npm WARN lifecycle @mapbox/mapbox-gl-native@3.4.4~preinstall: cannot run in wd %s %s (wd=%s) @mapbox/mapbox-gl-native@3.4.4 npm install node-pre-gyp /usr/lib/node_modules/.staging/@mapbox/map
box-gl-native-6eb8f479
/usr/bin/tileserver-gl -> /usr/lib/node_modules/tileserver-gl/src/main.js

> sqlite3@3.1.8 install /usr/lib/node_modules/tileserver-gl/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Success: "/usr/lib/node_modules/tileserver-gl/node_modules/sqlite3/lib/binding/node-v51-linux-x64/node_sqlite3.node" is installed via remote

> @mapbox/mapbox-gl-native@3.4.4 install /usr/lib/node_modules/tileserver-gl/node_modules/@mapbox/mapbox-gl-native
> node-pre-gyp install --fallback-to-build=false || make node

node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/@mapbox/mapbox-gl-native/v3.4.4/node-v51-linux-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/usr/lib/node_modules/tileserver-gl/node_modules/node-pre-gyp/lib/install.js:120:27)
node-pre-gyp ERR! stack     at emitOne (events.js:101:20)
node-pre-gyp ERR! stack     at Request.emit (events.js:191:7)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/usr/lib/node_modules/tileserver-gl/node_modules/request/request.js:1074:10)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:191:7)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:522:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:411:20)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! System Linux 3.16.0-4-amd64
node-pre-gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/tileserver-gl/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd /usr/lib/node_modules/tileserver-gl/node_modules/@mapbox/mapbox-gl-native
node-pre-gyp ERR! node -v v7.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.34
node-pre-gyp ERR! not ok 
403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/@mapbox/mapbox-gl-native/v3.4.4/node-v51-linux-x64.tar.gz
npm install --ignore-scripts # Install dependencies but don't run our own install script.
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--ignore-scripts"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! path /root/.npm/_logs
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall scandir

npm ERR! Error: EACCES: permission denied, scandir '/root/.npm/_logs'
npm ERR!  { Error: EACCES: permission denied, scandir '/root/.npm/_logs'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'scandir',
npm ERR!   path: '/root/.npm/_logs' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
glob error { Error: EACCES: permission denied, scandir '/root/.npm/_logs'
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs' }
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--ignore-scripts"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! path /root/.npm/nan/2.6.2/package
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/root/.npm/nan/2.6.2/package'
npm ERR!  { Error: EACCES: permission denied, mkdir '/root/.npm/nan/2.6.2/package'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/root/.npm/nan/2.6.2/package',
npm ERR!   parent: '@mapbox/mapbox-gl-native' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2017-05-17T09_09_59_593Z-debug.log
Makefile:55: recipe for target 'node_modules' failed
make: *** [node_modules] Error 243
/usr/lib
└── (empty)

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "tileserver-gl"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 2

npm ERR! @mapbox/mapbox-gl-native@3.4.4 install: `node-pre-gyp install --fallback-to-build=false || make node`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @mapbox/mapbox-gl-native@3.4.4 install script 'node-pre-gyp install --fallback-to-build=false || make node'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @mapbox/mapbox-gl-native package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build=false || make node
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @mapbox/mapbox-gl-native
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @mapbox/mapbox-gl-native
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2017-05-17T09_10_08_910Z-debug.log

**Comment by petrsloup** [comment]
Only Node v4 is currently supported
