### ISSUE TITLE
Oneway streets doesn't show any symbol for direction

### ISSUE THREAD

**Issue by SantiagoHorcajo** [klokantech/tileserver-gl#169]
Hello, maybe I've not been able to find any symbolized oneway street with predefined styles (OSM Bright, Positron, Dark Matter or Klokantech Basic), but it would be a good idea to show this information.

**Comment by ImreSamu** [comment]
You can modify the  styles with [maputnik](http://maputnik.com)

The [OpenMapTiles "transportation" layer](https://openmaptiles.org/schema/#transportation) has a `oneway` information. 
```
oneway
=========
Mark with 1 whether way is a oneway (in the direction of the way) or not with 0.
Possible values:
0
1
```

**Comment by SantiagoHorcajo** [comment]
Yes, of course, maybe I didn't explain myself very well. What I meant to say was that it would be a good idea to include oneway street symbology in default tileserver-gl styles
