### ISSUE TITLE
Error: unsupported image type

### ISSUE THREAD

**Issue by tschaub** [klokantech/tileserver-gl#171]
We're seeing frequent `[Error: unsupported image type]` messages logged after the service has been under load for a number of hours.  Another symptom of a problem is very long response times (30s to 1min) for tiles.  Restarting the service solves the issue for a while.

I'll get some better monitoring in place to try to determine what is going on, but I'm curious if the message provides any clues on where to start looking (I see it is not generated by code in this repo).

Thanks for any tips.

**Comment by petrsloup** [comment]
I've occasionally seen this message during development, but not on the production (nor the decrease in performance).

It could depend on the style, format of the sprites, fonts, configuration of the server, or even specific hardware (different GPU, different framebuffer dimensions and raster formats, etc.)...

I'm afraid this could be very hard to pin down.

**Comment by tschaub** [comment]
I'm seeing two places where it looks like this library could be logging the above error:
 * [`serve_rendered.js#L239-L241`](https://github.com/klokantech/tileserver-gl/blob/7de3d8b9c7e6d03a5351bc815cf99fcd0d046e1c/src/serve_rendered.js#L239-L241)
 * [`serve_rendered.js#L351`](https://github.com/klokantech/tileserver-gl/blob/7de3d8b9c7e6d03a5351bc815cf99fcd0d046e1c/src/serve_rendered.js#L351)

The first site looks unlikely to be the culprit.  In both cases, it looks like there should be a `return` after logging the error.  I'll submit a PR for this in case you agree that things should not continue if `err` in these cases.

**Comment by petrsloup** [comment]
I agree it probably does not make much sense to continue rendering when the errors occur at these places.
(The first once is definitely not the origin of the repeating error message as it can happen only once during the initialization.)

However, it's still puzzling why the error happens in the first place (and why it needs some time before occurring).

**Comment by tschaub** [comment]
I'm going to try running a more heavily instrumented version of tileserver-gl and see if we can get any more clues.  There are no glyphs or sprites involved, so it shouldn't be related to that.

**Comment by tschaub** [comment]
I've updated to klokantech/tileserver-gl:v2.1.0 and simplified the config, narrowing down at least one cause of the errors (I think the other was related to upstream 429s).

We have a style that looks something like this:
```js
module.exports = {
  version: 8,
  name: 'Test Style',
  sources: {
    osm: {
      type: 'vector',
      url: 'mbtiles://osm-2017-05-09-planet.mbtiles'
    },
    mosaic: {
      type: 'raster',
      tiles: [
        'https://s3-us-west-2.amazonaws.com/bucket-name/{z}/{x}/{y}.png'
      ],
      tileSize: 256
    }
  },
  layers: [
    {
      id: 'background',
      type: 'background',
      paint: {
        'background-color': 'hsl(0, 0%, 85%)'
      }
    },
    {
      id: 'imagery',
      type: 'raster',
      source: 'mosaic',
      paint: {
        'raster-opacity': 0.85,
        'raster-brightness-min': 0.35
      }
    },
    {
      id: 'water',
      type: 'fill',
      source: 'osm',
      'source-layer': 'water',
      filter: ['all', ['==', '$type', 'Polygon']],
      paint: {
        'fill-color': 'rgb(33,44,72)'
      }
    }
  ]
};
```

The way the S3 bucket is configured, we get a 403 when a tile is not present.

When the client makes a request for one of these tiles through tileserver-gl, we get an empty response after 1 minute (this may be an upstream timeout, didn't confirm).

In the tileserver-gl log, I see this (3/6/5 is an example tile that doesn't exist in S3):
```
mbgl: { class: 'Style',
  severity: 'ERROR',
  text: 'Failed to load tile 3/6/5=>3 for source mosaic: unsupported image type' }
```
