### ISSUE TITLE
Question: Raster image location?

### ISSUE THREAD

**Issue by AndrewDelposen** [klokantech/tileserver-gl#172]
Greetings,
Upon using your server, I am trying to extract the exact png/Raster files for a project. I can tell that the documentation says "/styles/...." but I can't seem to find it. Is there a hidden location of the pngs, or a way to generate them all?

Many Thanks,
AJ

**Comment by petrsloup** [comment]
The images are generated on the fly and returned from the server, they're not saved to a file(s).

If you are running the server locally, you can setup, for example, MapCache and seed it from the localhost.
