### ISSUE TITLE
ERROR:  function delete_empty_keys(hstore) does not exist

### ISSUE THREAD

**Issue by wardo001** [klokantech/tileserver-gl#173]
Hi Klokantech, 

I have successfully installed tileserver-gl and I am now looking forward to creating my own tiles. Great effort on the server software - you guys really are pushing the mapping platform forward! 

I am going through the process to create my own OpenMapTiles following the guide:

https://openmaptiles.org/docs/generate/generate-openmaptiles/

Everything goes well until the last step:

./quickstart.sh

This generates the error below. I have searched around but not found any relevant fixes. I am a bit reluctant to just comment out the offending lines in tileset.sql!

I am running on ubuntu 16.04, in a kvm shell. 

Any help is greatly appreciated. Many thanks.

-------------------------------------------------------------------------------------
====> : Start SQL postprocessing:  ./build/tileset.sql -> PostgreSQL 
      : Source code: https://github.com/openmaptiles/import-sql 
The MIN_ZOOM variable is not set. Defaulting to a blank string.
The MAX_ZOOM variable is not set. Defaulting to a blank string.
The BBOX variable is not set. Defaulting to a blank string.
Timing is on.
CREATE FUNCTION
Time: 25.896 ms
CREATE FUNCTION
Time: 5.357 ms
CREATE FUNCTION
Time: 5.225 ms
CREATE FUNCTION
Time: 11.203 ms
CREATE FUNCTION
Time: 42.732 ms
CREATE FUNCTION
Time: 15.181 ms
CREATE FUNCTION
Time: 22.137 ms
CREATE FUNCTION
Time: 10.969 ms
CREATE FUNCTION
Time: 11.107 ms
CREATE FUNCTION
Time: 11.073 ms
CREATE FUNCTION
Time: 12.521 ms
CREATE FUNCTION
Time: 9.578 ms
CREATE FUNCTION
Time: 10.981 ms
CREATE FUNCTION
Time: 11.039 ms
CREATE FUNCTION
Time: 11.113 ms
CREATE FUNCTION
Time: 11.066 ms
Timing is on.
psql:/sql/tileset.sql:4: ERROR:  function delete_empty_keys(hstore) does not exist
LINE 3:     SELECT delete_empty_keys(slice(tags, ARRAY['int_name', '...
                   ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
Time: 2.186 ms

**Comment by ImreSamu** [comment]
@wardo001:  
please create an issue here: https://github.com/openmaptiles/openmaptiles
( and please link  your full `quickstart.log` , this is created by `./quickstart.sh` )

**Comment by wardo001** [comment]
OK, will do @ImreSamu. Thanks for the swift response.
