### ISSUE TITLE
Docker : Obliged to restart container if new config

### ISSUE THREAD

**Issue by BaptWaels** [klokantech/tileserver-gl#177]
Hi,

I've asked this question here without success #155 

I'm using tileserver-gl with the up to date container from the Docker hub (klokantech/tileserver-gl). 

``` 
$ docker run -v $(pwd):/data -p 8080:80 klokantech/tileserver-gl --verbose
```

From my host, If I modify the file $(pwd)/config.json, I'm obliged to restart my container. Any suggestion to prevent this restart ?

**Comment by klokan** [comment]
Config can now reload with SIGHUB without restart, see:
https://github.com/klokantech/tileserver-gl/pull/155

For guaranteed zero downtime update check blue/green deployment:
http://blog.klokantech.com/2016/08/blue-green-deployment-with-docker-and.html

**Comment by vipyoung** [comment]
@klokan: I'm not sure this is working or may be I'm doing something wrong. I've tried myself without success (see #420 ). Has this merge (https://github.com/maptiler/tileserver-gl/commit/d67a57861ddaf64fb5229d1c5ce91d8cbb970204) been tested with docker?
