### ISSUE TITLE
installing on QNAP NAS

### ISSUE THREAD

**Issue by VNuhaan** [klokantech/tileserver-gl#180]
I try to install the tileserver on a QNAP NAS but I get the following error's (see picture)
![putty](https://user-images.githubusercontent.com/5813554/27371949-070ea016-5663-11e7-81c3-8816f6bf5dd4.png)

Has anyone get the tileserver working on a QNAP NAS?

**Comment by petrsloup** [comment]
I think "no space left on device" is a pretty clear message...

Plus you will probably run into other issues if you try to run tileserver-gl without docker (you need X server, many native libraries for encoding images, etc.). It might be easier to install docker on your machine or run tileserver-gl-light.

**Comment by VNuhaan** [comment]
The QNAP is fresh, no data, only one app installed (node js), 2TB free. No problem I think.

I will see if it is possible to install docker on the QNAP.

**Comment by mgruel** [comment]
@VNuhaan I guess, that the partition has only a fairly limited amount space of the 2 TB allocated.
