### ISSUE TITLE
Problems using Arcgis World Imagery raster tiles on server

### ISSUE THREAD

**Issue by tomsiwik** [klokantech/tileserver-gl#182]
Hi guys.

First of all big thumbs up :+1:  for creating this project. It's such a great, easy to use and helpful tool for starters in the area of geo, maps & similar.

I have a problem setting up a rasterized satellite map on the server (source is ArcGis' world imagery maps). My config & styles are listed in the following gist:

https://gist.github.com/tomsiwik/3986f8a3b160f004e84a61710051131d

Do i need to convert an additional raster mbtiles from the arcgis source or does the server handle proxying to the xyz schema? The examples i have found either use the mapbox or opentiles apis, which isn't helpful in documenting the steps needed to setup a (semi) service independant server.

I am abviously doing something wrong/stupid. If you can help me out i would highly appreciate the assistance. Hope to learn something. Thanks in advance.

**Comment by petrsloup** [comment]
The `tiles` in the style JSON has to be an array (hence the `'source tiles must be an array'` error):
```
"tiles": ["http://server.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}.png"]
```

**Comment by tomsiwik** [comment]
Oh thanks a lot. Sorry for the late response. I haven't looked at the docker logs yet...
