### ISSUE TITLE
Error libGLESv2.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by fire-stone** [klokantech/tileserver-gl#183]
I'm trying to excecute:

tileserver-gl switzerland.mbtiles --verbose and this Error pops up. 

Waht can I do to avoid this error and where can i find the config file. My System is a Ubuntu 64x. The version is tileserver-gl 2.0.0
Thanks in advance

**Comment by petrsloup** [comment]
Installing `libgles2-mesa` package should help

**Comment by christopheblin** [comment]
I've the same error but I also have the libgles2-mesa installed, what is wrong here ?

$>/home/ubuntu# tileserver-gl zurich_switzerland.mbtiles
Starting tileserver-gl v2.1.0
Automatically creating config file for zurich_switzerland.mbtiles
Run with --verbose to see the config file here.
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: libGLESv2.so.2: cannot open shared object file: No such file or directory
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/tileserver-gl/node_modules/@mapbox/mapbox-gl-native/platform/node/index.js:5:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

Here are the commands I've runned to see if libgles2-mesa is correctly installed

$>/home/ubuntu# ls -l /usr/lib/x86_64-linux-gnu/mesa-egl/libGLESv2.so.2
lrwxrwxrwx 1 root root 18 Jan 26 00:17 /usr/lib/x86_64-linux-gnu/mesa-egl/libGLESv2.so.2 -> libGLESv2.so.2.0.0
$>/home/ubuntu# ls -l /usr/lib/x86_64-linux-gnu/mesa-egl/libGLESv2.so.2.0.0
-rw-r--r-- 1 root root 34592 Jan 26 00:17 /usr/lib/x86_64-linux-gnu/mesa-egl/libGLESv2.so.2.0.0

**Comment by zhali** [comment]
also get the error 
Error: libGLESv2.so.2: cannot open shared object file: No such file or directory
Install libgles2-mesa canot fix it

**Comment by hoenic07** [comment]
@romainthiberville : Maybe you need to install `libegl1-mesa` as the error states ``ibEGL`, not `libGLESv2`?

**Comment by K-mikaZ** [comment]
I'm late, but never know-it can be helpful.

In my case:

`chrome://gpu`

Into section:

**Video Acceleration Information** (at the end)

> Log Messages
> [20744: 20744: 0505 / 151840.397379: ERROR: gl_implementation.cc (292)]: Failed to load /usr/lib/chromium/swiftshader/libGLESv2.so: /usr/lib/chromium/swiftshader/libGLESv2.so: Can not open the shared object file: No file or folder of this type
> GpuProcessHostUIShim: The GPU process exited with code 1024.

**Solution:**
`ls /usr/lib/chromium`

> (if the swiftshader folder does not exist)

`sudo mkdir /usr/lib/chromium/swiftshader`
`sudo ln -s /usr/lib/x86_64-linux-gnu/libGLESv2.so /usr/lib/chromium/swiftshader/libGLESv2.so`
`sudo ln -s /usr/lib/x86_64-linux-gnu/libEGL.so /usr/lib/chromium/swiftshader/libEGL.so`

ENJOY :)

**Comment by develCuy** [comment]
I'm getting this error in brave browser. So in ubuntu I should install `libgles2-mesa-dev` in order to get `libGLESv2.so.2` installed, then I do K-mikaZ's links:

```sh
sudo mkdir -p /usr/lib/brave/swiftshader/
sudo ln -s /usr/lib/x86_64-linux-gnu/libGLESv2.so /usr/lib/brave/swiftshader/
sudo ln -s /usr/lib/x86_64-linux-gnu/libEGL.so /usr/lib/brave/swiftshader/
```
For brave beta the path is different:

```sh
sudo mkdir -p /usr/lib/brave-beta/swiftshader/
sudo ln -s /usr/lib/x86_64-linux-gnu/libGLESv2.so /usr/lib/brave-beta/swiftshader/
sudo ln -s /usr/lib/x86_64-linux-gnu/libEGL.so /usr/lib/brave-beta/swiftshader/
```

**Comment by knnurl** [comment]
In my case the files should have been in /usr/lib/arm-linux-gnueabihf/ to catkin_make a ros package, but they were in /usr/lib/arm-linux-gnueabihf/mesa-egl/
Moving them to an upper folder solved my issue. 
Nautilus is a file manager app with sudo rights.
