### ISSUE TITLE
Text is cropped on raster tile 

### ISSUE THREAD

**Issue by Duke74** [klokantech/tileserver-gl#184]
I noticed that when using raster tiles, there is some case where text is cropped.
Here is an example with a peak name situated near the edge of a tile.

![chrome_2017-06-26_18-29-03](https://user-images.githubusercontent.com/1609064/27549902-e50008cc-5a9d-11e7-8860-431587edbb5b.jpg)

Is there any existing workaround to this issue ?

**Comment by petrsloup** [comment]
Duplicate, see #35, #161 and openmaptiles/openmaptiles#191
