### ISSUE TITLE
more docs for tileserver-gl-light / examples?

### ISSUE THREAD

**Issue by zwitter1** [klokantech/tileserver-gl#189]
im a little new to the world of tile servers so pardon me if I'm missing something

So if tileserver-gl-light does not have server side rendering then all I would assume I could get is the vector tiles in a raw form (geojson?). However the only documentation that hints to something close to what im looking for is under "source data" as :

 /data/{mbtiles}/{z}/{x}/{y}.{format}

id love to be able to specify coordinates much like i found here: (bug #161 )
http://demo.tileserver.org/styles/osm-bright/?raster#7/35.862/-121.371

only instead of receiving raster tiles i'd like geojson.

i had to scrounge through the issues tab here to get this example and then i get even more confused as it doesn't appear to match whats in the documentation? where does : "?raster#7/lat/lon" fit in the formatting documented? Is what I am looking to do possible or is tileserver-gl-light explicitly limited to the /data end point as defined only allowing me to iterate through the tiles?

**Comment by klokan** [comment]
Tiles are served typically in the Spherical Mercator.
BTW other coordinate systems (SRS in a defined EPSG) are supported too: https://openmaptiles.com/coordinate-systems/

See a website I made to document the relation between lat/lon and Mercator z/x/y:
http://www.maptiler.org/google-maps-coordinates-tile-bounds-projection/

TileServer GL provides vector data as well as on demand drawn raster tiles.
Tileserver GL Light gives you only the vector data.

The supported vector formats are:
- PBF (Protobuf encoded) vector tiles according to the Mapbox specification:
https://www.mapbox.com/vector-tiles/specification/ available at URLs like:
http://demo.tileserver.org/data/v3/1/0/0.pbf
- GeoJSON available at http://demo.tileserver.org/data/v3/1/0/0.geojson

Documentation is at http://tileserver.readthedocs.io/.

Feel free to improve it and make it better for newbies. The texts are at https://github.com/klokantech/tileserver-gl/tree/master/docs - just fork, edit and make a pull request on Github. New contributions are very welcome and you will help other users of this open-source software...
