### ISSUE TITLE
sudo npm install -g tileserver-gl doesn't work

### ISSUE THREAD

**Issue by fazlerabbi37** [klokantech/tileserver-gl#190]
**_sudo npm install -g tileserver-gl_** doesn't work, returns error **npm update check failed** and asks to run  **_sudo chown -R $USER:$(id -gn $USER) /root/.config_** .After running **_sudo chown -R $USER:$(id -gn $USER) /root/.config_** when I re-run **_sudo npm install -g tileserver-gl_** it gives the same error. I haven't used JS before so please help me out. I am attaching the debug log [here](https://gist.github.com/fazlerabbi37/b9bc9d8e13b9b3e5942fc8c25694fd42)

Thanks in advance!!!

**Comment by petrsloup** [comment]
```
6082 verbose node v8.0.0
```

TileServer GL 2.x.x requires node 6 (1.x.x requires node 4)
