### ISSUE TITLE
Context Path

### ISSUE THREAD

**Issue by ravjanga** [klokantech/tileserver-gl#192]
Is there any way we can setup context path for this. Below is what I am planning to achieve.

HAProxy <----> tileserver on local 127.0.0.1:8081

I would like to proxy every thing like below

https://myip/maps to the tile server.

I tried this and it doesnt seem to work, as some css/js are being referenced with / as the assumption for the context path.

**Comment by birdage** [comment]
see https://github.com/klokantech/tileserver-gl/issues/158, https://github.com/klokantech/tileserver-gl/issues/119 and https://github.com/klokantech/tileserver-gl/issues/85

**Comment by ravjanga** [comment]
I found the above mentioned threads little later. Sorry for raising this. I will close this for now.
Looks like this is not a supported scenario currently. We have worked around this.

**Comment by Laro88** [comment]
This sucks big, seems like mapbox-gl is generating a couple of urls clientside that results in generation of http:// requests that should have been https://
