### ISSUE TITLE
using ngnix in front of dockerized tileserver-gl

### ISSUE THREAD

**Issue by christopheblin** [klokantech/tileserver-gl#195]
Having failed to install from npm (#183), I've tried the docker way

After installing and running docker container, I've put an nginx reverse proxy in front.

Everything seems to work fine since I can request raster tile from https
example : https://myhost/styles/klokantech-basic/11/1072/717.png

The problem is that when I want to access to the tiles via http://myhost/styles/klokantech-basic/?raster#11/47.3790/8.5375, all the urls are rewritten with http://localhost:8080

Here is my nginx config :
server {
  listen          80;
  listen [::]:80 default_server;
  listen 443 ssl http2 default_server;
  listen [::]:443 ssl http2 default_server;

  server_name myhost;

  include snippets/ssl.conf;
  include snippets/ssl-params.conf;

  location / {
    proxy_pass      http://localhost:8080;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}

as per the recommendation in https://github.com/klokantech/tileserver-gl/blob/master/docs/deployment.rst

Is it a bug in the application or am I doing something wrong ?

**Comment by petrsloup** [comment]
Try adding `proxy_set_header  Host               $http_host;`, does it help?

**Comment by christopheblin** [comment]
yes it works, thank you (and sorry for my mistake in the nginx config file which is not related to tileserver at all)

**Comment by juystin** [comment]
> proxy_set_header Host $http_host;

Thank you
