### ISSUE TITLE
Adding dark-matter theme into a fresh docker install does not work

### ISSUE THREAD

**Issue by christopheblin** [klokantech/tileserver-gl#196]
Steps to reproduce
 * docker run -it -v $(pwd):/data -p 8080:80 klokantech/tileserver-gl -V
 * copy the outputed configuration file into /data/config.json
 * stop docker
 * relaunch docker with docker run -it -v $(pwd):/data -p 8080:80 klokantech/tileserver-gl -V -c config.json
 * check that it works
 * download https://raw.githubusercontent.com/openmaptiles/dark-matter-gl-style/master/style.json into /data/darkmatterstyle.json
* modifiy config to have new theme (see at the end)
* check that it does not work :)

Here is the config I added :
    "dark-matter": {
      "style": "/data/darkmatterstyle.json",
      "tilejson": {
        "bounds": [
          8.275,
          47.225,
          8.8,
          47.533
        ]
      }

And here is the error : 
docker run -it -v $(pwd):/data -p 8080:80 klokantech/tileserver-gl -V -c tileserverconf.json
Starting tileserver-gl v2.1.0
Using specified config file from tileserverconf.json
Starting server
Listening at http://[::]:80/
Startup complete
mbgl: { class: 'Style',
  severity: 'ERROR',
  text: 'Failed to load source openmaptiles: 0 - Invalid value.' }
mbgl: { class: 'Style',
  severity: 'ERROR',
  text: 'Failed to load source openmaptiles: 0 - Invalid value.' }
mbgl: { class: 'Style',
  severity: 'ERROR',
  text: 'Failed to load source openmaptiles: 0 - Invalid value.' }
mbgl: { class: 'Style',
  severity: 'ERROR',
  text: 'Failed to load source openmaptiles: 0 - Invalid value.' }
mbgl: { class: 'Style',
  severity: 'ERROR',
  text: 'Failed to load source openmaptiles: 0 - Invalid value.' }
mbgl: { class: 'Style',
  severity: 'ERROR',
  text: 'Failed to load source openmaptiles: 0 - Invalid value.' }
mbgl: { class: 'Style',
  severity: 'ERROR',
  text: 'Failed to load source openmaptiles: 0 - Invalid value.' }
mbgl: { class: 'Style',
  severity: 'ERROR',
  text: 'Failed to load source openmaptiles: 0 - Invalid value.' }
mbgl: { class: 'Style',
  severity: 'ERROR',
  text: 'Failed to load source openmaptiles: 0 - Invalid value.' }
mbgl: { class: 'Style',
  severity: 'ERROR',
  text: 'Failed to load source openmaptiles: 0 - Invalid value.' }
mbgl: { class: 'Style',
  severity: 'ERROR',
  text: 'Failed to load source openmaptiles: 0 - Invalid value.' }
mbgl: { class: 'Style',
  severity: 'ERROR',
  text: 'Failed to load source openmaptiles: 0 - Invalid value.' }
mbgl: { class: 'Style',
  severity: 'ERROR',
  text: 'Failed to load source openmaptiles: 0 - Invalid value.' }
mbgl: { class: 'Style',
  severity: 'ERROR',
  text: 'Failed to load source openmaptiles: 0 - Invalid value.' }

Obviously, this lead to the theme being unusable in the http://localhost:8080/styles/dark-matter/?raster#11/47.37900/8.53750

Please note that I've also tested to docker cp the style.json into /usr/src/app/node_modules/tileserver-gl-styles/styles/dark-matter/style.json but this lead to the same problem

**Comment by petrsloup** [comment]
The issue is, that the `style.json` file in the master branch of https://github.com/openmaptiles/dark-matter-gl-style is not directly usable in the tileserver-gl. It is used by Travis and another variants of the style are automatically created and pushed to the `gh-pages` branch for different purposes (running from cdn, running server, ...).

It should definitely be documented better (somewhere), but this is the file that you need to use:
https://raw.githubusercontent.com/openmaptiles/dark-matter-gl-style/gh-pages/style-local.json

**Comment by christopheblin** [comment]
I've tested with this file and I have the following errors :

mbgl: { class: 'Style',
  severity: 'ERROR',
  text: 'Failed to load sprite: ENOENT: no such file or directory, open \'/data/sprite.json\'' }

Should I do something else than just taking the style.json file ?

**Comment by petrsloup** [comment]
Yes, you also need all the `sprite*` files, since these are used (for POIs and icons) and linked from the style file: https://github.com/openmaptiles/dark-matter-gl-style/tree/gh-pages

+ Path to the fonts needs to be properly configured (but it should be already done if you copied the config from the `--verbose` output)

**Comment by christopheblin** [comment]
ok it works.

I think that the "Using docker" needs a bit more information in the README file :)

I will try to provide a document for this but please tell me how to do a PR since you have no wiki in this project. Should I PR the README.md ?

**Comment by ftballguy45** [comment]
I'm really struggling with this at the moment - how to get a local style to work. The 'preview' style does not suffice

**Comment by RyanDeRose-TomTom** [comment]
I'm using this as my style:
https://raw.githubusercontent.com/openmaptiles/dark-matter-gl-style/gh-pages/style-local.json

but now I'm getting this error:
`ERROR: style "style.json" using unknown mbtiles "v3"! Skipping...`

**Comment by rahimramezanian** [comment]
Hi. 
Thank you I could add dark mode to the map, following 
[this comment](https://github.com/maptiler/tileserver-gl/issues/196#issuecomment-317365631 )
these are my steps.

```
sudo docker image ls
sudo docker run -it 2822955ca112 bin/bash
# Where 2822955ca112 is image id
cd ./usr/src/app/node_modules/tileserver-gl-styles/styles/
mkdir dark
cd dark
# Download files
wget https://raw.githubusercontent.com/openmaptiles/dark-matter-gl-style/gh-pages/sprite.json
wget https://raw.githubusercontent.com/openmaptiles/dark-matter-gl-style/gh-pages/sprite.png
wget https://raw.githubusercontent.com/openmaptiles/dark-matter-gl-style/gh-pages/sprite%402x.json
wget https://raw.githubusercontent.com/openmaptiles/dark-matter-gl-style/gh-pages/sprite%402x.png
wget https://raw.githubusercontent.com/openmaptiles/dark-matter-gl-style/gh-pages/style-local.json
# Change a name
mv style-local.json style.json
exit
```
Now we commit changes
Run next command to find container id that you just changed
```
sudo docker container ls -a
```
then
```
sudo docker commit e09d8d248ef6 map_with_dark
```
where `e09d8d248ef6` is container id
Finally you can run image `map_with_dark` and access the dark mode
