### ISSUE TITLE
Rendering static images bigger then 8000x8000 pixels hangs up server

### ISSUE THREAD

**Issue by devtim123** [klokantech/tileserver-gl#198]
I am trying to render big images for printing from the static endpoint. Unfortunatly that images bigger then 8000x8000 pixels are hanging up the tileserver-gl with the following message:   

`
terminate called after throwing an instance of 'std::runtime_error'
  what():  Couldn't create framebuffer: incomplete attachment
/usr/src/app/run.sh: line 8:    21 Aborted                 (core dumped) node /usr/src/app/ -p 80 "$@"`

Looks like the hardware is at its limit!? I run the tileserver-gl thru docker-container.
This is my Server-Setup:

- 8 Core CPU
- 32 GB RAM
- 600 GB SSD
- Ubuntu 16.04.2 LTS
- Docker version 17.06.0-ce

Is this because of a limit at mapbox-gl-native? Do you have any hints to solve this problem, e.g. to split image in multiple parts and render it together in a second step?

**Comment by petrsloup** [comment]
Yes, this is hardware limit. The mapbox-gl-native creates large buffer on the GPU, but most GPUs don't allow for buffers larger than 8192x8192 pixels (but this really depends on the hardware).

It would be possible to detect very large requests (by default, requests larger than 2048 pixels are denied), split into more parts and then stitch in memory before encoding and returning, but it is not yet implemented (pull requests welcome).

Alternatively, you can create multiple requests and use some other software to do the stitching (e.g. imagemagick).

**Comment by devtim123** [comment]
Hallo again,

I was trying to split the image in multiple parts directly in the tileserver (did a fork), but now the problem is, that the images are not correctly stitched. I think the reason for this is the fuctions which calculates the ZoomLevel for the BBox. The stitching is not pixelperfect, see this image:
![bildschirmfoto 2017-09-04 um 15 41 33](https://user-images.githubusercontent.com/6614670/30029604-20c25d4c-918a-11e7-9ded-d38d2f19cb3d.png)

The code for calculating the ZoomLevel is this:
```

var calcZForBBox = function (bbox, w, h, query) {
    var z = 25;

    var padding = query.padding !== undefined ?
      parseFloat(query.padding) : 0.1;

    var minCorner = mercator.px([bbox[0], bbox[3]], z),
      maxCorner = mercator.px([bbox[2], bbox[1]], z);
    var w_ = w / (1 + 2 * padding);
    var h_ = h / (1 + 2 * padding);

    z -= Math.max(
        Math.log((maxCorner[0] - minCorner[0]) / w_),
        Math.log((maxCorner[1] - minCorner[1]) / h_)
      ) / Math.LN2;

    z = Math.max(Math.log(Math.max(w, h) / 256) / Math.LN2, Math.min(25, z));

    //try to round the zoomlevel to X.XX
    //z = Math.round(z * 100) / 100;

    return z;
  };

```

I was also trying to round the zoomlevel to the last two decimal digits, but same result, no pixel perfect stitches.

**So the question is:** should we rethink the calculation of the zoomlevel or is there an other solution for stitching the map-images?

**Comment by petrsloup** [comment]
@devtim123 There is a default 10% padding around the bounds, have you tried removing that? (Either in the query or just set 0 on the `var padding = ...` line.

**Comment by devtim123** [comment]
yes, this is already removed at the request. I split der image vertically, so i ask me: If i have a 100x100 pixel image and split it in two sections i get two 100x50 pixel images. But how i split it?

- from vertical 0 to 50 pixels and 50 to 100 pixels (this is how i did it)
- or from vertical 0 to 50 pixels and 51 to 100 pixels

maybe thats the problem!?

**Comment by devtim123** [comment]
@petrsloup i was trying to solve the stitching issue without any luck. So i am trying to explain how i split the image by example:

I want a static map-image with dimension 8000x10000 pixels for high-resolution prints. I split the image only vertically and in 2 parts for simplicity. So i get 2 images with 8000x5000 pixels which i want to stitch in the buffer after creating it. For both images i have the values for boundingBox, a width and a height, which are used to calculate the ZoomLevel by transforming the boundingBox-Coordinates to Pixelcoordinates with mercator.px() function (see https://github.com/mapbox/sphericalmercator) and a base zoom of 25. So i have a pixelcoordinate-system with 256 * 2^25 Pixels. With this Corners in Pixelcoodinates the zoom level is calculate by:
```
z -= Math.max(
        Math.log((maxCorner[0] - minCorner[0]) / w),
        Math.log((maxCorner[1] - minCorner[1]) / h)
      ) / Math.LN2;
```
The Zoom-Level is calculated for each part of the stitching image, and the strange thing about this is, that the Zoom-Levels are slightly different after the third decimal digit. I think the calculation of Zoom-Levels for the stitching images are not correct, but i dont know the solution there.

What i also have to mention is that a static map-image with lower zoom-level have a higher offset between the stitching images as a static map-image with higher zoom-level.

Can we trust the calculation of the mercator.px() function? Is there an other way to calculate the zoom level?

**Comment by petrsloup** [comment]
What I think might be the problem:
The image is rendered in mercator projection, but the area is specified in WGS84 (longitude, latitude) bounding box -- so you cannot simply take the lonlat boundingbox and partition the numbers in half.
You need to convert the WGS84 bounds to mercator, divide the bounds in half and then convert back -- this  should be the correct way how to partition the area.

**Comment by devtim123** [comment]
Thank you really much! That was the trick 👍

**Comment by devtim123** [comment]
Hey @petrsloup. I actually was solving the problem by converting the WGS84 bounds to mercator. But what i now mentioned is, that when i want to export the world (z <= 4) as static image, which consists of 9 part-images which i render in a loop, i still have stitching-overlay problems. The more i zoom out then more the images are not fit together. here are two examples:
<img width="1086" alt="bildschirmfoto 2017-11-18 um 19 35 36" src="https://user-images.githubusercontent.com/6614670/32983618-b3ba9c16-cc97-11e7-80cf-c1c8790d26c0.png">
<img width="1092" alt="bildschirmfoto 2017-11-18 um 19 29 52" src="https://user-images.githubusercontent.com/6614670/32983620-b955c38a-cc97-11e7-904f-1e109daa27bc.png">

is this because of the curvature of the earth and the wrong calculation of the zoom of the 9 parts? the mercator coordinates are fitting exactly together, just the rendering do not!

Renderings with zoom > 4 are rendered fine without any overlapping of the images-parts.

**Comment by devtim123** [comment]
I solved the problem by myself. just realized that i was calculating with WGS84 bounds on the center-calculation for the image parts. changing this also to mercator solved the problem. 

Thank you anyway :)
