### ISSUE TITLE
Dynamic layer loading

### ISSUE THREAD

**Issue by manueltimita** [klokantech/tileserver-gl#20]
Is there any way to dynamically change any of the configuration (data & styles) without restarting the server?

Great work, by the way!

**Comment by klokan** [comment]
Thanks for praising. A pleasure to hear you find our work useful...

No, this feature is not available yet. What is your exact use case?

A clean contribution would be welcome! ;-)

At @klokantech, we may need at some point a dynamically drawn polygons (or a highlighted polygon) on top of a JSON style - especially in the Static Maps API. To serve an image like:

<img src="https://maps.googleapis.com/maps/api/staticmap?size=235x190&scale=2&sensor=false&visual_refresh=true&path=color:0xff0000ff%7Cfillcolor:0xff000033%7Cweight:2%7C56.0070925897,-3.2043545251%7C56.0078494139,-3.1241867812%7C55.9629336300,-3.1228842812%7C55.9621780769,-3.2029591943%7C56.0070925897,-3.2043545251">
https://maps.googleapis.com/maps/api/staticmap?size=235x190&scale=2&sensor=false&visual_refresh=true&path=color:0xff0000ff%7Cfillcolor:0xff000033%7Cweight:2%7C56.0070925897,-3.2043545251%7C56.0078494139,-3.1241867812%7C55.9629336300,-3.1228842812%7C55.9621780769,-3.2029591943%7C56.0070925897,-3.2043545251

**Comment by manueltimita** [comment]
Thank you for the quick reply.

The praise is more than deserved. Been testing it last night and it works beautifully, and with such low consumption of RAM and CPU, even when having to pre-render the tiles on the server side. Slick!

My use case is not yet very well defined, but with the other two tiling technologies that I'm using (Mapnik and Geoserver), you get this flexibility: dynamically adding/changing/removing layers, and adding/changing/removing styles. Think of an app that has several users: they will be creating and editing these resources, and publish them as they wish. The server should, ideally, pick up the changes on the fly.

Anyways, a simple workflow would be like this: the user has data in PostGIS, for slicing, dicing and other operations. They would then use SQL queries to export various views of this data as JSON, to the disk. On Node, [tippecanoe](https://github.com/mapbox/tippecanoe) could be spawned as a child process, and convert the JSON to .mbtiles, create a basic style, and then notify tileserver-gl about the new config. The user can then use a UI to view the newly created vector tiles, edit the style, etc.

I am just getting my head around the concept of vector tiles from .mbtiles (as opposed to having them cut dynamically, like with Mapnik) learning as fast as I can, so it would be a little while until I could contribute a PR. I just realised today that one downside of them is that features inside the vector tile cannot be filtered out before serving (unless the tile is pre-rendered, as raster, with something like tileserver-gl). You know, like a quick and dirty row-level security baked into the tile ;-)

Regarding your last point, I didn't realise, but is it possible with vtiles to 'attach' arbitrary GeoJSON to a style?

Thanks!

**Comment by klokan** [comment]
Sounds like your request asks for "reload" of the config on submitting of a SIGHUB or similar event, instead of restart of the server.

**Comment by klokan** [comment]
For config reload there is #22 ticket now.

You have been interested in dynamic data source. Your GL JSON styles may contain a link to load vector tiles from a remote URLs with .pbf. In such case you can setup a vector tile server serving vector tiles directly from you PostGIS.

I think GeoServer can do that now (including caching). See:
https://2016.foss4g-na.org/session/vector-tiles-geoserver-and-openlayers
https://github.com/stefan0722/gs-mvt

Then TileServer-GL can be used just as a GL renderer - serving MapBox GL JSON styles as raster tiles.
We internally use TileServer-GL for prerendered MBTiles in basemaps and other applications, where data are not updated that often (weekly updates for example).

I don't see any other action on this ticket.
