### ISSUE TITLE
ERROR: Font not found: Klokantech Noto Sans Regular 

### ISSUE THREAD

**Issue by renefournier** [klokantech/tileserver-gl#200]
I've cloned Tileserver-GL 2.1.0 and built my own Docker image (using osm-2017-03-20-v3.5-planet.mbtiles). I notice that in non-Roman alphabet places (China and Japan), the localized place names are missing—that is, not in the local characters—only English. Plus, when Tileserver-GL tries to serves tiles for those places, it reports the following kinds of errors:

`
ERROR: Font not found: Klokantech Noto Sans Regular
ERROR: Trying to use Klokantech Noto Sans Bold as a fallback
ERROR: Font not found: Klokantech Noto Sans Bold
ERROR: Trying to use Open Sans Italic as a fallback
`

Any suggestions?

Thanks!

...René

**Comment by klokan** [comment]
Fonts are at https://github.com/openmaptiles/fonts

Deploy them. You can also use OpenMapTiles Server instead (https://openmaptiles.com/server/).

**Comment by lsiden** [comment]
@klokan, I am using tileserver-gl from the docker image. Will the server find the fonts if I download them to _download_dir/_, then mount _download_dir/_ on /usr/src/app/node_modules/tileserver-gl-styles/fonts in the container?  

The fonts in the container dir are all .pdf files, but the fonts in this repo are .ttf files and they are in subdirs with names like "moto-sans".  Will the server be able to find and use them if I mount them as described above?
