### ISSUE TITLE
How to change the default editor map

### ISSUE THREAD

**Issue by DragonSuper** [klokantech/tileserver-gl#201]
I open http://localhost:8081/editor ,will show a blank editor page or default page。
I want to open a custom map ，then to edit it 。How to do?  Thanks

**Comment by klokan** [comment]
You may configure your web server (nginx, apache) to serve a different content at the required URL...

We do directly support that in the OpenMapTiles Server - where you can set a redirect in the step by step wizard directly under the Advanced options. See: https://openmaptiles.com/server/
