### ISSUE TITLE
md5sum of planet_z0_z14.mbtiles

### ISSUE THREAD

**Issue by cameronbraid** [klokantech/tileserver-gl#203]
Does anyone have a or can make a md5sum of the https://openmaptiles.os.zhdk.cloud.switch.ch/v3.3/planet_z0_z14.mbtiles file

I downloaded it (took a long time) and when I use it I get all grey tiles.  I wonder if its corrupt.

Having a md5sum would be a handy way to verify.

Cheers

Cameron

**Comment by klokan** [comment]
Request similar to #147

We track showing of MD5 in downloads under internal ticket https://github.com/klokan/openmaptiles.com/issues/359

It may soon be available at https://openmaptiles.com/downloads/tileset/osm/

Unrelated to TileServer GL software. Closing.
