### ISSUE TITLE
How to use a style downloaded from mapbox.com ?

### ISSUE THREAD

**Issue by shayke** [klokantech/tileserver-gl#204]
I've tried downloading a style.json from mapbox studio but the map is rendered empty.
Are there any docs of using the online mapbox.com editor instead of creating from scratch using maputnik?

EDIT: To clarify, I'd like to use the style offline so I have all the fonts/sprites needed but I'm not sure how the style.json should look like.

**Comment by mmuelder** [comment]
If you download a style from mapbox, I'm guessing you have source urls like "mapbox://youaccount/XYZ". Those sources won't work offline.

**Comment by CraigglesO** [comment]
I was also curious about this. I built a really nice style from mapbox. Downloaded it... no conversion method?

**Comment by petrsloup** [comment]
Changing the source definition in the style is the correct way to do this.

However, if you are trying to use a style that was created for mapbox data, it will not work properly.
OpenMapTiles uses different tile schema (https://openmaptiles.org/schema/) -- the data layers in the tiles are grouped differently with different attributes.
