### ISSUE TITLE
Unable to render raster tiles in 2.1 (vs 1.7)

### ISSUE THREAD

**Issue by WBMol** [klokantech/tileserver-gl#205]
I've set up a fully functional tileserver with various styles on a development server on TileServer 1.7. Now that it was figured out, I did the same installation on a production server (and later on a local computer), which by then installed the version 2.1 TileServer. Both installations were done using the `docker pull` method.

With tileserver 2.1, only vector tiles are functional. I've been unable to get raster tiles, and I've tried a lot. The only difference I can find between the two servers is the tileserver version and the OpenMapTiles version (free vs. latest production set). The latter should not affect the raster rendering. Styles and config is identical, except for the endpoint of the mbtiles dataset(s). The errors I receive upon launching the tileserver 2.1 with the following command:
`sudo docker run --rm -it -v $(pw:/data -p 8080:80 klokantech/tileserver-gl`
which results in these errors:
`mbgl: { class: 'Style',
  severity: 'ERROR',
  text: 'Failed to load source omt: 0 - The document is empty.' }
mbgl: { class: 'Style',
  severity: 'ERROR',
  text: 'Failed to load source omt: 0 - The document is empty.' }
mbgl: { class: 'Style',
  severity: 'ERROR',
  text: 'Failed to load source omt: 0 - The document is empty.' }
mbgl: { class: 'Style',
  severity: 'ERROR',
  text: 'Failed to load source omt: 0 - The document is empty.' }
... etc
`

A minimal example of my config file:

` {
  "options": {
    "paths": {
      "root": "",
      "fonts": "fonts",
      "styles": "styles",
      "mbtiles": "mbtiles"
    }
  },
  "styles": {
    "borders-satellite": {
      "style": "test.json",
      "serve_rendered": true,
      "tilejson": {
        "type": "overlay",
        "bounds": [8.44806, 47.32023, 8.62537, 47.43468]
      }
    }
  },
  "formatQuality": {
    "jpeg": 80,
    "webp": 90,
    "pngQuantization": true,
    "png": 100
  },
  "data": {
    "world-vector": {
      "mbtiles": "world.mbtiles"
    }
  }
}`

here the `style.json`

`{
  "version": 8,
  "name": "Empty Style",
  "metadata": {
    "mapbox:autocomposite": false,
    "mapbox:type": "template",
    "maputnik:renderer": "mbgljs",
    "openmaptiles:version": "3.x"
  },
  "sources": {
    "omt": {
      "type": "vector",
      "url": "http://localhost:8080/data/world-vector.json"
    }
  },
  "glyphs": "https://demo.tileserver.org/fonts/{fontstack}/{range}.pbf",
  "layers": [
    {
      "id": "sea_outline",
      "type": "line",
      "source": "omt",
      "source-layer": "water",
      "layout": {},
      "paint": {
        "line-color": "rgba(25, 25, 25, 1)"
      }
    }
  ],
  "sprites": "https://demo.tileserver.org/fonts/{fontstack}/{range}.pbf",
  "id": "durq19su1"
}`

I've arrived at the point where I think it's a bug in TileServer, or I'm missing something. Documentation is too minimal for me to figure it out. Anyone familiar with this issue?

**Comment by WBMol** [comment]
Temporarily fixed it by building a docker image myself from 1.7.0 source. Issue might be with the preview page @ localhost:8080 still using the old endpoints which have changed in 2.0.0. Haven't looked into it any further.

**Comment by songrui233** [comment]
got the same problem==

**Comment by petrsloup** [comment]
The URL of the endpoints changed in v2 (see release notes: https://github.com/klokantech/tileserver-gl/releases/tag/v2.0.0), so you should update your URL in the style.

However, the recommended way to link style->data is `"url": "mbtiles://{world-vector.json}"` instead of hardcoding hostname and port. (it's also much better for performance).

BTW You should not use `demo.tileserver.org`. It's only for demonstration purposes and might change/be shut down soon. Better way is to download the fonts (https://github.com/openmaptiles/fonts/releases/) and host it with the server locally as well.
