### ISSUE TITLE
Image size over 8000

### ISSUE THREAD

**Issue by dtarnawczyk** [klokantech/tileserver-gl#206]
I've tried to play with the maximum image size and with values over 8000, on two different servers, service has crashed (one running Windows and one Linux machine). Error message was: Couldn't create framebuffer. Have you managed to run the service with bigger image size values ? Could you deffine what are the hardware limits on this ?

**Comment by petrsloup** [comment]
See https://github.com/klokantech/tileserver-gl/issues/198#issuecomment-318315600
