### ISSUE TITLE
how to config tile url to serve for kibana ?

### ISSUE THREAD

**Issue by chenyg0911** [klokantech/tileserver-gl#208]
I use the autonavi as tile serivce, it work fine, the kibana.yml config as below:
`
tilemap.url: 'http://webrd04.is.autonavi.com/appmaptile?lang=zh_cn&size=1&scale=1&style=7&x={x}&y={y}&z={z}'
`
Now  I want to change to tileserver-gl replace autonavi, I try to config as the document:
`
tilemap.url: 'http://localhost:8080/styles/osm-bright/{z}/{x}/{y}'
`
it not work.

I can use visit the url: 
`http://localhost:8080/styles/osm-bright/#11/30.675/104.0595`
the map render normal:
but in kibana request, the tileserver-gl log says:
`
GET /styles/osm-bright/2/1/1 404 5.597 ms - 162
GET /styles/osm-bright/2/2/1 404 5.314 ms - 162
GET /styles/osm-bright/2/1/2 404 7.579 ms - 162
GET /styles/osm-bright/2/2/2 404 6.156 ms - 162
GET /styles/osm-bright/2/1/0 404 1.449 ms - 162
GET /styles/osm-bright/2/3/1 404 1.880 ms - 162
GET /styles/osm-bright/2/2/0 404 2.751 ms - 162
GET /styles/osm-bright/2/0/2 404 17.855 ms - 162
GET /styles/osm-bright/2/0/1 404 18.730 ms - 162
GET /styles/osm-bright/2/3/2 404 18.376 ms - 162
GET /styles/osm-bright/2/1/3 404 10.061 ms - 162
GET /styles/osm-bright/2/2/3 404 10.553 ms - 162
GET /styles/osm-bright/2/0/0 404 0.959 ms - 162
GET /styles/osm-bright/2/3/0 404 3.477 ms - 162
GET /styles/osm-bright/2/0/3 404 7.274 ms - 162
GET /styles/osm-bright/2/3/3 404 14.116 ms - 162
`
How I config the url correctly?

**Comment by petrsloup** [comment]
You need to add format extension to the requests to the individual tiles (`.png`).

Try using `http://localhost:8080/styles/osm-bright/{z}/{x}/{y}.png`

**Comment by chenyg0911** [comment]
Thanks! petsloup. It work!
