### ISSUE TITLE
Polygon overlay in static maps

### ISSUE THREAD

**Issue by klokan** [klokantech/tileserver-gl#21]
We need at some point a dynamically drawn polygons (or a highlighted polygon) on top of a JSON style - especially in the Static Maps API. To serve an image like:

<img src="https://maps.googleapis.com/maps/api/staticmap?size=235x190&scale=2&sensor=false&visual_refresh=true&path=color:0xff0000ff%7Cfillcolor:0xff000033%7Cweight:2%7C56.0070925897,-3.2043545251%7C56.0078494139,-3.1241867812%7C55.9629336300,-3.1228842812%7C55.9621780769,-3.2029591943%7C56.0070925897,-3.2043545251">
https://maps.googleapis.com/maps/api/staticmap?size=235x190&scale=2&sensor=false&visual_refresh=true&path=color:0xff0000ff%7Cfillcolor:0xff000033%7Cweight:2%7C56.0070925897,-3.2043545251%7C56.0078494139,-3.1241867812%7C55.9629336300,-3.1228842812%7C55.9621780769,-3.2029591943%7C56.0070925897,-3.2043545251

**Comment by petrsloup** [comment]
Implemented in v0.4 (see README.md for usage description).
