### ISSUE TITLE
how to got Native language support?

### ISSUE THREAD

**Issue by chenyg0911** [klokantech/tileserver-gl#211]
I want use tileserver-gl as my inner-org tile server.
It work! but the all chars shows as English.
I inspect the mbtile file. the {name} characters is Chinese. 
![2017-09-18 14-04-47](https://user-images.githubusercontent.com/16010372/30530654-245be8b4-9c7b-11e7-800c-1696fe355c87.png)

I try to edit osm-bright/style.json, change {name_en} to {name}, and clone the CJK fonts. from https://github.com/klokantech/klokantech-gl-fonts.

the updated style.json like below:
      "source-layer": "place",
...
        "text-font": [
          "Klokantech Noto Sans CJK Bold",
          "Open Sans Bold",
          "Klokantech Noto Sans Bold"
        ],
        "text-size": {
(...)
        },
        "text-field": "{name}",
        "text-max-width": 8
      },

But it still show English, not chinese.
the tileserver-gl backend output:
...
ERROR: Trying to use Open Sans Italic as a fallback
ERROR: Font not found: Klokantech Noto Sans Bold
ERROR: Trying to use Open Sans Italic as a fallback
ERROR: Font not found: Klokantech Noto Sans Bold
ERROR: Trying to use Open Sans Italic as a fallback
ERROR: Font not found: Klokantech Noto Sans Bold
ERROR: Trying to use Open Sans Italic as a fallback
GET /fonts/Open%20Sans%20Italic,Klokantech%20Noto%20Sans%20Italic,Klokantech%20Noto%20Sans%20CJK%20Regular/0-255.pbf 200 20.542 ms - 78090
GET /fonts/Open%20Sans%20Italic,Klokantech%20Noto%20Sans%20Italic,Klokantech%20Noto%20Sans%20CJK%20Regular/27648-27903.pbf 200 21.971 ms - 69
...

What's the problem?

**Comment by chenyg0911** [comment]
```
/tileserver/node_modules/tileserver-gl-styles/fonts$ ls
KlokanTech Noto Sans Bold         Open Sans Bold
KlokanTech Noto Sans CJK Bold     Open Sans Italic
KlokanTech Noto Sans CJK Regular  Open Sans Regular
KlokanTech Noto Sans Italic       Open Sans Semibold
KlokanTech Noto Sans Regular      README.md

```

**Comment by klokan** [comment]
If you edit the JSON style and replace `{name_en}` by `{name}`, and configure TileServer GL to use the modified style it should run...

Otherwise - try the OpenMapTiles Server (https://openmaptiles.com/server/) which has the setting of the language for each style directly in the step-by-step wizard - including support for transliteration and fallback language...

Your whole world can have places names in Chinese!

Like at https://openmaptiles.org/languages/zh/#1.64/61.4/-7.4

**Comment by chenyg0911** [comment]
yes, I have edited the JSON style like the first post, but it not work.
