### ISSUE TITLE
Icon-images not rendering

### ISSUE THREAD

**Issue by hunt3ri** [klokantech/tileserver-gl#217]
Hi 

I really like the server, however, I can't get the icon-images to render.  The docs suggest putting icons within /icons in your data dir - which I've done to no success

So I have a few svg icons downloaded from mapbox, but I can't persuade the server to find them.  I can get the label to appear but not the associated icon.  Any help would be greatly appreciated.

Thanks
Iain

**Comment by petrsloup** [comment]
You need to create `.json` and `.png` files for the sprites before starting the server -- using SVG directly is not possible at the moment.

You can use https://github.com/mapbox/spritezero-cli to do the conversion
