### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by asecondwill** [klokantech/tileserver-gl#218]
I've tried to install this on ubuntu and debian.  I always end up with  errors around sqllite3 and node-pre-gyp

What is the recommended way to install for a production server?

**Comment by asecondwill** [comment]
btw, these errors are reported elsewhere, which is why i haven't repeated them, also i have worked though trying to fix for quite a few hours.  I'd have to start from scratch to get the original errors.  Let me know if that would be helpful. 

eg https://github.com/klokantech/tileserver-gl/issues/163
(although i'm on debian9, node6, npm 3.10. )

**Comment by klokan** [comment]
Use docker.

If you want a complete packed production setup - try our https://openmaptiles.com/server/.

Otherwise, you need to solve the dependency mess on your Linux distro on each deploy.
Reactions on exact errors are in the different tickets.

**Comment by asecondwill** [comment]
All we really need on this is for one single distro to be documented to a working situation.  docker server isn't really production appropriate.

**Comment by klokan** [comment]
Commands required in Debian 9 Stretch, production ready, are visible inside of
https://github.com/klokantech/tileserver-gl/blob/master/Dockerfile

You need to clone this GitHub repo (or get one of the stable [releases](https://github.com/klokantech/tileserver-gl/releases))

Then install the dependencies:

```
apt-get -qq update
apt-get -y install \
    apt-transport-https \
    curl \
    unzip \
    build-essential \
    python \
    libcairo2-dev \
    libgles2-mesa-dev \
    libgbm-dev \
    libllvm3.9 \
    libprotobuf-dev \
    libxxf86vm-dev \
    xvfb \
apt-get clean
```

and start the software with:

   $ ./run.sh

Wrap this into your distro start scripts or supervisord, etc.

If you need a help with professional production setup - including caching, setting up CDN, configuring everything - it is offered from the developer team at https://openmaptiles.com/ and https://openmaptiles.com/support/

**Comment by klokan** [comment]
Feel free to make a pull request improving the documentation at
http://tileserver.readthedocs.io/en/latest/installation.html

The text can be changed on GitHub here:
https://github.com/klokantech/tileserver-gl/blob/master/docs/installation.rst
