### ISSUE TITLE
Understanding raster renderer pools

### ISSUE THREAD

**Issue by otsaloma** [klokantech/tileserver-gl#219]
Hello,

I have just set up a Tileserver GL instance, primarily for serving raster tiles. I was experiencing some kind of a "warm-up" delay, where if I'd use the server after not having accessed it in a while, it would initially take up to ten seconds for new tiles (not yet cached on the server) to load. After that initial delay, as I would pan and zoom further it would work fast, as I'd expect.

So, I took a look at the code and experimented with the raster renderer pool size and I seem to have gotten rid of that delay by setting both min and max size of the pool to five (the processor count on my server is four).

Do I understand correctly that when the server is idle, anything above min pool size gets eventually killed and then created anew when requests over min pool size come in? A new renderer essentially creates a `mbgl.Map` object. That object creation itself doesn't seem slow, does it do some costly initialization later?

Why is the default renderer count not based on CPU count? Is there any reason to destroy renderers when idle, other than minimizing memory use (which is probably not an issue for me)?

**Comment by petrsloup** [comment]
Yes, the renderer pool behaves as you describe. Although the memory usage by individual renderers is not high, it can increase over time. Also if you have a lot of different styles, having all the renderers ready all the time can be a waste of resources.

However, if you are okay with the memory requirements you can set the pool sizes as you need and there should not be any side-effects.

**Comment by otsaloma** [comment]
The pool creation code has a comment `// TODO: make pool sizes configurable` and that's what I'd like too better than patching the source. I could well do that and send a pull request, adding config file entries `minRendererPoolSize` and `maxRendererPoolSize` and using those for all scale factors and falling back on the current code if not defined. Would that be all right or would you expect something more complicated like pool sizes configurable per scale factor?

**Comment by petrsloup** [comment]
I think it might be useful to define pool sizes differently for different scale factors, but I think it's not required. If you made a PR (it would be very welcome) with the two options you described above, it would already be a nice improvement (please also add these to the documentation as part of the PR https://github.com/klokantech/tileserver-gl/blob/master/docs/config.rst).

**Comment by otsaloma** [comment]
PR filed: #222
