### ISSUE TITLE
Sprites not rendering

### ISSUE THREAD

**Issue by hunt3ri** [klokantech/tileserver-gl#220]
Hi 

I'm continuing to have problems rendering sprites.  I thought I could use your existing sprite sheets to test the server so on my style I've set up the following (using your sprites hosted in S3):

    "glyphs": "https://free.tilehosting.com/fonts/{fontstack}/{range}.pbf?key={key}",
	"sprites": "https://s3-eu-west-1.amazonaws.com/maptrunk/public/basic-v9",

The text appears but the icon doesn't to my continued annoyance.  Any help/pointers would be HUGELY appreciated.  For reference I've attached the style

        {
            "id": "populated-placesgeojson",
            "type": "symbol",
            "source": "local-file",
            "source-layer": "populated_placesgeojson",
            "maxzoom": 20.3,
            "filter": [
                "==",
                "$type",
                "Point"
            ],
             "layout": {
                "text-field": "{NAME}",
                 "text-font": [
                    "OpenSans-Regular"
                ],
                "icon-image": "fast-food-15",
                "icon-size": 1,
                "text-offset": [
                    0,
                    -0.8
                ]
            },
             "visibility": "visible",
            "paint": {
            "text-color": "rgba(0, 0, 0, 1)"
        }
        }

Thanks

**Comment by klokan** [comment]
https://openmaptiles.org/docs/style/mapbox-gl-style-spec/#sprites
Duplicate to #217

**Comment by klokan** [comment]
If you need personal help - order one hour of support time and we can explain everything during a personal video meeting and check your examples, workflow and software setup. See: https://openmaptiles.com/support/
