### ISSUE TITLE
Rendering Hybrid Maps and Tiles from Geoserver

### ISSUE THREAD

**Issue by eickovic** [klokantech/tileserver-gl#221]
I've watched your FOSS4G 2016 presentation and am very interested to configure Tileserver GL as described in the Advanced section of the presentation.  I have read through the configuration and usage documentation and do not find any reference to configure these settings.
Specifically:
1. Tiles from Geoserver or remote tile sources
2. Hybrid Maps
3. Loading tiles from S3 and GCS

Can you provide examples or documentation as to how these features are enabled?

**Comment by petrsloup** [comment]
This is actually a matter of style definition and not the server itself.

The style defines what sources it requires and how to style them visually.

Usually, the default openmaptiles styles (such as https://github.com/openmaptiles/klokantech-basic-gl-style/blob/gh-pages/style-local.json) contain a symbolic referencer to a local mbtiles file:
```
  "sources": {
    "openmaptiles": {
      "type": "vector",
      "url": "mbtiles://{v3}"
    }
  },
```
and the TileServer GL also has dataset with `v3` identifier in it's `config.json`.

However, you can also directly reference remote tiles in the style definition (see https://www.mapbox.com/mapbox-gl-js/style-spec/#sources-vector) such as:
```
  "sources": {
    "mytiles": {
      "type": "vector",
      "tiles": [
        "http://example.com/abc/{z}/{x}/{y}.pbf"
      ]
    },
    "myrastertiles": {
      "type": "vector",
      "tiles": [
        "http://example.com/rastermap/{z}/{x}/{y}.png"
      ]
    }
  },
```

This is only the definition of the sources, in order for the tiles to display properly, you need to change also the `layers` array to display the data from the sources.

Example of style using remote zxy raster tiles with the vector tiles: https://github.com/lukasmartinelli/osm-liberty/blob/gh-pages/style.json
