### ISSUE TITLE
access configuration file to add new style when running as docker container

### ISSUE THREAD

**Issue by geospatialmapmashup** [klokantech/tileserver-gl#225]
I have some very specific vector tiles that I've created with MapBox Tippecanoe and MapBox Studio Classic
I am using Maputnik in another docker container that I am using to make a new style.  
I also have some offline vector tiles mbtiles that I've created from ESRI vector basemap and MapZen Vector tile service and want to load styles for those as well.
I don't see any procedures/directions for loading or specifying a style to use.

**Comment by klokan** [comment]
Documentation of the TileServer GL config related to styles:
http://tileserver.readthedocs.io/en/latest/config.html#styles

The config.json is in the volume.

Seems like you have to modify the JSON style to load all your sources.

There is no action on this issue. Closing.
