### ISSUE TITLE
Use mbtiles file stored on S3 as data

### ISSUE THREAD

**Issue by drzhouq** [klokantech/tileserver-gl#231]
I am wondering whether we can use mbtiles file on S3. It seems the server assume the files are located locally on the "/data" folder. In theory, opening a http stream as data source should not be a problem, but I haven't dug into the codes to see where would be a good place to support mbtiles stored and accessible via http.

**Comment by petrsloup** [comment]
Mbtiles is a SQLite database and it is not designed to be accessed remotely. In theory, it should be possible, but performance would suffer (there can be many non-sequential reads to get a single tile).

Much better solution would be to have the tiles unpacked on the S3 and add support for accessing the tiles as individual files, then 1 file = 1 request.
