### ISSUE TITLE
Docker image update

### ISSUE THREAD

**Issue by webmap2015** [klokantech/tileserver-gl#233]
Hi @petrsloup.

"https://github.com/klokantech/tileserver-mapnik" updated on  Apr 18, 2016

But, "https://github.com/mojodna/tessera" updated on Sep 14 2017.

When will you update "tileserver-mapnik" package and docker image?

Thanks.

**Comment by klokan** [comment]
This request is not related to the tileserver-gl project (this github repo).

Please communicate at the relevant GitHub repository issues.

If you want an immediate update of tileserver-mapnik project you can get it as part of https://openmaptiles.com/support/

**Comment by webmap2015** [comment]
Thanks
