### ISSUE TITLE
gyp ERR! stack Error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by sanysaran** [klokantech/tileserver-gl#234]
I have been trying to install soap client for my project requirement

I have tried following soap clients
npm install soap
npm install node-soap-client
npm install soap-client
npm install strong-soap
npm install easy-soap

I get the following issues while installing

**Installation Error** 
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: self signed certificate in certificate chain
gyp ERR! stack     at Error (native)
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1079:38)
gyp ERR! stack     at emitNone (events.js:86:13)
gyp ERR! stack     at TLSSocket.emit (events.js:185:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:603:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\TKMAK7F\\AppD
ata\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js"
"rebuild"
gyp ERR! cwd C:\Saran\SpringReact\reactwamba\scotch-react-todo\node_modules\ursa

gyp ERR! node -v v6.9.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN scotch-react-router@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fse
vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ursa@0.9.4 (node_modules\ursa):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ursa@0.9.4 install: `node-gyp re
build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ soap@0.23.0
added 117 packages and updated 1 package in 18.123s

**Solutions I tried** 
npm config set strict-ssl false
upgrade your version of npm npm install npm -g --ca=""
tell your current version of npm to use known registrars npm config set ca=""
npm config set registry http://registry.npmjs.org/

**Still facing the same issue - Appreciate if some one cam help me sort this out.**

**Comment by petrsloup** [comment]
I don't think this is related to tileserver-gl at all.
