### ISSUE TITLE
How to add custom osm shapefile.

### ISSUE THREAD

**Issue by MinChanSike** [klokantech/tileserver-gl#239]
Hi, Thanks for your TileServer GL.

How to add custom shape file to current **pbf** docker data?

Can I integrate with Leaflet or OpenLayer js library for client?

What is TileServer GL license term? 

Thank you.

**Comment by petrsloup** [comment]
Modifying existing pbf is not easy, it's much simpler to add additional data sources to the style.


You can take a look at the license terms in LICENSE.md file
