### ISSUE TITLE
Missing content-encoding

### ISSUE THREAD

**Issue by jingsam** [klokantech/tileserver-gl#24]
As I know, glyphs genrated by fontmachine are gzip encoded. So glyphs should be serve with `Content-Encoding: gzip` header.
https://github.com/klokantech/tileserver-gl/blob/master/src/serve_font.js#L53

**Comment by jingsam** [comment]
Sorry. What I previous said is wrong. node-fontnik generates uncompressed gylphs and fontmachine generates compressed

**Comment by klokan** [comment]
It seems like no action here. Closing.
