### ISSUE TITLE
[UPDATED] tileserver-gl command not found

### ISSUE THREAD

**Issue by Namec** [klokantech/tileserver-gl#241]
Hello All,

i have installed TileServer-gl from docker (latest)

everything i ok, and i can ssh'd in the container and download mbtiles file.

but when lunching tileserver-gl mytown.mbtiles, it says commande not found ?????

and i confirme that npm installed (3.10.10)

let the force be with you.

**Comment by hoenic07** [comment]
The command `tileserver-gl` is only available if you install it via `npm install -g tileserver-gl`. But you don't need it when you use docker.
