### ISSUE TITLE
Offline Mapping - capabilities

### ISSUE THREAD

**Issue by jonppierce** [klokantech/tileserver-gl#244]
Hello,

I have installed tileserver-gl and have been trying to come up with a solution for offline mapping and have not been able to do so. I am hoping someone can help with tileserver-gl or maybe even suggest another way if tileserver-gl does not support this. 

Basically, I am trying to download to a mobile device a whole region/city, for 10 - 18 zoom level. From what I can see here is that I can request only one tile at a time...is there a way to get the entire set of tiles for a specified region in one request or maybe even per zoom level requests? 

Any help / suggestions would be greatly appreciated.

Thanks!

Jon

**Comment by roblabs** [comment]
For Offline mobile apps, you will want to obtain the entire data set from zooms 10-18, and serve the data set as an `.mbtiles` file.  

`.mbtiles` is a blob of tiles at all your zooms, thereby giving you all offline data in one package.  

You can download tiles in the `.mbtiles` format from https://openmaptiles.com/downloads/planet,  Be sure to check their terms of service for how you can use the data.

Once you have the `.mbtiles` file served up, then your mobile app can just fetch that file, giving you offline or no connectivity map tiles.

You can see the sample apps showing these concepts at https://openmaptiles.org/mobile or http://RobLabs.com/blog

**Comment by klokan** [comment]
Jon,

For offline mapping sample source code for iOS and Android is available at https://openmaptiles.com/mobile-app/

If you have Intel device to run the server - with Windows, Mac or Linux - check OpenMapTiles Server which after installation runs completely offline:
https://blog.klokantech.com/2017/12/openmaptiles-map-server-the-easiest-way-to-deploy-vector-osm.html

If you are serious about the business use of the TileServer GL and OpenMapTIles software stack - we offer support via https://openmaptiles.com/.

This ticket has no action on this TileServer GL repository. Closing.
