### ISSUE TITLE
install local fonts

### ISSUE THREAD

**Issue by Namec** [klokantech/tileserver-gl#247]
i am wondering if there is any tutorial for installing missing fonts localy

i got this message whene rendering my map :

ERROR: Font not found: Klokantech Noto Sans Bold
ERROR: Trying to use Open Sans Bold as a fallback
GET /fonts/Klokantech%20Noto%20Sans%20Bold/0-255.pbf 200 80025 - 61.492 ms

thank you

**Comment by nafis042** [comment]
If you are installing tileserver-gl from npm then do the following:
1. download fonts from here [https://github.com/klokantech/klokantech-gl-fonts](url)
2. go to tile-server-gl styles module and from that go to fonts folder and paste the fonts. (in my case it was /usr/local/lib/node_modules/tileserver-gl/node_modules/tileserver-gl-styles/fonts/)
3. please be careful about the name of the folder. The folder name should be (klokantech .... ) the downloaded folders has capital 'T'.

**Comment by Namec** [comment]
Thank you i'll try this
