### ISSUE TITLE
static x3 and x4 images not appearing

### ISSUE THREAD

**Issue by nijs9** [klokantech/tileserver-gl#248]
I'v setup an evalution version of OpenMapTiles Map Server. Everything is working fine, but when I try to get hdp tiles in this way:

http://myserver.com/styles/osm-bright/16/33674/21931@3x.png
http://myserver.com/styles/osm-bright/16/33674/21931@4x.png

I get this error message:

Cannot GET /styles/osm-bright/16/33674/21931@3x.png

When using url http://myserver.com/styles/osm-bright/16/33674/21931@2x.png I get a correct image.

Are @3x and @4x only available with paid licences? That's no problem, but I first want to know this before paying :-).

**Comment by petrsloup** [comment]
This question is not related to TileServer-GL directly.

When setting up OpenMapTiles Server, you can select max allowed hidpi factor in advanced options (max `@3x` at the moment), `@2x` is the default value.
