### ISSUE TITLE
There is no wizard at Kitematic

### ISSUE THREAD

**Issue by dingfengboo** [klokantech/tileserver-gl#250]
In https://openmaptiles.com/server/    It said:
step 2,  ... follow the web wizard.
------------
1, I installed Kitematic and launch Tileserver-gl, but can't view wizard. 
![11](https://user-images.githubusercontent.com/34928957/35259135-fac7b0f0-003e-11e8-8864-f4c2b0e0056c.png)

2, It is ok when I use a new mbtiles file. (put it to "data" folder")
![22](https://user-images.githubusercontent.com/34928957/35259174-2ee86942-003f-11e8-9a7c-8dd6a8098f34.png)

3, but I failed to set config.json many times. Is there any sample files?

**Comment by petrsloup** [comment]
This is TileServer GL repository. Questions about OpenMapTiles Server (or data) do not belong here. See https://openmaptiles.com/support/ for info how to get support.

**Comment by dingfengboo** [comment]
I saw it!
wizard for "openmaptiles-server" , not for "tileserver-gl"
