### ISSUE TITLE
Optional extension suffix for .pbf.pict urls

### ISSUE THREAD

**Issue by jackhuang89** [klokantech/tileserver-gl#253]
I want to own a tile server which output .pbf.pict like 

https://free-0.tilehosting.com/data/v3/14/13379/7145.pbf.pict?key=...

Any help or hints, thanks.

**Comment by petrsloup** [comment]
http://tileserver.readthedocs.io/en/latest/config.html

You can use `"pbfAlias": "pbf.pict"`
