### ISSUE TITLE
process static image as cli

### ISSUE THREAD

**Issue by bertrandmd** [klokantech/tileserver-gl#254]
Hello, 
first thanks for your amazing tool !

Do you know if it's possible to use logic behind tileserver-gl as cli library ? (it could be usefull to create raster tiles dynamically from pbf file and style.json, for now we need to restart server every time we want to build static custom image)

thanks for your reply

Bertrand

**Comment by klokan** [comment]
https://github.com/klokantech/thumbnail-gl

Follow @klokantech on Twitter and you would know ;-)

Would be lovely to cooperate with WEMAP more closely...

**Comment by bertrandmd** [comment]
amazing !
thks
