### ISSUE TITLE
Run from command-line without X server running

### ISSUE THREAD

**Issue by johntwill** [klokantech/tileserver-gl#255]
I'm running outside of docker. 

I checked out the repo, then did npm install (with version 6 of node).  BTW, I had to manually install the sharp package after.

Unless I have an X server running, I get:

terminate called after throwing an instance of 'std::runtime_error'
  what():  eglInitialize() failed.

Aborted (core dumped)

I tried running:

 /usr/bin/Xvfb -- :99 -screen 0 1024x768x24 -ac +extension GLX +render -noreset

but I still get the error unless my shell is connected to an X server.  

Is that intended behavior, or is it possible to run without the dependency on the X server?

Thanks,
John

**Comment by petrsloup** [comment]
No, it is not possible to run without X server at the moment.
