### ISSUE TITLE
Reason for not using the node image?

### ISSUE THREAD

**Issue by stirringhalo** [klokantech/tileserver-gl#26]
Is there a particular reason you're not using the node docker image as a "from"?

**Comment by klokan** [comment]
Debian is required esp. for installing xvfb for software GL rendering (typically used in Docker now).

We use debian as base of all our company docker containers, so it is more efficient (our server nodes downloads less data from docker hub).

What for advantages do you see in using official `node` as the base image?

If there are real benefits, dicsussed here and confirmed - would you be able to prepare a pull request?

**Comment by stirringhalo** [comment]
Right, good point! I'm just leary of "curl | bash" as a regular method of installs. There's many ways it can break (incomplete transfers leaving half broken scripts running), DNS hijacking, etc. See stuff like: https://jordaneldredge.com/blog/one-way-curl-pipe-sh-install-scripts-can-be-dangerous/

The real repository is at:

deb https://deb.nodesource.com/${NODEREPO} ${DISTRO} main
deb-src https://deb.nodesource.com/${NODEREPO} ${DISTRO} main

where NODEREPO=node_4.x and I believe DISTRO=stretch or jessie

Just put those two lines into sources.list.d and be done with it? Sure nodesource could be equally malicious, but at least we're only running the scripts that need to be.

**Comment by klokan** [comment]
+1. Pull request passing the tests?

**Comment by stirringhalo** [comment]
Sure thing, I'll do that tonight!

**Comment by klokan** [comment]
Great! Thanks.

BTW we are also working on bringing the code of "light" version into this repo - see #27 
The code may still change a bit - at least until announcement of version 1.0 on FOSS4G 2016.

**Comment by petrsloup** [comment]
I believe this can be closed now (solved by #26).
