### ISSUE TITLE
Labels missing

### ISSUE THREAD

**Issue by MoustafaMahgoub** [klokantech/tileserver-gl#260]
I am working with docker , the tiles are loading but with no street names and no labels. 
error in inspector ,this error comes up.

fonts/Klokantech%20Noto%20Sans%20Regular/0-255.pbf Failed to load resource: the server responded with a status of 502 (Bad Gateway).

**Comment by MoustafaMahgoub** [comment]
![error](https://user-images.githubusercontent.com/34306739/37030086-e5b04a6c-2139-11e8-88b7-12d064c1bc50.png)

**Comment by Rajavelu** [comment]
<img width="1418" alt="screen shot 2018-03-08 at 3 35 05 pm" src="https://user-images.githubusercontent.com/3033600/37145218-570d9b08-22e6-11e8-9655-797606fdf542.png">
Me too facing this issue (labels missing), using docker. Also no error found in console.

**Comment by procogent** [comment]
I had a problem like this.  What I found was that the names of the KlokanTech fonts I cloned from https://github.com/klokantech/klokantech-gl-fonts.git were slightly different than the names in the style json.  The style had "Klokantech" in the names and the fonts from the repo were using "KlokanTech" (notice the subtle case difference).

I simply added symlinks inside my fonts directory in order to support either case:
```
ln -s KlokanTech\ Noto\ Sans\ Bold Klokantech\ Noto\ Sans\ Bold
ln -s KlokanTech\ Noto\ Sans\ CJK\ Bold Klokantech\ Noto\ Sans\ CJK\ Bold
ln -s KlokanTech\ Noto\ Sans\ CJK\ Regular Klokantech\ Noto\ Sans\ CJK\ Regular
ln -s KlokanTech\ Noto\ Sans\ Italic Klokantech\ Noto\ Sans\ Italic
ln -s KlokanTech\ Noto\ Sans\ Regular Klokantech\ Noto\ Sans\ Regular
```

**Comment by MoustafaMahgoub** [comment]
@procogent this is a docker with no custom config file specified,  there is no font directory in the tile server folders

**Comment by Namec** [comment]
same probleme here, has someone figured out how to fix this ?

**Comment by Rajavelu** [comment]
https://github.com/klokantech/tileserver-gl/issues/267#issuecomment-373606433

**Comment by petrsloup** [comment]
This is caused by the incompatibility between data and the bunded styles+fonts. See #271
