### ISSUE TITLE
tileserver-gl-light: 400 (Bad Request) for font using "text-field" in mapbox-gl.js

### ISSUE THREAD

**Issue by tkohr** [klokantech/tileserver-gl#262]
I have installed tileserver-gl-light via npm and have it running on port 4200. Everything works fine serving data from localhost:4200 for my web app on localhost:8080.

However, once I use "text-field" in one of my layers in my app like:
```
'layout': {
      'text-field': '{reg}'
       ...
```
I get the following error:

![tileserver_font_error](https://user-images.githubusercontent.com/6329425/37155907-d7cee320-22e4-11e8-87f3-b69713ac5b32.JPG)

**Comment by tkohr** [comment]
Actually this does not seem to be a bug, but due to the fact that mapbox-gl js uses ["Open Sans Regular","Arial Unicode MS Regular"] as default text-font. This returns a "Font not allowed: Arial Unicode MS Regular"-Error. If I get rid of "Arial Unicode MS Regular" in my client, everything works fine for displaying numbers. Do I loose any characters getting rid of "Arial Unicode MS Regular"?

The following issue pointed me to the solution: https://github.com/openmaptiles/fonts/issues/1

**Comment by klokan** [comment]
I expect this is closed. You have to fix your style JSON to load only fonts you really have on your server.
