### ISSUE TITLE
the speed of raster tile is slow?

### ISSUE THREAD

**Issue by lihuadong1988** [klokantech/tileserver-gl#265]

**Comment by klokan** [comment]
It depends on how you do software setup, what hardware you use, how you do caching, if you have CDN, etc.

I expect (raster) maps at https://tilehosting.com are not slow (if you have good internet connection).

TileServer GL is a low-level rendering component.
If you want a complete map server system try https://openmaptiles.com/server/.

For serious production deployment of our software stack - we can help with performance as part of commercial support. If you are interested contact info@klokantech.com.
