### ISSUE TITLE
Data/Labels not showing on maps 

### ISSUE THREAD

**Issue by Rajavelu** [klokantech/tileserver-gl#267]
Using Docker & tiles rendered. But there are no data or labels presents on maps.  Is there any data related issue? 
Similar to #360. But, No error in console(Fonts pbf also accessible).

<img width="1439" alt="screen shot 2018-03-11 at 12 29 45 am" src="https://user-images.githubusercontent.com/3033600/37280310-6e4712b0-2613-11e8-90d8-d04665a1ead3.png">

**Comment by Namec** [comment]
same probleme here, has someone figured out how to fix this ?

**Comment by Rajavelu** [comment]
I think the issue in style.json.
Refer this link: https://github.com/klokantech/tileserver-gl-styles/issues/2
As suggested in above link, changed {name:latin}\n{name:nonlatin} & {name:en}\n{name:nonlatin} to {name}, labels showing. But still some country names(labels) not showing. Please suggest proper solution to show all labels.

<img width="983" alt="screen shot 2018-03-16 at 10 48 35 am" src="https://user-images.githubusercontent.com/3033600/37504921-a924320e-2907-11e8-8302-c3d960ad8114.png">

**Comment by Namec** [comment]
Great i'll try it,

where exactly you locate this Json file ?

**Comment by Rajavelu** [comment]
@Namec You can find your style.json file on your machine using 
find / -name "style.json"
for eg: /var/lib/docker/.../node_modules/tileserver-gl-styles/styles/osm-bright/style.json.

**Comment by MoustafaMahgoub** [comment]
@Rajavelu Have you solved the problem using docker ?!

**Comment by Rajavelu** [comment]
@MoustafaMahgoub After run the cmd **docker run --rm -it -v $(pwd):/data -p 8080:80 klokantech/tileserver-gl**  you can get style.json in your machine. Try as root user.

I am using centos7.4 and check my file path:
_root@172.20.23.141~#find / -name "style.json"
/var/lib/docker/overlay2/f287b8582a6c5db2b58e3ce54569e88481d141153f5efecfb20a55215556841b/diff/usr/src/app/node_modules/tileserver-gl-styles/styles/osm-bright/style.json_

If still can't find the file, try to re-install docker.

**Comment by petrsloup** [comment]
This is caused by the incompatibility between data and the bunded styles+fonts (see #271). You can solve this by creating a custom config.json file and downloading the correct version of the styles that is compatible with your version of the data.
