### ISSUE TITLE
Convert Mapbox styles to OpenMapTiles styles

### ISSUE THREAD

**Issue by AliFlux** [klokantech/tileserver-gl#268]
Hi.

Is there a way to convert Mapbox styles to OpenMapTiles styles? As far as I've searched, tileserver only supports OpenMapTiles, and there are some pretty amazing map styles at Mapbox. 

https://www.mapbox.com/gallery/

Is there an automated way to convert the style? The style files are too big for manual effort.

Thanks.

**Comment by petrsloup** [comment]
The cartography of OpenMapTiles (structure of the underlying data and the individual layers) is different, therefore the styles are not compatible. There is no way to automatically convert between them.

**Comment by moyaying** [comment]
@AliFlux Have you find any idea to convert?  I am also very interest about this.
