### ISSUE TITLE
Light (no raster rendering) code in this repo

### ISSUE THREAD

**Issue by klokan** [klokantech/tileserver-gl#27]
The master code in this repository should expose also the "tileserver-gl-light" package for use with OSM2VectorTiles.

https://github.com/osm2vectortiles/tileserver-gl-light

It does have practical use-case scenario (and easier installation without binary deps), and if we should keep both packages up-to-date, it makes sense to have then in one repo.

This repo should have code base of both versions.

**Comment by stirringhalo** [comment]
Sounds good, I have a Dockerfile for tileserver-gl-light that you can happily use (https://github.com/stirringhalo/docker-tileserver-gl-light). All that's needed is to put the *.mbtiles into the import directory. The build only contains tileserver-gl-light, the mbtiles are just a volume mount

**Comment by petrsloup** [comment]
We now have a script ready for publishing both `tileserver-gl` and `tileserver-gl-light` to npm.
See https://github.com/klokantech/tileserver-gl/blob/master/PUBLISHING.md and  https://github.com/klokantech/tileserver-gl/blob/master/publish.js for details.
