### ISSUE TITLE
WMTS support without using wmts.maptiler.com

### ISSUE THREAD

**Issue by spatialillusions** [klokantech/tileserver-gl#274]
It would be really nice if it was possible to get WMTS support without using wmts.maptiler.com. The depencency on using wmts.maptiler.com makes it quite tricky to use in a network not connected to the internet.
I might be able to look into creating a pull request for this if you think that it might be a useable feature.

**Comment by blairdgeo** [comment]
:+1:

**Comment by spatialillusions** [comment]
Now we are just waiting for pull #307 to be merged for this to be implemented.

**Comment by petrsloup** [comment]
Implemented in #307, thanks!
