### ISSUE TITLE
Some Contours PBFs Result in 404

### ISSUE THREAD

**Issue by procogent** [klokantech/tileserver-gl#275]
I am using tileserver-gl v2.3.1 with contours-2018-01-08-planet.mbtiles from openmaptiles.com, but some PBFs are resulting in a 404.  Is this a problem with the contours mbtiles or with tileserver-gl?

Here are some examples of ones getting a 404:

/data/contours-planet/10/210/330.pbf
/data/contours-planet/10/211/328.pbf
/data/contours-planet/10/211/329.pbf
/data/contours-planet/10/211/330.pbf
/data/contours-planet/10/212/330.pbf
/data/contours-planet/10/213/330.pbf
/data/contours-planet/10/213/331.pbf
/data/contours-planet/10/214/329.pbf
/data/contours-planet/10/214/330.pbf
/data/contours-planet/10/216/329.pbf
/data/contours-planet/10/216/330.pbf
/data/contours-planet/10/216/331.pbf
/data/contours-planet/13/1309/2854.pbf
/data/contours-planet/13/1309/2857.pbf
/data/contours-planet/13/1309/2858.pbf
/data/contours-planet/13/1309/2859.pbf
/data/contours-planet/13/1309/2860.pbf
/data/contours-planet/13/1309/2861.pbf
/data/contours-planet/13/1309/2862.pbf
/data/contours-planet/13/1309/2863.pbf
/data/contours-planet/13/1310/2840.pbf
/data/contours-planet/13/1310/2841.pbf
/data/contours-planet/13/1310/2853.pbf
/data/contours-planet/13/1310/2856.pbf
/data/contours-planet/13/1310/2866.pbf
/data/contours-planet/14/2616/5725.pbf
/data/contours-planet/14/2617/5722.pbf
/data/contours-planet/14/2617/5724.pbf
/data/contours-planet/14/2617/5725.pbf
/data/contours-planet/14/2618/5723.pbf
/data/contours-planet/14/2618/5724.pbf
/data/contours-planet/14/2618/5725.pbf
/data/contours-planet/14/2619/5714.pbf
/data/contours-planet/14/2619/5715.pbf
/data/contours-planet/14/2619/5716.pbf
/data/contours-planet/14/2619/5719.pbf
/data/contours-planet/14/2619/5720.pbf
/data/contours-planet/14/2619/5721.pbf
/data/contours-planet/14/2619/5722.pbf
/data/contours-planet/14/2619/5723.pbf
/data/contours-planet/14/2620/5714.pbf
/data/contours-planet/14/2620/5715.pbf
/data/contours-planet/14/2620/5716.pbf
/data/contours-planet/14/2620/5720.pbf
/data/contours-planet/14/2620/5721.pbf
/data/contours-planet/14/2620/5722.pbf
/data/contours-planet/14/2621/5714.pbf
/data/contours-planet/14/2621/5721.pbf
/data/contours-planet/14/2621/5738.pbf
/data/contours-planet/14/2622/5721.pbf
/data/contours-planet/14/2622/5733.pbf
/data/contours-planet/14/2622/5734.pbf
/data/contours-planet/14/2622/5735.pbf
/data/contours-planet/14/2623/5722.pbf
/data/contours-planet/14/2627/5721.pbf
/data/contours-planet/9/107/166.pbf
/data/contours-planet/9/108/163.pbf
/data/contours-planet/9/108/164.pbf
/data/contours-planet/9/108/165.pbf
/data/contours-planet/9/117/203.pbf
/data/contours-planet/9/117/204.pbf
/data/contours-planet/9/117/205.pbf
/data/contours-planet/9/118/203.pbf
/data/contours-planet/9/118/204.pbf
/data/contours-planet/9/118/205.pbf
/data/contours-planet/9/119/203.pbf
/data/contours-planet/9/119/204.pbf
/data/contours-planet/9/119/205.pbf
/data/contours-planet/9/120/204.pbf
/data/contours-planet/9/120/205.pbf
/data/contours-planet/9/78/179.pbf

**Comment by petrsloup** [comment]
This is expected behavior.
TileServer GL returns 404 for the tiles not found in the .mbtiles file. (Often some tiles are not present in .mbtiles to save some space if there are no features present in that location.)

**Comment by amirmasud** [comment]
> TileServer GL returns 404 for the tiles not found in the .mbtiles file.

I think it's better to return 204 in this situation and let 404 be only for user wrong requests.  (see #46 )
