### ISSUE TITLE
Add Custom Style after server installation

### ISSUE THREAD

**Issue by Namec** [klokantech/tileserver-gl#279]
Hello All

Currently Runing the latest version of Tileserver-GL using the docker image without any custom settings.

after installation and fine running, i am looking for a way to add new styles to the server, but don't know where to start.

also i am unable to locate in my server config.json file, after the installation is completed

let the force be with you

**Comment by Namec** [comment]
ANY news !!

if not possible how can i package new styles with my tieserver-gl repo

thanks

**Comment by petrsloup** [comment]
You can specify path to custom styles, sprites and fonts using the config file: http://tileserver.readthedocs.io/en/latest/config.html

**Comment by Namec** [comment]
thank you for your response but currently using rancher as container orchestrator, i cannot add the config file to docker run, that's why i am looking for solution when building the image itself or on runtime.

thank you

**Comment by georgbachmann** [comment]
I'd like to do the same... I am running TileServer GL using Kitematic. I've already figured out how to get it to load my own mbtiles source, but I don't yet know how to add a custom style (or edit an existing one)...
Any hints?

**Comment by alex2wong** [comment]
Hi @georgbachmann ,  custom style.json can be added to any directory your config.json refer to.
```
"options": {
    "paths": {
      "root": "",  // root dir for following directory
      "styles": "./styles",  // where style json located.
    }
},
"styles": {
    "klokantech-basic": {
      "style": "klo_style.json",
     }
}
```
for my case,  the klo_style.json is customized , located in root dir/styles/klo_style.json.

Default klokantech-basic style.json is located in **global** node_modules/tileserver-gl-light/node_modules/tileserver-gl-styles/styles/klokantech-basic/style.json.

May it help a little.
