### ISSUE TITLE
Missing tiles

### ISSUE THREAD

**Issue by MoustafaMahgoub** [klokantech/tileserver-gl#285]
Hello, I am using my own tiles on Debian server, 
I currently face this error when I press the viewer and the victor tiles but on the start page, nothing is wrong. 

![screen shot 2018-06-11 at 14 29 30](https://user-images.githubusercontent.com/34306739/41231672-28fcf5fe-6d84-11e8-87d2-956d51689b34.png)
![screen shot 2018-06-11 at 14 32 06](https://user-images.githubusercontent.com/34306739/41231697-3e04e3b2-6d84-11e8-8576-119046fe3cd9.png)

**Comment by petrsloup** [comment]
TileServer GL never returns 502. You have probably some proxy server in front of the TileServer GL (like nginx) and it is not properly configured.
