### ISSUE TITLE
Serve raw MBTtiles files

### ISSUE THREAD

**Issue by frodrigo** [klokantech/tileserver-gl#286]
It would be nice to serve not only the content of MBTiles as raw data, but also allow to download the MBTiles it self.

**Comment by klokan** [comment]
Thanks for your suggestions. I see a practical use case in this...

... but this should be probably done by configuring your webserver (such as nginx) - to expose the directory or individual MBTiles directly.

There is no need for node.js to do this work IMHO. I believe a code for downloading large static files (and resumable downloads, and http range, etc) does not belong to TileServer GL - if it is already very well done in the stable web server you have in front of TileServer GL.
