### ISSUE TITLE
Possible to use Sprites without a style.json on server?

### ISSUE THREAD

**Issue by strech345** [klokantech/tileserver-gl#287]
Hello,

we include the style.json into our application to be more flexible. Thats works great. But now we want to show the sprites. Is it possible to put it to the tileserver without a style.json? Or is it outherwise possible to load it also from application?
Thanks

**Comment by petrsloup** [comment]
No, this is not possible at the moment -- sprites are considered just a part of the style and are therefore served under the style path.

What is your use case? Why do you need to serve sprites that are not used in any style?

**Comment by strech345** [comment]
Our usecase is that we store our styles on appliclation and not on tileserver, because this is for us more flexible and dynamic. Now we want to use also sprites and the question is how to do this without having a style on server. Maybe its possible to store and link it on application?

**Comment by petrsloup** [comment]
If you store the styles elsewhere, it would make sense to me to also store the sprites there. And only use TileServer GL for serving the vector tiles for you.

**Comment by strech345** [comment]
Yes, that makes thense. I read that a local url is possible. 

> 3.4.2 Sprites
If your style requires any sprites, make sure the style JSON contains proper path in the sprite property.
It can be a local path (e.g. my-style/sprite) or remove http(s) location (e.g. https://mycdn.com/
my-style/sprite). 

but for me only a absolute http... works. Do you know how to use a relative path?

**Comment by 808730** [comment]
@petrsloup 
if i store my sprites local in my application, how to link it properly? 
mapbox-gl complains: "Uncaught Error: Unable to parse URL object"

Example (in mapstyle.json): 
"glyphs":  "http:/...", 
"sprite": "/../assets/sprites/"

**Comment by 808730** [comment]
it seems to be NOT possible: https://github.com/mapbox/mapbox-gl-js/issues/4416

**Comment by petrsloup** [comment]
Yes, this is not possible -- the style has to contain absolute URL for the sprites.
