### ISSUE TITLE
Data difference on tile server and when added to project

### ISSUE THREAD

**Issue by m-mapunity** [klokantech/tileserver-gl#288]
I am using tileserver-gl-light to render the tiles.
When I look for my street on the tileserver directly on the 8080 port, I see my street and my style.
Below is the image from 8080 port on the server:

![tile1](https://user-images.githubusercontent.com/40420091/41642552-3a17b9c4-7486-11e8-8c91-f9315f7aebb6.png)

Then I try to include the tiles in the project using leaflet:
               mapunityLayer = L.mapboxGL({
                        style: 'https://tiles.mapunity.com/styles/' + layer_name + '.json',

Now when I look for my street in the project , I dont see the street, though the styling is correct and even the names of the street are messed up.

![tile2](https://user-images.githubusercontent.com/40420091/41642560-4045a5a4-7486-11e8-8eb3-f02d4a06978d.png)

**Comment by petrsloup** [comment]
I suspect you are looking at the vector map in the first picture.
There can be slight visual differences between vector and raster maps. (Because of different software and different versions of mapbox-gl-js and mapbox-gl-native)

**Comment by m-mapunity** [comment]
Both of them are vector maps. I have only vector maps, I dont have raster at all. I am including the same link as part of leaflet layer. The link directly looks different, from when I include it

**Comment by petrsloup** [comment]
The issue is probably still the same -- different version of mapbox-gl-js in TileServer GL and in the Leaflet GL (which is very old and outdated BTW).

Also `https://tiles.mapunity.com/styles/' + layer_name + '.json` is URL of the TileJSON for *raster* tiles, not sure what this would do in the Leaflet GL. You might want to use `https://tiles.mapunity.com/styles/' + layer_name + '/style.json` instead.

**Comment by m-mapunity** [comment]
1.) Nothing comes if I add style.json instead of just .json. I am assuming it gets appended in one of the libraries 
2.) I agree that I am using a old version of GL, but there is an interesting observation:

The same project when opened in the latest browser (either on phone or laptop) shows the streets missing. Only on my laptop, Chrome Version 48.0.2564.116 I see some streets get missing. This is not a major issue but I wanted to understand why this could happen
