### ISSUE TITLE
Some raster caching on disk

### ISSUE THREAD

**Issue by stirringhalo** [klokantech/tileserver-gl#29]
Would there be an interest with having some temporary caching on disk to avoid rendering the same tiles over? 

Not sure what would the purge criteria be, perhaps solely on disk size. Every request touches the cached tile. If the size limit is met, start purging from the least recently access to most recently accessed.

**Comment by klokan** [comment]
I believe it does not belong to this repository and to the code of this project.

The cache can be done externally easily, and more efficiently - with CDN, squid, varnish, mapcache, mapproxy, etc. choose the one you want.

External projects are better in caching then a hacked internal cache. If tileserver-gl is used as a microservice, there are other microservices for caching which you can configure in your production deployment for the online service.

**Comment by petrsloup** [comment]
I agree with @klokan -- there are many tools that can be used to handle this very efficiently in production environment and there is no need to try to solve it internally as part of this project.

**Comment by stirringhalo** [comment]
Sounds good, I don't disagree. Depending on ease of use, do you think it would be worth mentioning any easy/lightweight ones in the instructions as a optional step? I don't want anyone to dismiss this server out of hand for being slow when it's largely a caching issue.

**Comment by klokan** [comment]
I guess we can make a demonstration of how to make a disk cache with WMS, WMTS & KML under https://github.com/klokantech/tileserver-gl-mapproxy

@stirringhalo feel free to make a Pull Request with first Dockerfile or mapproxy config into that repository if you want to play with this. Details under https://github.com/klokantech/tileserver-gl-mapproxy/issues/1

Otherwise, @klokantech team jumps on this later (maybe on FOSS4G coding sprint?) -  it has lower priority than TileServer-GL core now.

**Comment by phainv88** [comment]
Dear Klokan,

I am new about map. i have followed below steps:
1. convert shapefile to postgis data
2. using tegola to public pbf from postgis data
3. using tileserver gl to connect to pbf
4. finish showing raster map/vector map on tileserver

My problem: showing raster map is so heavy, i want to pre-cache raster images somewhere, but i don't know how to do it. Please help me

**Comment by harry-wilson** [comment]
> I guess we can make a demonstration of how to make a disk cache with WMS, WMTS & KML under https://github.com/klokantech/tileserver-gl-mapproxy
> 
> @stirringhalo feel free to make a Pull Request with first Dockerfile or mapproxy config into that repository if you want to play with this. Details under [klokan/tileserver-gl-mapproxy#1](https://github.com/klokan/tileserver-gl-mapproxy/issues/1)
> 
> Otherwise, @klokantech team jumps on this later (maybe on FOSS4G coding sprint?) - it has lower priority than TileServer-GL core now.

@klokan your github link does not exist. Can you please correct it?
