### ISSUE TITLE
Optimize rendering concurrency

### ISSUE THREAD

**Issue by petrsloup** [klokantech/tileserver-gl#3]
Have more `mbgl.Map` instances ready to be able to process more requests simultaneously.

**Comment by petrsloup** [comment]
Dynamic pool of map instances (creating and releasing instances as needed) is implemented in `mappool` branch, but there are probably some issues in `mbgl.Map` itself, causing segfaults.

**Comment by petrsloup** [comment]
This is now in `master`.

There are some issues with the mesa3d graphics library and concurrent rendering.
The Dockerfile is now based on `debian:stretch` (`testing`) to get `libgl1-mesa-dri` 11.1.2 which does seem to be stable (as opposed to 10.3.2 in `jessie`).
Concurrent rendering (via multiple instances) is fully supported by mapbox-gl-native (see [ticket 4215](https://github.com/mapbox/mapbox-gl-native/issues/4215)).

The tileserver-gl server now has dynamic pool of instances with 4-16 instances for scale 1; 2-8 for `@2x`; 2-4 for `@3x`. (for each style)
It might be useful to make this somehow configurable in the config file (together with the available scales? -- we can easily go higher than `@3x`).

**Comment by klokan** [comment]
BTW our dedicated servers have hardware accelerated GPU with available X.org driver.
Before production deploy it would be worth to check performance if these are turned on vs. emulated on CPU.
Related ticket: https://github.com/klokan/internal/issues/39
