### ISSUE TITLE
Deploy and tests on Amazon GPU instance

### ISSUE THREAD

**Issue by klokan** [klokantech/tileserver-gl#30]
TODO: Deploy and test (like in #9) on Amazon NVidia CUDA instance:
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using_cluster_computing.html

**Comment by stirringhalo** [comment]
I'd be interested in testing after my July 31st due date, but I have two GTX 650 tis handy to test locally. Might be best for testing as you minimize congestion with the cards.

@petrsloup I see in the performance branch there is a perf.js script. How was that being used for the testing in #9 ?

**Comment by stirringhalo** [comment]
I will need assistance on this to test locally. Looks like my GTX 650 won't play nice with https://github.com/thewtex/docker-opengl-nvidia.

**Comment by klokan** [comment]
Running it without docker is fine on your computer? See README.md.

**Comment by stirringhalo** [comment]
I've got other pressing tasks, so this is low priority for me, especially if there's a caching functionality with 3rd part tools. Feel free to close.

**Comment by klokan** [comment]
Google offers now GPU machines in their cloud as well: https://cloud.google.com/gpu/

**Comment by klokan** [comment]
Our production hosting is now using hardware accelerated GPU machines.
The performance is very good.

**Comment by klokan** [comment]
It is the custom plan offered at https://openmaptiles.com/hosting/
with raster tile rendering from vector tiles, custom styles, and optional SLA and high-availability setup with two datacenters, CDN with 100+ caching data centers worldwide.

**Comment by zhali** [comment]
hi, @klokan ,i have an GPU machine(Centos7, Nvidia-384), when i use tileserver-gl to render png tiles, the speed is same as CPU machine, then i use nvidia-smi to check , found the GPU did not do anything, i don't how to make GPU join the render work, do you have any idea?
this is my commad:
xvfb-run -s "-screen 0 1024x768x24 +extension GLX" /usr/bin/tileserver-gl --verbose
thank you

**Comment by klokan** [comment]
You have to run against real X11 with correct OpenGL drivers.
Support is provided via https://openmaptiles.com/support/ - get an hour and contact us.
