### ISSUE TITLE
Serve GeoJSON files

### ISSUE THREAD

**Issue by spatialillusions** [klokantech/tileserver-gl#306]
Really like the tileserver, and just started playing around with custom styles. One thing that I found when I wanted to add a GeoJSON overlay was that I either had to include the data in the style.json file, or that I had to have another server providing the GeoJSON file, and I think it would be really nice if it was possible to share the GeoJSON files using the tileserver as well.

This could be done with a custom protocol or just by adding a path in the same way as for fonts. 

Do you think this would be a good idea so that I should see if I can look into it, or do you think the best solution is to set up another server?

**Comment by spatialillusions** [comment]
I decided to solve this in another way, and I don't think the possibility to serve geojson is within the scope of tileserver-gl when I think more about it.

**Comment by Rajavelu** [comment]
@spatialillusions "I decided to solve this in another way" - can you share details ?

**Comment by spatialillusions** [comment]
I did a script that injects the geojson, generated from SHP files, directly in the styles when the server is restarted. Not the most dynamic way, but we don't update the data so often.
https://github.com/spatialillusions/tileserver-gl-setup/blob/master/tileserver/update-data.js
