### ISSUE TITLE
 Error: EACCES: permission denied, scandir '/data'

### ISSUE THREAD

**Issue by Forensik-IT** [klokantech/tileserver-gl#316]
Hi klokantech!

I have downloaded the mbtile-file for germany from openmaptiles and located it under

`/home/user/tileserver`

after that I navigated to this folder within my bash and used the command:

`docker run --rm -it -v $(pwd):/data -p 8080:80 klokantech/tileserver-gl`

The Error-Msg i get is this:

```
Waiting 3 seconds for xvfb to start...

Starting tileserver-gl v2.4.0
fs.js:961
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: EACCES: permission denied, scandir '/data'
    at Error (native)
    at Object.fs.readdirSync (fs.js:961:18)
    at /usr/src/app/src/main.js:181:22
    at FSReqWrap.oncomplete (fs.js:123:15)
```

I have tried to execute this within different paths and checked the rights on the user and files. Everything should be fine.
Are there any ideas to solve this problem? I would be really thankful for any help!

I accomplished this task on another computer. But not on the one I need. :(

**Comment by PJSosnowski** [comment]
Hi, the same problem here, any ideas how to fix it?

**Comment by PJSosnowski** [comment]
I have found solution here https://stackoverflow.com/a/44142648/4270929
just add ':z' after volume path

**Comment by aleksandrawy** [comment]
@PJSosnowski thanks for help!!!
