### ISSUE TITLE
Responsive CSS for the web page

### ISSUE THREAD

**Issue by klokan** [klokantech/tileserver-gl#33]
So it can be displayed on tablets and mobile phones as well (changeable width of the page and adjustment of padding - to fit different size of the screen).

The design itself is simple enough to easily support this - including the step to see the viewer in fullscreen without any controls and then return.

@daliborjanak would you like to contribute on this one?

See: ed0af943da91cca1f40a94be80abdbf907c64a10

**Comment by daliborjanak** [comment]
Not the best but useful.

**Comment by klokan** [comment]
@daliborjanak could you please give it a bit more love for the mobile phones? Try it on your Nexus - or in the Developer tools in Chrome ! ;-). Thank you a lot!

![screen shot 2016-07-27 at 15 23 08](https://cloud.githubusercontent.com/assets/59284/17176663/0cefe02e-540e-11e6-8f77-0e19decececc.png)

**Comment by daliborjanak** [comment]
I always test it on my nexus :) More love needs more refactoring of html :-/ I will do it

**Comment by klokan** [comment]
Thank you lot!
