### ISSUE TITLE
Failed to parse GeoJSON data

### ISSUE THREAD

**Issue by ZOHOCORPORATIONPVTLTD** [klokantech/tileserver-gl#332]
I am getting below error msg on add source into style json. Kindly help to me fix this.

mbgl: { class: 'ParseStyle',
  severity: 'ERROR',
  text: 'Failed to parse GeoJSON data: 0 - The document is empty.' }

**Comment by AndyHuska** [comment]
I have the same experience with my geojson files referenced in my style file.  The style with the geojson sources works fine in Maputnik and in my offline maplibre-gl-js server.
