### ISSUE TITLE
MBTiles raster source bounds

### ISSUE THREAD

**Issue by Xeenych** [klokantech/tileserver-gl#334]
I have an MBTiles raster source. It has bounds specified in metadata table.
But MapBox Studio shows this source with a white collar, and collar's size is dependent on zoom level.
I think this is the issue of tileserver-gl not MapBox studio.
Tileserver-gl should respect mbtiles bounds. It should fill partially covered tiles with transaprent color.

QGIS as expected shows this mbtile source without any collar.

**Comment by Xeenych** [comment]
Here is the example on my local tileserver-gl instance
http://176.119.158.225:8080/
http://176.119.158.225:8080/styles/basic/?raster#12/43.2840/76.5294
I hope this container will last for a long enough time

You can see two mbtiles layers with yellow collar around.

**Comment by petrsloup** [comment]
TileServer GL does not do any processing of the raster tiles -- it just serves the images.

When there are bounds specified in the metadata, this is passed to the mapbox-gl-native for rendering (if the raster tiles are used in a Style JSON), but it's just used to determine which tiles exist and which don't.

To achieve what you want, you need to prepare the raster data accordingly (with the alpha channel) -- this is also the ideal solution for the best performance.
