### ISSUE TITLE
xvfb-run instead of using xvfb server directly

### ISSUE THREAD

**Issue by hanc2006** [klokantech/tileserver-gl#336]
Is there a reason why the X virtual framebuffer server is started directly on run.sh script instead of using  a wrapper to simplify the interactions?

This is a part of my shell script I use to run the tileserver-gl

`...`
`xvfb-run -s "-screen 0 1024x768x24 +extension GLX" node src/main.js -c config.json --verbose`
`...`

So I avoid checking the waiting time before server is started...

Thank you

**Comment by petrsloup** [comment]
Originally, we used `xvfb-run`, but there were issue on some platforms and we had to switch to the daemon: https://github.com/klokantech/tileserver-gl/issues/185

Then there was also an issue with proper restarting of the container (people tend to stop the container and then "resume" rather then restarting completely).
