### ISSUE TITLE
Cannot start container, exec: \"/bin/bash\": stat /bin/bash: no such file or directory

### ISSUE THREAD

**Issue by KieCap** [klokantech/tileserver-gl#338]
I'm trying to run a container of the latest image using the following command:
`docker run --rm -it -v $(pwd):/data -p 8080:80 klokantech/tileserver-gl --verbose --config config.json`

I'm getting the following error:
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown.`

I'm not terribly knowledgable about docker, but as far as I can see, the base image you are using in the Dockerfile (`node:6.15.1-stretch`) does not exist in the Docker Hub here: https://hub.docker.com/_/node/

This has only started happening after we updated to the latest image.

Can you shed any light on this issue?

**Comment by petrsloup** [comment]
I don't have any issue with the latest version of the docker image. (It's not a problem that the `6.15.1-stretch` is not longer listed.)

Try `docker pull klokantech/tileserver-gl` to make sure you have the latest version.

There might be something wrong with your docker installation? Try some other image, like `docker run hello-world` and see if that works okay (although this definitely would not reveal all possible issues).
