### ISSUE TITLE
Unable to localize names

### ISSUE THREAD

**Issue by BHudsonJSI** [klokantech/tileserver-gl#340]
I want to be able to display names using localization.  e.g. Deutschland instead of Germany.  

I updated the osm-bright/style.json to use {name_de} instead of {name_en}, but it does not change anything.  I have also tried the {name:de} format, it does not work.  I have confirmed that my local style.json is the one being used (it's mapped into docker and the containers see the correct file).

Based on openmaptiles/openmaptiles/pull/190 the localized names should be available as of openmaptiles v3.6.  When I run 'strings osm-2018-12-03-v3.9-planet.mbtiles|grep name_de' I can see that the name_de does exist in the file (as does name:de).

I am using tileserver-gl 2.5.0 (in docker) and osm-2018-12-03-v3.9-planet.mbtiles.  OS is CentOS 7.6.  The map server is stable, other than this issue.

Please provide complete guidance as to how to configure tileserver-gl so that this localization can work.  For now I need to support name_de, but others will be required soon.  Please provide links to documentation if possible.

**Comment by petrsloup** [comment]
Are you sure the style is used? (You can try changing the color of the water or some other clearly visible change.)

Have you also created a complete `config.json` file? It is not enough to just put the `style.json` inside the container, you need to create the config file. See https://tileserver.readthedocs.io/en/latest/config.html
