### ISSUE TITLE
Static map marker/image support

### ISSUE THREAD

**Issue by hanc2006** [klokantech/tileserver-gl#341]
Hello,
I was reading the "endpoint" section and looking for a way to display a marker (or an image) inside the static map. I saw that it is possible to draw a path using coordinates (this works well). Is the behavior of the static endpoints similar to mapbox? [Mapbox Static (Classic)](https://www.mapbox.com/api-documentation/legacy/static-classic/)

Thank you

**Comment by petrsloup** [comment]
No, the static maps api in tileserver-gl does not support markers at the moment, only polygon -- see https://tileserver.readthedocs.io/en/latest/endpoints.html#static-images.
