### ISSUE TITLE
Feature Request: add id field to map

### ISSUE THREAD

**Issue by strech345** [klokantech/tileserver-gl#343]
On the mbtile preview of the map on feature hover the properties will be shown.
It is also possible to save a property at feature id field. I do it because for using featureStates with own id.
But this wouldn't be shown.

Please add the id field also to this pupup, so the user could check it.

**Comment by petrsloup** [comment]
TileServer-GL is using https://github.com/lukasmartinelli/mapbox-gl-inspect for the inspect mode. Any changes to the popup need to be made there.
