### ISSUE TITLE
Raster tiles endpoint in Mapbox-GL

### ISSUE THREAD

**Issue by chebourne** [klokantech/tileserver-gl#346]
What is the endpoint url you need to serve raster tiles in Mapbox-GL:

I have something like this:

        var map = new mapboxgl.Map({
            container: 'map',
            style: {
                "version": 8,
                "sources": {
                    "raster-tiles": {
                        "type": "raster",
                        "url": "https://tileserver.johndoe.com/styles/mystyle/?raster#3/0.0/0.0"
                    }
                },
                "layers": [{
                    "id": "mystyle",
                    "type": "raster",
                    "source": "raster-tiles",
                    "minzoom": 0,
                    "maxzoom": 22
                }]
            },
            center: [0,0],
            zoom: 3
        });

As per the Mapbox example: https://docs.mapbox.com/mapbox-gl-js/example/map-tiles/

With this I get an error:
SyntaxError: "JSON.parse: unexpected character at line 1 column 1 of the JSON data"

Using url for xyz from tileserver-gl frontend: "https://tileserver.johndoe.com/styles/mystyle/{z}/{x}/{y}.png"
Results in a 404 error.

Where am I going wrong?

**Comment by petrsloup** [comment]
The source definition inside the style expects URL to a TileJSON.

There is a link with "TileJSON" on the front page (in this case it would be "https://tileserver.johndoe.com/styles/mystyle.json")

**Comment by chebourne** [comment]
Thanks, is that in the documentation?

**Comment by petrsloup** [comment]
Yes, of course. It's part of the style specification: https://docs.mapbox.com/mapbox-gl-js/style-spec/#sources
