### ISSUE TITLE
Satellite tiles broken

### ISSUE THREAD

**Issue by ZOHOCORPORATIONPVTLTD** [klokantech/tileserver-gl#353]
Few satellite tiles in south India region have weird white color filled  polygons. 

Screenshot : 

![Screen Shot 2019-03-27 at 3 23 34 PM](https://user-images.githubusercontent.com/30683089/55067355-8f914900-50a5-11e9-92f0-3ba62f4d1e79.png)

URL : https://www.maptiler.com/maps/#hybrid//vector/6.13/75.167/9.347

**Comment by petrsloup** [comment]
This is not related to tileserver-gl open source software.

To report issues with MapTiler products use https://support.maptiler.com/
