### ISSUE TITLE
Docker image always uses http://localhost:8080 in production

### ISSUE THREAD

**Issue by mariansedivy** [klokantech/tileserver-gl#356]
Hello Klokans!

I have dowloaded docker image and installed it on my Mac, this works perfectly. But when I install it on our server behind nginx reverse proxy it always tries to load scripts from localhost.
This is my config:
`{
  "options": {
    "paths": {
      "root": "",
      "fonts": "glyphs",
      "sprites": "sprites",
      "styles": "styles",
      "mbtiles": "data"
    },
    "domains": ["our.map.domain"],
    "formatEncoding": {
      "png": 6,
      "jpeg": 80,
      "webp": 90
    }
  },
  "styles": {
    "bright": {
      "style": "bright-v9.json",
      "tilejson": {
        "type": "overlay",
        "bounds": [8.529446, 47.364758, 8.55232, 47.380539]
      }
    },
    "basic": {
      "style": "basic-v9.json",
      "tilejson": {
        "type": "overlay",
        "bounds": [8.529446, 47.364758, 8.55232, 47.380539]
      }
    }
  },
  "data": {
    "slovak-vector": {
      "mbtiles": "osm-2018-12-03-v3.9-europe_slovakia.mbtiles"
    }
  },
  "sources": {
  "source1": {
    "url": "mbtiles://osm-2018-12-03-v3.9-europe_slovakia.mbtiles",
    "type": "vector"
   }
  }
}`

I have downloaded data from here https://github.com/klokantech/tileserver-gl-data but I have even tried it without this, but result was the same.

I run the docker image with this `docker run --rm -it -v $(pwd):/data -p 8080:80 klokantech/tileserver-gl`. I can see the welcome page an go through setup process and everything works until I try to display maps. Then I have many errors in console where Safari is trying to get files from localhost:8080 and not from our.map.domain. It looks like localhost:8080 is hardcoded somewhere inside the docker image. This is part our our style file served from docker on our.map.domain/styles/basic/style.json
`{"version":8,"name":"Basic","sources":{"mapbox":{"url":"http://localhost:8080/data/slovak-vector.json","type":"vector"}},"sprite":"http://localhost:8080/styles/basic/sprite","glyphs":"http://localhost:8080/fonts/{fontstack}/{range}.pbf" ...`

I have tried clean instal without any data and config file, so it downloads Zurich tiles and creates its own config, but result are always the same - on localhost it works, on server not.

Please can you tell me how to fix this? Am I missing something in the config file?

Thank you very much.

**Comment by petrsloup** [comment]
https://github.com/klokantech/tileserver-gl/blob/master/docs/deployment.rst#running-behind-a-proxy-or-a-load-balancer

**Comment by mariansedivy** [comment]
Hi Petr,

thank you very much for pointing me to this direction. I have already set this before, but it looks like there was a mistake in configuration. However I was able to fix it, thanks to you. In case somebody need this setup for nginx here it is: 
```
server {
       server_name YOUR_SERVER_NAME_GOES_HERE;
       listen          80;
       location / {
          proxy_pass http://localhost:8080;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto https;
          proxy_redirect off;
       }
}
```
