### ISSUE TITLE
styles.json incorrect path

### ISSUE THREAD

**Issue by danpe** [klokantech/tileserver-gl#361]
TileServer-gl 2.5.0.

my `https://server.domain.com/style.json` returns:
```
[{"version":8,"name":"Maps Basic","id":"basic","url":"https://server.domain.com//styles/basic/style.json"},{"version":8,"name":"Maps History","id":"history","url":"https://server.domain.com//styles/history/style.json"},{"version":8,"name":"Satellite","id":"satellite","url":"https://server.domain.com//styles/satellite/style.json"},{"version":8,"name":"Satellite Streets","id":"hybrid","url":"https://server.domain.com//styles/hybrid/style.json"}]
```

As you see there are double `//` so this will never work... I never set a public URL.
After reading the code I can never understand how it does work because `utils.getPublicUrl` always make sure the URL as a `/` at the end while `GET style.json` also adds a `/`.

**[utils.js:10](https://github.com/klokantech/tileserver-gl/blob/master/src/utils.js#L10)**
```
module.exports.getPublicUrl = function(publicUrl, req) {
  return publicUrl || (req.protocol + '://' + req.resolvedHost + '/')
}
```

**[server.js:200](https://github.com/klokantech/tileserver-gl/blob/master/src/server.js#L200)**
```
app.get('/styles.json', function(req, res, next) {
    var result = [];
    var query = req.query.key ? ('?key=' + req.query.key) : '';
    Object.keys(serving.styles).forEach(function(id) {
      var styleJSON = serving.styles[id];
      result.push({
        version: styleJSON.version,
        name: styleJSON.name,
        id: id,
        url: utils.getPublicUrl(opts.publicUrl, req) +
             '/styles/' + id + '/style.json' + query
      });
    });
    res.send(result);
  });
```

**Comment by petrsloup** [comment]
Yes, this was an oversight in the `/styles.json` endpoint. (It's not used often, so that's probably why nobody noticed so far.) Fixed in master.
