### ISSUE TITLE
point never shows on tileServer

### ISSUE THREAD

**Issue by hoogw** [klokantech/tileserver-gl#367]
point never shows on tileServer

I setup the tileserver, city_address is point, never shows.
polygon, and lines shows correctly.

No point shows. 

Please advise how to make point shows?

I know why, because in source code, ` type: 'line',
      paint: {'line-color': colorText}
    });`

type is line, for point, it has to be "type": "symbol",

Is there way that before you map.addLayer , to know this layer type is line(point, polygon) ahead of time?

                 `if layer is point {
                                         map.addLayer({
                                                        type: symbol
                                                                 })
                                         }

                   else { 
                                 // for both line and polygon
                                         map.addLayer({
                                                        type: line
                                                                 })
                                         }

`

**Comment by hoogw** [comment]
I kind find a way to solve this problem.
[https://docs.mapbox.com/mapbox-gl-js/example/multiple-geometries/](https://docs.mapbox.com/mapbox-gl-js/example/multiple-geometries/)

Add multiple geometries from one GeoJSON source, 

The key is:
 
    you add all 3 layer for point, line, polygon, with 3 different layer-id
   each layer, you use filter for that type only.
                  `,
"filter": ["==", "$type", "Polygon"]` 


I have a complete code at: 
                       [https://github.com/hoogw/arcgis_viewer/blob/master/public/javascripts/pbf/mapbox_common_share.js](https://github.com/hoogw/arcgis_viewer/blob/master/public/javascripts/pbf/mapbox_common_share.js)

**Comment by petrsloup** [comment]
Seems like this is not an issue in the tileserver-gl, but rather in the viewer setup. (Correctly creating style to show points.)
