### ISSUE TITLE
A lot of 404 request

### ISSUE THREAD

**Issue by daniyel** [klokantech/tileserver-gl#37]
Hi.

I am running just an example tileserver-gl on my VirtualBox machine and I am trying to zoom in and out, and move the map and I am getting broken maps rendering wise, because a lot of pbf requests are 404. Is there any explanation why is this happening?

Staring server with:
`docker run -it -v $(pwd):/data -p 8080:80 klokantech/tileserver-gl`

And on my host machine I access:
`http://192.168.96.10:8080/`

This is how Bodensee in Swiss and Germany looks like:

![bodensee_swiss](https://cloud.githubusercontent.com/assets/356247/17438147/b1802170-5b21-11e6-966a-ffc56ae81414.png)

Best regards.

**Comment by klokan** [comment]
This is very probably a problem of the MBTiles with vector tiles which you have downloaded from OSM2VectorTiles - no the problem of TileServer-GL project.

Related to:
https://github.com/osm2vectortiles/osm2vectortiles/issues/380

Could you please check if the tiles which are 404 in TileServer-GL are also missing in your downloaded MBTiles?

I expect if you download the dumps again in a couple of days (after above-linked ticket is closed) it will be fixed automatically. Could you please inform us if the problem resolves?

**Comment by klokan** [comment]
Country extracts were reuploaded. Could you please try it with latest downloaded MBTiles @daniyel?

**Comment by daniyel** [comment]
Hi.

I downloaded new Zurich mbtiles it seems to be ok for Zurich, now I wanted to try on Switzerland but when I start docker container I get error:
```

Starting tileserver-gl v0.9.1
Listening at http://:::80/
/usr/src/app/node_modules/sharp/index.js:988
    throw new Error('Unsupported output format ' + formatOut);
    ^

Error: Unsupported output format undefined
    at Sharp.toFormat (/usr/src/app/node_modules/sharp/index.js:988:11)
    at /usr/src/app/src/serve_rendered.js:201:18
    at /usr/src/app/node_modules/mbtiles/lib/mbtiles.js:267:28
    at ensureCenter (/usr/src/app/node_modules/mbtiles/lib/mbtiles.js:335:89)
    at /usr/src/app/node_modules/mbtiles/lib/mbtiles.js:264:17
    at ensureBounds (/usr/src/app/node_modules/mbtiles/lib/mbtiles.js:306:42)
    at /usr/src/app/node_modules/mbtiles/lib/mbtiles.js:262:13
    at /usr/src/app/node_modules/mbtiles/lib/mbtiles.js:277:29
    at Statement.errBack (/usr/src/app/node_modules/mbtiles/node_modules/sqlite3/lib/sqlite3.js:16:21)
```

And in config.json i made changes like:

```
"data": {
    "switzerland-vector": {
      "mbtiles": "switzerland.mbtiles"
    }
  }
```

And the right mbtiles are in the data folder "switzerland.mbtiles" and "switzerland-raster.mbtiles".

Do I need to change something else?

Best regards.

**Comment by klokan** [comment]
You must adjust the JSON files in styles to point to "switzerland-vector".

**Comment by daniyel** [comment]
Ok, thank you. Today I downloaded new switzerland.mbtiles, it looks like I am getting only 200 and 304 which is good I assume but I am still getting this funny rendering somehow:

![meilen_tile](https://cloud.githubusercontent.com/assets/356247/17476259/5c6c7b94-5d5f-11e6-99fd-256becc95f41.jpg)
![rapperswill_tile](https://cloud.githubusercontent.com/assets/356247/17476260/5c6d7bb6-5d5f-11e6-864f-7f3d429ab6d9.jpg)
![swiss_part](https://cloud.githubusercontent.com/assets/356247/17476261/5c6dbc0c-5d5f-11e6-8dba-5bc1804fd41e.jpg)

**Comment by klokan** [comment]
@daniyel the issue in TileServer-GL is https://github.com/klokantech/tileserver-gl/issues/38

**Comment by klokan** [comment]
The problem of 404 tiles does not exist anymore. Closing this issue - thanks for cooperation @daniyel.

The issues with rendering are probably related to V2 spec vector tiles - it continues in #38
