### ISSUE TITLE
OpenLayer vector Tiles are not loading properly.

### ISSUE THREAD

**Issue by AsimAziz** [klokantech/tileserver-gl#372]
Hi,

I'm running tile-server-gl locally with mbtiles tiles generated by "Tippecanoe".

Running tile-server-gl by this command:
    sudo docker run -it -v $(pwd):/data -p 8180:80 klokantech/tileserver-gl

I can preview my mbtile tile layer from data section  in "tile-server" from my localhost.

But when i try to load these vector tiles through openlayer, tile are loading with "Status Code: 204 No Content"  , And also there is warning in  request headers "
Provisional headers are shown".

Any idea ? It may be some stupid error, I'm new .. 

here is my openlayer code to access mbtiles:

       new ol.layer.VectorTile({
          source: new ol.source.VectorTile({
            declutter: true,
            format: new ol.format.MVT(),
            url: 'http://localhost:8180/data/live_line/{z}/{x}/{y}.pbf'
          })
       }),

Thanks.

**Comment by AsimAziz** [comment]
so, each time when we are working with .bmtiles are not in the openmaptile format we have to make a conf file for the style. I'm able to run with creating a conf file and give it as a reference in the run command.

**Comment by 2803media** [comment]
@AsimAziz hello do you have an example for the conf file I'm stuck to style mbtiles from tippecanoe thanks
