### ISSUE TITLE
Support V2 spec tiles

### ISSUE THREAD

**Issue by klokan** [klokantech/tileserver-gl#38]
The OSM2VectorTiles project has upgraded recently to V2 specification of vector tile format - so all the vector tiles downloaded after OSM2VectorTiles milestone v2.2 are in this format.

We should upgrade the "MapBox GL Native" library too as there are reported rendering issues probably related to incompatibility of the old version of the rendering library with the new V2 spec of vector tiles. (to be reproduced first, before committing the upgraded version)

**Comment by klokan** [comment]
Report from @daniyel:

Today I downloaded new switzerland.mbtiles, it looks like I am getting only 200 and 304 which is good I assume but I am still getting this funny rendering somehow:

![meilen_tile](https://cloud.githubusercontent.com/assets/356247/17476259/5c6c7b94-5d5f-11e6-99fd-256becc95f41.jpg)
![rapperswill_tile](https://cloud.githubusercontent.com/assets/356247/17476260/5c6d7bb6-5d5f-11e6-864f-7f3d429ab6d9.jpg)
![swiss_part](https://cloud.githubusercontent.com/assets/356247/17476261/5c6dbc0c-5d5f-11e6-8dba-5bc1804fd41e.jpg)

**Comment by petrsloup** [comment]
I'm having hard time reproducing the issue -- I downloaded latest Switzerland and Zurich extracts, everything seems to be working ok (both raster and vector viewer). I even tried Paraguay (from https://osm2vectortiles-downloads.os.zhdk.cloud.switch.ch/v2.0/extracts/paraguay.mbtiles), which seems to be the newest file on the server (`2016-08-07T14:18:58.000Z`), but no visual errors.

Anyway, I updated the dependencies in a separate branch (`v2_tiles`).

@daniyel Where did you download the file? Are you having problems with the "Vector" or the "Raster" viewer? Can you try running `docker run -it -v $(pwd):/data -p 8080:80 klokantech/tileserver-gl:v2_tiles` to see if it helps?

**Comment by klokan** [comment]
@daniyel we need your feedback.

**Comment by daniyel** [comment]
Sorry for not answering earlier. I have downloaded the tiles from `https://osm2vectortiles-downloads.os.zhdk.cloud.switch.ch/v2.0/extracts/switzerland.mbtiles` and started the docker with `docker run -it -v $(pwd):/data -p 8080:80 klokantech/tileserver-gl:v2_tiles`. It seems the rendering is working now, atleast I could not see any distortions in the map.

Oh. I was using i think vector tiles.

**Comment by MH6** [comment]
I am having a similar issue with vector tile rendering on certain machines using the United States mbtiles extract. On my development machine (Windows 7 with dedicated GPU) it renders fine, but on one of my other machines (Windows 10, no dedicated GPU) it has similar artifacts to what klokan posted. I was using Chrome with both.

**Comment by MH6** [comment]
Was having the same issue, v2_tiles version of the docker image resolved it.

**Comment by petrsloup** [comment]
This is now part of the master branch.
