### ISSUE TITLE
Auth and Referer Header check

### ISSUE THREAD

**Issue by daniyel** [klokantech/tileserver-gl#41]
Hi.

Is there a way to set some basic auth or referer check on server side, so the server would prove referer before the tiles would be delievered. I have used before `https://github.com/klokantech/tileserver-mapnik`, but I had to checkout the whole project and then customize the `server.js`. 

Need: we want to set our server live and we do not want everyone to be able to render maps from our server.

If there is nothing like this at the moment, would it be hard to set some kind of config, or throught Dockerfile somehow, that would enable somekind of authentication?

Best regards.

**Comment by klokan** [comment]
Typically - you should use nginx/lighttpd/apache on the frontend - and the node.js application server is hidden behind it in production deployment.
Nginx can be used to add protection via https, password, referrer, IP address restriction, access keys, etc.

We offer commercial support and consulting on production deployment of the software. Contact info@klokantech.com.

Action on this ticket:
- A short paragraph in the manual to cover a similar question/request directly in the documentation of this project.

**Comment by petrsloup** [comment]
See http://tileserver.readthedocs.io/
