### ISSUE TITLE
Tileserver accepting random GET requests

### ISSUE THREAD

**Issue by MH6** [klokantech/tileserver-gl#44]
I was doing some tests with tileserver-gl and noticed some strange GET requests. Currently the server is public facing for testing purposes though not actually being used anywhere. The final setup will involve having another public server reroute tile requests to the tile server on the LAN.

The request in question:
`GET http://<random Chinese website here>.com/ 200 113.811 ms - 4686`

Is this normal behavior?  Shouldn't it reject this request outright as not valid, since it isn't actually requesting a tile? Is there a way to auto-reject such requests, or is this something I will just need to handle on a proper server and keep the tile server private?

My concern is this could be used in some malicious fashion, but my security expertise is lacking. I'm not sure if that line means the tileserver is going out and grabbing that website or if it is just ignoring it and sending back a 200 OK message. Maybe it is completely benign and I'm just being paranoid--can anyone ease my mind a bit?

**Comment by klokan** [comment]
Tileserver-GL is listening on HTTP port you specify and responds there to all incoming requests.
You should use it behind a reverse proxy such as nginx - in a production deployment.

If you want to filter incoming requests to your own IP address CNAME DNS records or filter any other malicious requests - then configure the nginx sitting in front of the tileserver-gl to refuse such requests or create filters for only valid requests for your application.

IMHO It is not job of the tileserver-gl to handle this.

**Comment by MH6** [comment]
I will look into using nginx as a front end. Thank you for the prompt reply, and great work.
