### ISSUE TITLE
Error while npm installing (node v4.5, npm 3.10.6)

### ISSUE THREAD

**Issue by rastapasta** [klokantech/tileserver-gl#47]
Hey hey and thanks for this wonderful project. While trying to install the npm module, i constantly run into following error:

```
/Users/imac24/.nvm/versions/node/v4.5.0/lib
└── (empty)

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/imac24/.nvm/versions/node/v4.5.0/bin/node" "/Users/imac24/.nvm/versions/node/v4.5.0/bin/npm" "install" "-g" "tileserver-gl"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.6
npm ERR! path /Users/imac24/.nvm/versions/node/v4.5.0/lib/node_modules/.staging/abbrev-bebc58f6
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/Users/imac24/.nvm/versions/node/v4.5.0/lib/node_modules/.staging/abbrev-bebc58f6' -> '/Users/imac24/.nvm/versions/node/v4.5.0/lib/node_modules/tileserver-gl/node_modules/abbrev'
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/imac24/.nvm/versions/node/v4.5.0/lib/node_modules/.staging/abbrev-bebc58f6' -> '/Users/imac24/.nvm/versions/node/v4.5.0/lib/node_modules/tileserver-gl/node_modules/abbrev'
```

Neither can i find any dependency to abbrev in the dep tree, nor does it make issues when i install it separately.
So I'm asking you if you might know this behavior and a possible fix. Cheers and thanks in advance!

**Comment by rastapasta** [comment]
Figured out what's up: canvas failed to install (only pointing to abbrev).
Fixed by taking care of following requirements on OSX: 

`brew install pkg-config cairo`

And all is good 😄

**Comment by klokan** [comment]
In all cases - the easiest way how to install and use the project is via `docker` - especially on a Mac where may be issues with X11 anyway and docker is now supported very well.

NPM has binary dependencies. If you don't need raster rendering you can try `npm install tileserver-gl-light` which is pure JavaScript without binary deps.

Otherwise, you have to solve the dependencies and install missing binary libraries on your computer.

**Comment by rastapasta** [comment]
@klokan thank you very much for your kind reply and advice!!

am consciously running without docker and with rendering support, just didn't think of additional binary libraries - thanks again! ❤️
