### ISSUE TITLE
Running Docker on ARM

### ISSUE THREAD

**Issue by RedFiveAZ** [klokantech/tileserver-gl#49]
Hi guys,

I tried installing via docker, but discovered this error:

docker run -it -v $(pwd):/data -p 8080:80 klokantech/tileserver-gl
exec format error
Error response from daemon: Cannot start container 571b11b20b93fcee093edeab3704485d98e567fb1d23133039d53187682c68e5: [8] System error: exec format error

I believe this occurs because tileserver hasn't been packaged for ARM processors. Having a lot of issues installing via npm, so it'd be awesome if you could package it for the RaspberryPi!

Thanks for making something so awesome!

**Comment by RedFiveAZ** [comment]
As a followup, when I try to install via npm I get this:

`npm ERR! Linux 4.4.13-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--unsafe-perm" "-g" "tileserver-gl"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! path /usr/lib/node_modules/.staging/abbrev-4786dede
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/.staging/abbrev-4786dede' -> '/usr/lib/node_modules/tileserver-gl/node_modules    /abbrev'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/.staging/abbrev-4786dede' -> '/usr/lib/node_modules/tileserver-gl/node_modules    /abbrev'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sysop/vectortiles/npm-debug.log
npm ERR! code 1
`

**Comment by petrsloup** [comment]
Running full version of tileserver-gl on ARM is not supported at the moment.

It requires native dependencies, which are not easy to compile on ARM. So, AFAIK, it's not possible to create the compatible docker image either.

But! You should be able to run the `tileserver-gl-light` which has no native dependencies (see http://tileserver.readthedocs.io/en/latest/installation.html#tileserver-gl-light-on-npm).

**Comment by RedFiveAZ** [comment]
I am looking to use the vector rasterization process, so tileserver-gl-light would not be appropriate for that. Any other suggestions?

**Comment by klokan** [comment]
@RedFiveAZ If you need the rasterization, then you must install the full version with all dependencies - so the light version will not help you.
You have to take one binary library after another from npm - and ensure every single one does compile correctly on ARM platform and can be properly installed. As this project is 100% open-source it is technically possible - but you must put a non-trivial effort into the task.

First step is direct native installation with npm. Docker container specific for ARM platform could be created from npm trivially, once direct installation runs.

@klokantech team is not going to work on this unless there is a client who requires this explicitly. Feel free to jump on this task - and provide a pull request. We would be glad to review.

**Comment by strech345** [comment]
I've also the same error, running on osgeo (ubuntu) and also with --unsafe-perm flag = true

npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "tileserver-gl"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! path /usr/lib/node_modules/.staging/abbrev-4786dede
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/.staging/abbrev-4786dede' -> '/usr/lib/node_modules/tileserver-gl/node_modules/abbrev'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/.staging/abbrev-4786dede' -> '/usr/lib/node_modules/tileserver-gl/node_modules/abbrev'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
npm ERR! code 1

**Comment by jakehewitt** [comment]
If anyone wants to figure this out on their own, we're offering a $1,000 bounty for it.

**Comment by gimse** [comment]
> If anyone wants to figure this out on their own, we're offering a $1,000 bounty for it.
> 
> Edit: Solved.
@jakehewitt Can you tell how you soled it?

**Comment by musamak** [comment]
Until we get the official ARM release for "tileserver-gl" on the docker

I have tested the following workaround on Raspbian (arm64) and it is working fine.

sudo docker run --privileged --rm tonistiigi/binfmt --install amd64

sudo docker run --rm -it -v $(pwd):/data -p 8080:80 --platform linux/amd64 maptiler/tileserver-gl

PS: I know it is not an optimal solution.

**Comment by acalcutt** [comment]
I have been working on trying to get arm support in my maplibre-native fork and made a test tileserver-gl arm64 with it includes it. would anyone here be willing to test?

wifidb/tileserver-gl:v5.0.4
https://hub.docker.com/r/wifidb/tileserver-gl/tags

I am trying to get my changes upstream to maplibre so the can be used here, but that is still a work in progress.
 https://github.com/maplibre/maplibre-gl-native/pull/535
https://github.com/maplibre/maplibre-gl-native/pull/520

**Comment by luandro** [comment]
Works on arm64 @acalcutt!

**Comment by acalcutt** [comment]
In theory, arm64 support should now be included in maptiler/tileserver-gl:v4.3.2 . Can anyone still interested in this give it a test.

**Comment by luandro** [comment]
Working well on arm64 for new releases.
