### ISSUE TITLE
URL error in style files when using tileserver behind a reverseproxy

### ISSUE THREAD

**Issue by SToto98** [klokantech/tileserver-gl#50]
Hi there :)
I try to use tileserver behind a reverse proxy (actually it is tileserver-gl-light but I think this is the same code).
On my server I start tileserver on http://127.0.0.1:8080 and then I use Apache as a reverse proxy to call tileserver  from https://map.domain.tld. So far so good, HTTP calls are working, but when the style file is called (https://map.domain.tld/styles/bright-v9.json), then, inside I get something like this :
`glyphs:"http://localhost:8080/fonts/{fontstack}/{range}.pbf"
layers:[{id: "background", type: "background", paint: {background-color: "#f8f4f0"}, interactive: true},…]
metadata:{mapbox:autocomposite: true, mapbox:type: "template",…}
name:"Bright"
sources:{mapbox: {url: "http://localhost:8080/data/osm2vectortiles.json", type: "vector"}}
sprite:"http://localhost:8080/styles/bright-v9/sprite"
version:8`
As you see all urls are http://localhost:8080 ...
The problem came from /src/serve_style.js line 60 when you replace urls in the style file :
`return url.replace('local://', req.protocol + '://' + req.headers.host + '/') + query;`
Obviously req.protocol and req.headers.host are not the good ones. Is it possible to add somewhere in the config file the good url to use or to use an absolute URL without protocol and domain instead ?

Thanks a lot for this awesome project which I plans to use hugely !

**Comment by SToto98** [comment]
And I see you are using req.protocol and req.headers.host in other places of your code. I might have the same issue there too...

**Comment by petrsloup** [comment]
See https://expressjs.com/en/guide/behind-proxies.html

If you set `X-Forwarded-Host`, `X-Forwarded-Proto` headers (when proxying requests from the Apache) the tileserver-gl will use these automatically.

**Comment by SToto98** [comment]
Ok, thank you for your quick response ! Maybe you can add this to the doc http://tileserver.readthedocs.io/en/latest/deployment.html ?

**Comment by klokan** [comment]
Could you please make a pull request with related paragraph? Thank you!

**Comment by jeanbaptistevilain** [comment]
Hi,
Thanks for the great work on tileserver-gl. For people using Apache to reverse proxy the server, here is what worked for me :

`ProxyPreserveHost On
ProxyPass / http://localhost:8080/
ProxyPassReverse / http://localhost:8080/`

It took me some time to realize that the ProxyPreserveHost was required (as well as X-Forwarded-* headers, which are set by the ProxyPass directive), so I thought I would add it here in case it helps anyone.
