### ISSUE TITLE
can not start container on 32b architecture

### ISSUE THREAD

**Issue by seb4no** [klokantech/tileserver-gl#53]
when trying to run the docker image I got the here below message ;

docker: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: exec format error".

Does this image work with 32b CPU ?
My host is  4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:41:41 UTC 2016 i686 i686 i686 GNU/Linux
Ubutun 16.04 LTS

**Comment by klokan** [comment]
The binary container pushed to DockerHub is build for 64bit Linux systems automatically. Practically all hardware produced within the last 10? years supports 64bit mode - time to upgrade (your Linux kernel) ;-).

If you really need 32bit - you can do that on your own. This is an open-source project. You should be able to build your own 32bit docker container by adjusting our Dockerfile - or make native installation with npm on your 32bit hardware.

We do not intend to put extra effort in 32bit linux, unless we have a client who requires this.
Feel free to make a fork of TileServer GL project, play with the code and link it here with comments for what you have done. We would be glad to review and accept a Pull Request.
