### ISSUE TITLE
Rendering issues

### ISSUE THREAD

**Issue by slongberry** [klokantech/tileserver-gl#54]
I have followed the instructions for running tileserver-gl from a Docker container. When I connect to port 80, I can see the the page listing the styles just fine. I am trying to server the united_states_of_america.mbtiles downloaded from OSM2VectorTiles. I have tried an older version of this file and a fresh download as well.

If I click on the link to view the vector tiles, everything works fine:

![screen shot 2016-09-29 at 10 23 42 am](https://cloud.githubusercontent.com/assets/12254683/18964557/9c93404a-8636-11e6-89b6-fe69a89d6e2f.png)

However, when I click on the link for raster tiles, I get random tiles from South America:

![screen shot 2016-09-29 at 10 07 12 am](https://cloud.githubusercontent.com/assets/12254683/18964605/db4506fc-8636-11e6-8fbb-6ed67aedb6bf.png)

I have also tried downloading a city file and see the same results. 

Pointing QGIS at the WMTS gives a different sampling of tiles from South America:

![screen shot 2016-09-29 at 10 22 59 am](https://cloud.githubusercontent.com/assets/12254683/18964652/0be165e4-8637-11e6-9877-f7129df969e8.png)

Any ideas of what is going wrong here? I would be happy to provide more information if needed.

**Comment by petrsloup** [comment]
Fixed in v1.1.3

**Comment by KoAi** [comment]
Thanks, it works
