### ISSUE TITLE
Serve from non root url location

### ISSUE THREAD

**Issue by rustyb** [klokantech/tileserver-gl#56]
Hi! Great server guys, really nice work. Just wondering if you might have any advice on running the server from a non root url?

For instance running the app behind nginx at domain.com/tiles/.

I've been toying with adding a baseURL parameter to the config file, but figured there must be a quicker way?

**Comment by petrsloup** [comment]
@rustyb Hi, it should be easily possible to configure nginx to rewrite the URLs you need to the local root-based URLs of the tileserver.

This seems to me like a better solution than modifying tileserver-gl itself.

**Comment by rustyb** [comment]
Thanks @petrsloup ! Probably not the best place to log this but if anyone is interested in how to do the same thing here was the nginx config I settled on in the end.

The easy part was getting tiles served and getting the server to show the homepage at /tiles

```
location /tiles/ {
    proxy_pass http://127.0.0.1:8071/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host/tiles;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
}
```

For serving up the static content referenced in the templates.
```
location ~ ^/(images/|fonts/|index.css|mapbox-gl.css|mapbox-gl.js) {
          root path/to/tileserver-gl/public/resources;
          access_log off;
          expires 30d;
        }
```

This next part baffled me for a while, so maybe this is not the most optimum way to do it but this second block was needed so that you could see the x-ray viewer and to render the tilejson.

```
location /data/ {
        proxy_pass http://127.0.0.1:8071;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Forwarded-Proto $scheme;
}
```

**Comment by Lewik** [comment]
Will tileserver always generate images url without "tiles" addition?

**Comment by tibbben** [comment]
I modified your second location to a redirect and it worked without the third location. My final config looked like this: 

```
        location /vectortiles/ {
          proxy_pass http://so.me.ip:port/;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection 'upgrade';
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-Server $host/vectortiles;
          proxy_set_header X-Forwarded-For $remote_addr;
          proxy_set_header Host $http_host/vectortiles;
          proxy_set_header X-Forwarded-Host $host/vectortiles;
          proxy_set_header X-Forwarded-Proto https;
        }

        location ~ ^/(?<res>images/.*|data/.*|fonts/.*|index.css|maplibre-gl.*) {
          return 301 /vectortiles/$res;
        }
```
