### ISSUE TITLE
Raster source can't serve retina

### ISSUE THREAD

**Issue by klokan** [klokantech/tileserver-gl#57]
When TileServer GL is hosting raster MBTiles - these are available only on one resolution (only standard scale and no retina for example).
Stil - the xray view requests retina tiles from this dataset (which are then 404).

For example:
http://klokantech.tilehosting.com/data/hillshades/?key=tXme5cuqgrCqdPoZHqyn#4/28.57/28.65
on a retina display (can be tried on a Chromebook too).

Not sure if the viewer reacts to availability of the `scale` in metadata or on something else.

Also - on TileServerPHP we supports serving of two different MBTiles file - one with "@2x" suffix in the basename of filename and another without:
https://tileserver.maptiler.com/grandcanyon.json
https://tileserver.maptiler.com/grandcanyon@2x.json

**Comment by petrsloup** [comment]
The mapbox.js viewer always assumes both regular and retina tiles are available.

I added a few lines to the viewer initialization so the regular and retina tiles use the same URL.
