### ISSUE TITLE
Vertical lines on planet.mbtiles and missing translations

### ISSUE THREAD

**Issue by daniyel** [klokantech/tileserver-gl#59]
Hi.

I do not know if this relates to tileserver-gl or mbtiles from osm2vectortiles, but we have noticed some vertical lines on the water areas.

![Weird lines](http://img5.fotos-hochladen.net/uploads/weirdlinesz4ov3qhwxf.png)

Another thing I have noticed (we are using German names) that **Adriatic see** is not translated (should be **Adriatisches Meer**) and possibly falls back to English version. How can I edit names or what is the right procedure for doing that?

![Non German names](http://img5.fotos-hochladen.net/uploads/nongermanname5239uxwp8o.png)

Best regards.

**Comment by klokan** [comment]
Thanks for the report @daniyel.

Both these issues are related to the vector tiles from OSM2VectorTile project.
The problems are not related to the tileserver-gl software in this repository.

Please report one problem per one ticket - in the OSM2VectorTiles repo - and before submitting a new ticket be sure similar tickets does not exist yet. Remember OSM2VectorTiles is a community project - you can always fix yourself the problem you have... or hire somebody to do that for you.

https://github.com/osm2vectortiles/osm2vectortiles/issues/431
https://github.com/osm2vectortiles/osm2vectortiles/issues/300
