### ISSUE TITLE
Problem installing tileserver-gl

### ISSUE THREAD

**Issue by joaokho** [klokantech/tileserver-gl#61]
Error message like this:
38548 error Linux 3.19.0-71-generic
38549 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "tileserver-gl"
38550 error node v6.8.1
38551 error npm  v3.10.8
38552 error path /home/joaokho/.npm-global/lib/node_modules/.staging/abbrev-708f0d9d
38553 error code ENOENT
38554 error errno -2
38555 error syscall rename
38556 error enoent ENOENT: no such file or directory, rename '/home/joaokho/.npm-global/lib/node_modules/.staging/abbrev-708f0d9d' -> '/home/joaokho/.npm-global/lib/node_modules/tileserver-gl/node_modules/a$
38557 error enoent ENOENT: no such file or directory, rename '/home/joaokho/.npm-global/lib/node_modules/.staging/abbrev-708f0d9d' -> '/home/joaokho/.npm-global/lib/node_modules/tileserver-gl/node_modules/a$
38557 error enoent This is most likely not a problem with npm itself
38557 error enoent and is related to npm not being able to find a file.
38558 verbose exit [ -2, true ]

**Comment by klokan** [comment]
Please see #47 #53 #49 and react.

**Comment by klokan** [comment]
Esp. my answer:

> The easiest way how to install and use the project is via `docker` - especially on a Mac where may be issues with X11 anyway and docker is now supported very well. See: http://www.docker.com/

> Full TileServer GL has binary dependencies. If you don't need raster rendering you can try `npm install tileserver-gl-light` which is pure JavaScript without binary deps and runs really everywhere.

> Otherwise, you have to ensure all the required binary libraries are present on your computer.

**Comment by joaokho** [comment]
Thanks @klokan, I already testing tileserver-gl-light, so now want to test tileserver-gl that can use base map (topo map) and overlay with vector tile, that look very good, such as: OSM Liberty (https://github.com/lukasmartinelli/osm-liberty) :-)

**Comment by joaokho** [comment]
@klokan, I try using docker is run successfully, but i confuse to configure how to using another mbtiles that always run zurich_switzerland.mbtiles defaultly

**Comment by joaokho** [comment]
Hi, I already made docker commit on container to change mbtiles files on run.sh. 

Thank you :+1:

**Comment by klokan** [comment]
@joaokho you should not need to change run.sh at all.
If you need to serve
- a single .mbtiles file then just copy it to the /data directory exposed to Docker.
- multiple .mbtiles files you can create a config.json and place it in the /data directory

See:
https://tileserver.readthedocs.io/en/latest/usage.html
https://tileserver.readthedocs.io/en/latest/config.html

**Comment by huangyingjie** [comment]
````js
 npm i -g tileserver-gl-light
````
Also report error as bellow sometimes:

````js
no such file or directory, rename 'xxx/node_modules/.staging/minimist-5fa6bcbe' -> 'sqlite3/node_modules/node-pre-gyp/node_modules/mkdirp/node_modules/minimist'
````
versions
````js
npm: 3.10.9
node: 4.6
os: mac osx ei 10.11.6
````

**Comment by klokan** [comment]
Try `npm cache clean`.
Use docker or learn how to use npm.

**Comment by twisig** [comment]
Same issue in my side. The installation doesn't work with MacOs

**Comment by twisig** [comment]
tileserver-gl zurich_switzerland.mbtiles
Starting tileserver-gl v1.1.5
Automatically creating config file for zurich_switzerland.mbtiles
Run with --verbose to see the config file here.
module.js:474
    throw err;
    ^

Error: Cannot find module '../../lib/mapbox-gl-native.node'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/tileserver-gl/node_modules/mapbox-gl-native/platform/node/index.js:5:12)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/tileserver-gl/src/serve_rendered.js:19:12)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)

**Comment by huangyingjie** [comment]
@twisig  you'd better use docker instead.

**Comment by twisig** [comment]
The problem comes from mapbox gl native library. Dockers is the best option to test the server. 
I would like to customize the code but I don't know how to modify the files in Dockers.

**Comment by klokan** [comment]
Duplicate to #70 or #76

**Comment by twisig** [comment]
Where is the solution??
There is no fix in your comment. 
Why do you close this issue?
Please reopen this issue thank you!!
