### ISSUE TITLE
tileserver-gl-light command not found...

### ISSUE THREAD

**Issue by fake-fur** [klokantech/tileserver-gl#65]
hi and thanks for the work

i managed to finally get this to install via npm (what a clusterf*** of a mission) but now typing "tileserver-gl-light berlin-blahblah.mbtiles" says simply "command not found"

i have no idea how to make this thing actually run

any pointers or clues?

thanks
:)

**Comment by klokan** [comment]
Unfortunately, your issue report does not tell any technical details at all - such as what operating system do you use, commands you run, etc.
It looks like there is something wrong with installation of npm / node on your computer.

In general - If you are testing the software on your laptop - use "Kitematic" (graphical user interface to docker) - learn how docker run and forget npm, if you don't want to develop and only deploy. See #61 for more details.

**Comment by fake-fur** [comment]
fixed - sorry

**Comment by fake-fur** [comment]
hi and thanks for getting back to me

sorry for the lack of reqd info - i'm kinda new to this so i don't always know what all the pieces are or how they fit together

just this morning i found the magical incantations to get the tileserver installed and running on a debian box - apparently the nodejs sqlite3 thingy won't compile on a raspbery pi (which i was going to use for a test setup) - on x64 debian no problems

i also wrote a quick python script to merge multiple mbtiles files into a single file so the server can serve them all properly - it doesn't seem to like multi-files

just figuring out the styling on the maps now

thanks again for the great work on the server and getting back to me

ps i don't like docker - too many levels of abstraction just to make it so i don't have to figure things out properly
:)

**Comment by derak29** [comment]
Hi All. How i can fix it on ubuntu 14?


npm WARN package.json node@0.0.0 No repository field.
npm http GET https://registry.npmjs.org/node
npm http 304 https://registry.npmjs.org/node
npm WARN deprecated node@0.0.0: To update or install node, go to http://nodejs.org/
node@0.0.0 node_modules/node
root@server84:~# npm install -g tileserver-gl
npm http GET https://registry.npmjs.org/tileserver-gl
npm http 304 https://registry.npmjs.org/tileserver-gl
npm WARN engine tileserver-gl@1.5.0: wanted: {"node":">=4.2.1 <5"} (current: {"node":"v0.10.25","npm":"1.3.10"})
npm http GET https://registry.npmjs.org/async/2.2.0
npm http GET https://registry.npmjs.org/advanced-pool/0.3.2
npm http GET https://registry.npmjs.org/canvas/1.6.5
npm http GET https://registry.npmjs.org/base64url/2.0.0
npm http GET https://registry.npmjs.org/clone/2.1.1
npm http GET https://registry.npmjs.org/color/1.0.3
npm http GET https://registry.npmjs.org/cors/2.8.2
npm http GET https://registry.npmjs.org/express/4.15.2
npm http GET https://registry.npmjs.org/mapbox/mapbox-gl-native/3.4.4
npm http GET https://registry.npmjs.org/mapbox/sphericalmercator/1.0.5
npm http GET https://registry.npmjs.org/glyph-pbf-composite/0.0.2
npm http GET https://registry.npmjs.org/handlebars/4.0.6
npm http GET https://registry.npmjs.org/mbtiles/0.9.0
npm http GET https://registry.npmjs.org/morgan/1.8.1
npm http GET https://registry.npmjs.org/node-pngquant-native/1.0.4
npm http GET https://registry.npmjs.org/nomnom/1.8.1
npm http GET https://registry.npmjs.org/pbf/3.0.5
npm http GET https://registry.npmjs.org/proj4/2.4.3
npm http GET https://registry.npmjs.org/request/2.81.0
npm http GET https://registry.npmjs.org/sharp/0.17.2
npm http GET https://registry.npmjs.org/tileserver-gl-styles/1.1.1
npm http GET https://registry.npmjs.org/vector-tile/1.3.0
npm http 304 https://registry.npmjs.org/async/2.2.0
npm http 304 https://registry.npmjs.org/advanced-pool/0.3.2
npm http 304 https://registry.npmjs.org/base64url/2.0.0
npm http 304 https://registry.npmjs.org/canvas/1.6.5
npm http 304 https://registry.npmjs.org/express/4.15.2
npm http 304 https://registry.npmjs.org/clone/2.1.1
npm http 304 https://registry.npmjs.org/color/1.0.3
npm http 304 https://registry.npmjs.org/cors/2.8.2
npm http 404 https://registry.npmjs.org/mapbox/sphericalmercator/1.0.5
npm http 304 https://registry.npmjs.org/glyph-pbf-composite/0.0.2
npm http 404 https://registry.npmjs.org/mapbox/mapbox-gl-native/3.4.4
npm ERR! 404 'mapbox' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.13.0-24-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "tileserver-gl"
npm ERR! cwd /root
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! code E404
npm http 304 https://registry.npmjs.org/mbtiles/0.9.0
npm http 304 https://registry.npmjs.org/handlebars/4.0.6
npm http 304 https://registry.npmjs.org/morgan/1.8.1
npm http 304 https://registry.npmjs.org/node-pngquant-native/1.0.4
npm http 304 https://registry.npmjs.org/request/2.81.0
npm http 304 https://registry.npmjs.org/nomnom/1.8.1
npm http 304 https://registry.npmjs.org/pbf/3.0.5
npm http 304 https://registry.npmjs.org/proj4/2.4.3
npm http 304 https://registry.npmjs.org/sharp/0.17.2
npm http 304 https://registry.npmjs.org/tileserver-gl-styles/1.1.1
npm http 304 https://registry.npmjs.org/vector-tile/1.3.0
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0

**Comment by petrsloup** [comment]
@derak29 
```
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
```
Install newer node (v4) and newer npm
