### ISSUE TITLE
Use in OpenLayers viewer (URL syntax and type)

### ISSUE THREAD

**Issue by Roozaay** [klokantech/tileserver-gl#66]
Hi,

I'm running a tileserver-gl-light server with a complete france pbf perfectly, thanks for that !

Now I would like to display my vector tiles in my application that runs openlayers.
I tried `"href" : "http://serveradress/styles/bright-v9/?vector#{z}/{x}/{y}.pbf"` for the URL and `"type" : "application/x-protobuf"` for the type but it doesn't work...

Any idea ? It may be a stupid error, I'm a bit new in this... thx

**Comment by klokan** [comment]
Here is a sample source code for displaying vector tiles in OpenLayers V3 natively:
https://openlayers.org/en/latest/examples/mapbox-vector-tiles.html?q=vector+tiles
and the same runs with our own CDN and vector tiles - so it should run with your tileserver-gl-light instance too:
http://osm2vectortiles.tileserver.com/#v2/ol3vector.code
http://osm2vectortiles.tileserver.com/#v2/ol3vector.embed

**Comment by klokan** [comment]
Please close this ticket if problem is solved.

**Comment by lukaszbel** [comment]
I have the same problem. I tried in OL4.0 this code to your demo server:

`var tilegrid = ol.tilegrid.createXYZ({tileSize: 512, maxZoom: 22});

var layer1 = new ol.layer.VectorTile({
  source: new ol.source.VectorTile({
    format: new ol.format.MVT(),
    tileGrid: tilegrid,
    tilePixelRatio: 8,
    url: 'http://demo.tileserver.org/styles/positron/rendered/{z}/{x}/{y}.pbf''
  }),

});

var osm =  new ol.layer.Tile({
            source: new ol.source.OSM()
          })
var view = new ol.View({
  center: [732602.1417165294, 5864590.06411005],
  resolution: 2445,
  maxResolution: 90000
});

var map = new ol.Map({
  target: 'map',
  layers: [layer1
  ],
  view: view
});`

but it doesn't work. I don't try on my own server yet. What address should be to show vector layers on OL? On http://demo.tileserver.org/ is only the XYZ link to png raster tiles version.

**Comment by klokan** [comment]
Please see:
https://openmaptiles.org/viewers/
and
https://openmaptiles.org/docs/website/openlayers3/ for complete source code of example of displaying the vector tiles from TileServer GL in OpenLayers

**Comment by lukaszbel** [comment]
Thank you for answer. I saw that and if i copy and paste the code from https://openmaptiles.org/docs/website/openlayers3/ everythink works perfect but when I change the url from : 'https://free-0.tilehosting.com/data/v3/{z}/{x}/{y}.pbf?key=tXiQqN3lIgskyDErJCeY' to 
"http://demo.tileserver.org/styles/positron/rendered/{z}/{x}/{y}.pbf'' it doesn't.

**Comment by klokan** [comment]
demo.tileserver.org server restricts access to the tiles - and we may shut it down...

Load the vector tiles from free.tilehosting.com with your own key (get it at https://openmaptiles.com/hosting/) or install own TileServerGL instance on your server.

**Comment by lukaszbel** [comment]
Ok, i found my mistake. I got wrong address. It should be Http://myserver.com/data/v3/{z}/{x}/{y}.pbf not Http://myserver.com/styles/positron/rendered/{z}/{x}/{y}.pbf now it's working perfect. Thanks!

**Comment by lukaszbel** [comment]
klokan I have one more question. How to set better resolutions for OpenLayers? Even on your page https://openmaptiles.org/viewers/  if I switch the view from MB GL JS to OpenLayers to OpenLayers when the resolution is on the level of buildings and street on OL the quality is much worse and image is 
blurred.

**Comment by klokan** [comment]
@lukaszbel - this is a closed ticket, and support request. NO FURTHER DISCUSSION HERE PLEASE!

OpenLayers does not have yet all the functionality required - such as over zoomed redraw of vector tiles for example or collision on captions.
