### ISSUE TITLE
Error thrown during the install. No such file or directory rename.

### ISSUE THREAD

**Issue by dagonar** [klokantech/tileserver-gl#67]
What an amazing project and solves some of the problems we have. Still having trouble installing for usage with Leaflet.

I have cairo dependencies installed on the server. Seems to be due to a file missing. Is there a way to resolve this?

Using npm 3.10.3 and Node 6.7.

[npm-debug.log](http://pastebin.com/kUHuF3Fb)

**Comment by klokan** [comment]
Try Node v4 or Docker.

From manual:
http://tileserver.readthedocs.io/en/latest/installation.html
> Make sure you have Node v4 or higher (`nvm install 4`) and run

**Comment by klokan** [comment]
Duplicate to #68 or #76
