### ISSUE TITLE
Error when installing (s3 file not available)

### ISSUE THREAD

**Issue by luisra51** [klokantech/tileserver-gl#70]
Hi, 
- I'm installing tile server-gl from the code but I have problems with the file:
`403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/mapbox-gl-native/v3.3.3/node-v48-linux-x64.tar.gz`
-Not available for download. regards

- I modify the code to download the version:
https://mapbox-node-binary.s3.amazonaws.com/mapbox-gl-native/v3.3.3/node-v46-linux-x64.tar.gz
- but when I start the server says
`Error: Module version mismatch. Expected 48, got 46.`

Thanks for any help

**Comment by klokan** [comment]
You may need to use the compatible version of `node`, or our prepared docker container.

Otherwise, you can compile the mapbox-gl-native node module from source code and create the binary yourself.
