### ISSUE TITLE
Gitter Option

### ISSUE THREAD

**Issue by twisig** [klokantech/tileserver-gl#72]
Hi,
May be to help more the developers community, create a room in Gitter.
What do you think ?

**Comment by klokan** [comment]
We offer commercial support and assistance with production deployment of our open-source software. Contact info@klokantech.com if you are interested in getting support directly from the developers.

Public demo of the production version of TileServerGL is at https://maps.klokantech.com/

**Comment by twisig** [comment]
Thank you for your comment but your solution is open source right? So we need to found a solution to fix some issues in the installation.
Julien

**Comment by klokan** [comment]
https://gitter.im/tileserver-gl/Lobby
