### ISSUE TITLE
Rendering 3d 

### ISSUE THREAD

**Issue by twisig** [klokantech/tileserver-gl#74]
Hi
Is it possible to render 3d tiles with this solution?
Thx

**Comment by klokan** [comment]
Tiles are typically created by other software tools - they can contain any (even 3D) information the creator decides to put in.

Mapbox GL native supports tilted view and 3d buildings - which could be probably rendered by TileServer GL into map tiles in future.

Right now, this has a low priority for @klokantech, unless a client request this feature.
