### ISSUE TITLE
How to render a point?

### ISSUE THREAD

**Issue by twisig** [klokantech/tileserver-gl#75]
Hi
Do you have an example how to draw a marker or a symbol in config.json file?
Thx

**Comment by klokan** [comment]
The config.json links source of the data (vector tiles), which can contain a point information (with assigned geo-coordinates). This can be styled with a GL JSON style - so marker has a symbol of your choice in the final map.

This is typically done for thousands or millions of points. If you want to draw a single marker use Leaflet API, OpenLayers API or another API of the viewer you are using.

Please study the documentation at http://osm2vectortiles.org/ and on MapBox websites - or seek support to understand concepts related to vector tiles.
