### ISSUE TITLE
Errors when installing tileserver-gl on Windows 8.1

### ISSUE THREAD

**Issue by scpeterson** [klokantech/tileserver-gl#76]
I am running Windows 8.1 64 bit with Node 4.6.0 and npm 3.10.8.  I ran the folllowing:

- npm cache clean
- npm i -g tileserver-gl

And I get several errors:

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\My_user\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-pre-gyp"
npm ERR! node v4.6.0
npm ERR! npm  v3.10.8
npm ERR! path C:\Users\My_user\AppData\Roaming\npm\node_modules\.staging\mapbox-gl-native-9a3259eb
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall rmdir

npm ERR! EBUSY: resource busy or locked, rmdir 'C:\Users\My_user\AppData\Roaming\npm\node_modules\.staging\mapbox-gl-native-9a3259eb'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\My_user\AppData\Roaming\npm\node_modules\.staging\mapbox-gl-native-9a3259eb\npm-debug.log
C:\Users\My_user\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\My_user\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "tileserver-gl"
npm ERR! node v4.6.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! mapbox-gl-native@3.3.3 preinstall: `npm install node-pre-gyp`
npm ERR! Exit status 4294963214
npm ERR!
npm ERR! Failed at the mapbox-gl-native@3.3.3 preinstall script 'npm install node-pre-gyp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mapbox-gl-native package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install node-pre-gyp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mapbox-gl-native
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mapbox-gl-native
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\My_user\npm-debug.log
npm ERR! code 1

C:\Users\My_user>npm i -g tileserver-gl > ts-gl_errors.txt
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\My_user\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-pre-gyp"
npm ERR! node v4.6.0
npm ERR! npm  v3.10.8
npm ERR! path C:\Users\My_user\AppData\Roaming\npm\node_modules\.staging\mapbox-gl-native-9a3259eb
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall rmdir

npm ERR! EBUSY: resource busy or locked, rmdir 'C:\Users\My_user\AppData\Roaming\npm\node_modules\.staging\mapbox-gl-na
tive-9a3259eb'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\My_user\AppData\Roaming\npm\node_modules\.staging\mapbox-gl-native-9a3259eb\npm-debug.log
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\My_user\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "tileserver-gl"
npm ERR! node v4.6.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! mapbox-gl-native@3.3.3 preinstall: `npm install node-pre-gyp`
npm ERR! Exit status 4294963214
npm ERR!
npm ERR! Failed at the mapbox-gl-native@3.3.3 preinstall script 'npm install node-pre-gyp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mapbox-gl-native package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install node-pre-gyp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mapbox-gl-native
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mapbox-gl-native
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\My_user\npm-debug.log
npm ERR! code 1

If I run npm install -g node-pre-gyp or npm install node-pre-gyp seperately, I do not get any errors.  If I run npm install -g mapbox-gl-native@3.3.3, then I get the same node-pre-gyp related errors as above.

What should I do?  We do not have a Docker license, so I don't think that's the answer.

**Comment by klokan** [comment]
You can use the `tileserver-gl-light` variant (without raster tiles generated on the server side).
The full `tileserver-gl` does not run natively on Windows right now, because the `mapbox-gl-native` component is not available for Windows yet.

Otherwise, install the Docker on your Windows computer. You don't need any license.
Get it at: https://www.docker.com/products/docker-toolbox

If you are newbie on docker - use the "Kitemetic" graphical user interface (in the package above) and drop the map tiles for area of your choice download at OSM2VectorTiles into the "data" folder.
