### ISSUE TITLE
Installation-documentation

### ISSUE THREAD

**Issue by gistack** [klokantech/tileserver-gl#77]
Hi

Can you write more details about the installation of tileserver with windows, Linux and Mac..??

Lots of errors in the installation with mapbox native!! and your team purposes dockers solution but your solution needs to work with  Mac, Windows and Linux!!!

Thank you

**Comment by klokan** [comment]
Feel free to contribute with the documentation. It would be great help to new users.

The `/docs` folder in the repo is directly built into http://tileserver.readthedocs.io/en/latest/. Improvements from a volunteer from the community are very welcome... 
Just create a pull request, please.

**Comment by twisig** [comment]
So how to resolve the mapboxgl native error with your npm installation??

Thanks

**Comment by klokan** [comment]
See: #79

**Comment by petrsloup** [comment]
@gistack We recently made some improvements to the installation documentation: http://tileserver.readthedocs.io/en/latest/installation.html.
If you still have some issues, please write a more specific description of your problem.
