### ISSUE TITLE
Points not visible in X-Ray view

### ISSUE THREAD

**Issue by muesliq** [klokantech/tileserver-gl#81]
The (hugely useful) X-Ray view doesn't seem to display poi content (yet it is there), not even with one pixel.

**Comment by muesliq** [comment]
Example (Location hash: #19.9/53.55149/9.99634)

Map: 

![screen shot 2016-11-25 at 11 39 19](https://cloud.githubusercontent.com/assets/1606618/20622597/eaa62190-b303-11e6-8e74-b527ef17933f.png)

X-Ray: 

![screen shot 2016-11-25 at 11 39 05](https://cloud.githubusercontent.com/assets/1606618/20622603/f20335f4-b303-11e6-9433-ce12c04e95fd.png)

**Comment by klokan** [comment]
There is a pull request waiting for merge, which will solve this:
https://github.com/klokantech/tileserver-gl/pull/73

@petrsloup

**Comment by muesliq** [comment]
Great!
