### ISSUE TITLE
[QUESTION] How to use custom styles from mapbox without token

### ISSUE THREAD

**Issue by BernhardBezdek** [klokantech/tileserver-gl#89]
I've downloaded a custom style created in mapbox studio (based on a `basic` style) and referenced the downloaded `.json` file in the config file.

Then after the server was started  the style was showed up in the overview and after I selected it I've got the errormessage: 
"MapBox Token required"

What do I have to do to get the custom style working as in the shown example where I don't need the mapbox token.

Thanks in advance.

**Comment by petrsloup** [comment]
@BernhardBezdek You also need to make sure that all the resources (`sources`, `glyphs` and `sprites`) referenced by the style `.json` file are  provided locally (not referencing any mapbox assets).

See http://tileserver.readthedocs.io/en/latest/config.html#referencing-local-mbtiles-from-style
