### ISSUE TITLE
Performance testing

### ISSUE THREAD

**Issue by petrsloup** [klokantech/tileserver-gl#9]
Performance testing of current tileserver-gl (rendering 960 various tiles):

Inside docker with mesa3d and xvfb:
```c
  data: 2.1724632369999988 // mbtiles accessing [s]
  render: 16.036997651000004 // tile rendering (uses OpenGL) [s]
  compress: 9.118905018 // png compression [s]
```

Native - OpenGL can access GPU (underclocked -- core 300 MHz, memory 300MHz):
```c
  data: 2.1002146649999998
  render: 13.908218127999989
  compress: 9.162028793000003
```

Native (GPU **severly** underclocked -- core 300 MHz, memory 150 MHz):
```c
  data: 2.155217818000001
  render: 15.640598796999985
  compress: 8.87022230800001
```

Native (GPU -- core 900MHz, memory 900MHz):
```c
  data: 2.0076603880000006
  render: 11.593615335
  compress: 8.727896114999984
```

---

Although the rendering process uses OpenGL and GPU, the performance seems to be okay even when running without HW acceleration.
Memory bandwidth is quite important since the rendered tiles need to be transferred from graphics memory to CPU RAM (and this operation is very cheap when using software rasterization).

**Conclusion:**
Running tileserver-gl on very low-end GPU probably wouldn't bring any (significant) performance gain over running inside docker container.

Code for performance testing is in `performance` branch.

**Comment by stirringhalo** [comment]
May I ask what GPU was used for the testing?

Would it be worth it to investigate Docker + 3D like: https://github.com/thewtex/docker-opengl-nvidia ?

**Comment by stirringhalo** [comment]
@klokan 

May I ask what GPU was used for the testing?

Would it be worth it to investigate Docker + 3D like: https://github.com/thewtex/docker-opengl-nvidia ?

**Comment by klokan** [comment]
I believe it was a standard desktop NVidia card. @petrsloup may give the `glxinfo`.

The `latest` docker image of this project must be portable and small - so people can easily try the project on any computer they want.

We should run the tests again on Amazon GPU instance (#30) - interested in doing this @stirringhalo?

With production deployment on a powerful GPU, the direct npm installation may be probably easier - but if you create a Dockerfile (esp. tested on Amazon NVidia GPU instance), we would be keen to have it under a separate tag in Docker Hub for people to use. Continue on #30
