### ISSUE TITLE
Data source via http

### ISSUE THREAD

**Issue by ArsenyN** [klokantech/tileserver-gl#91]
Hello, 
Can I use as source for rendering pbf files served via http?
How?

Thanks.

**Comment by klokan** [comment]
Yes. Of course you can.

Link the remote `source` from JSON style - it can be pre-generated tiles hosted on Amazon S3 or another cloud or folder with tiles - or vector .pbf tiles generated on demand from MapServer / GeoServer / Tegola or another dynamic server.

Good point - as it should be better documented.

**Comment by ArsenyN** [comment]
Thanks a lot for response.
I tried to add this code to style.json
```javascript
"sources": {
	"mapbox": {
		"url": "http://tile.mapzen.com/mapzen/vector/v1/all/{z}/{x}/{y}.mvt?api_key=mapzen-vF28k1C",
		"type": "vector"
	}
},
```
And after that I checked request function in renderer in serve_renderer.js.
This function did not replace placeholders inside url.

What I did wrong?
