### ISSUE TITLE
Serve multiple custom styles with different sprites

### ISSUE THREAD

**Issue by abenrob** [klokantech/tileserver-gl#92]
I'm having a hard time figuring our how to navigate the config file when I have multiple custom styles.
Each style has its own sprites (dark for dark theme, light for light, etc.) With the `{paths: {sprites: '...'}}` object, I am setting a shared root for all styles, and I con't see how to point the correct sprites to the style.
I would _like_ to be able to have a dir for each style, which contains that styles style file, glyphs and sprites, but I'm not getting it to work.
Is there an example of the 'out of the box' config for the server? i.e. when I fire up the server with no custom styles defined, it provides basic and bright styles -what does that config look like?
FWIW I'm trying to use osm-liberty, and two variants I created as the 3 styles I serve.
Thanks for the help!

**Comment by abenrob** [comment]
Hey guys - this project is great. The issue here becomes moot when using openmaptiles. CLosing, and thanks!

**Comment by klokan** [comment]
BTW the out of the box config.json is printed out if you run the server with `--verbose`.

See the manual: http://tileserver.readthedocs.io/en/latest/search.html?q=verbose&check_keywords=yes&area=default

**Comment by abenrob** [comment]
Yes! I saw that, and it really helped me get it dialed in.
