### ISSUE TITLE
Tileserver interprets wrong zoom levels for fonts 

### ISSUE THREAD

**Issue by muesliq** [klokantech/tileserver-gl#94]
In the raster output Tileserver (v1.1.1) seems to render the wrong fonts. See _Aarrau_, _Zug_ or _Winterthur_ in this example (ZL 9, raster):

![screen shot 2016-12-19 at 12 01 48](https://cloud.githubusercontent.com/assets/1606618/21310638/9b9b82c8-c5e3-11e6-9905-c6aceccee8ff.png)

It should be rendered as Mapbox GL JS does (ZL 8, vector):
![screen shot 2016-12-19 at 12 01 33](https://cloud.githubusercontent.com/assets/1606618/21310712/dccbf94e-c5e3-11e6-873d-951c2ef8bb04.png)

This is the styling of _Aarau_ for example:

```
        "text-font": {
          "base": 1,
          "stops": [
            [7, ["LeFont Std Regular"]],
            [11, ["LeFont Std Bold"]]
          ]
        },
```

It looks like Tileserver is interpreting the zoom levels wrong. When I zoom out in the raster version to ZL 8. Note that while _Lucerne_ is still formatted wrongly, _Aarau_ is now right:

![screen shot 2016-12-19 at 12 13 27](https://cloud.githubusercontent.com/assets/1606618/21311036/75d5d17c-c5e5-11e6-8c42-69e3a217e90b.png)

Let's look at _Aarau_ zoom level treatment in detail:

|  | When Bold starts to get used  |
| ------------- | ------------- | 
| Stylesheet  |  ZL 11  |
| Mapbox GL JS | ZL 11  |
| Tileserver GL Raster  | **ZL 9**  |
| Raster how it should be  | ZL 12  |

It seems like the ZL conversion is being done two ZL back instead of one ZL forward.

**Comment by klokan** [comment]
Thanks for the report.

Unfortunately, we do not have any client who would directly cover working hours related to investigation and fix of this issue now. If you do, please provide a pull request with the fix - or purchase a support from us via info@klokantech.com - so we can dedicate required time to this task.

It may be possible that upgrade to the latest Mapbox GL Native brings improvement in this regards.

**Comment by muesliq** [comment]
Fair enough. Can you give us some pointers as to where in the code to look at, to fix this?

**Comment by muesliq** [comment]
Problem seems to have been fixed meanwhile.
