### ISSUE TITLE
Lost the ability to get rendered tiles ...

### ISSUE THREAD

**Issue by Tom-Cuthill** [klokantech/tileserver-gl#97]
Hi,

I built a tileserver based on tileserver-gl in docker-compose using an image that is now about a month or two old.  Yesterday I rebuilt the entire service, based on the current tileserver-gl image.

It appears that I've lost the ability to serve rendered tiles.  Previously I was able to get the tiles from here: /styles/bright-v9/rendered/{z}/{x}/{y}.png  (for example, in my configuration: http://ge-gis-dev1:8080/styles/bright-v9/rendered/10/841/607.png rendered a tile in Western Australia). 

I investigated further and see that the new tileserver-gl image no longer has the bright-v9 style.  I tried instead to use the osm-bright style.  So my URL became http://ge-gis-dev1:8080/styles/osm-bright/rendered/10/841/607.png.  The server reports a 404.  It also appears that I can't get to any of the styling information associated with osm-bright.  If I try http://ge-gis-dev1:8080/styles/osm-bright/sprite.json, I again get a 404.  Note that apart from that, the server is continuing to be able to serve up vector tiles.

I assume this has something to do with the config file?  I have no idea where it is or what it is called.
Can you give me any insights into what I am doing wrong?  I was hoping to demo a project using the tileserver in mid-January!!

Thanks for any help you can provide,
Tom Cuthill

**Comment by mkjaer** [comment]
The styles seem to disappear when you mount something into /data using version 1.3.0 (which apparently is beta even though it has both a beta and non-beta tag on dockerhub).
v1.2.0 works for me.

**Comment by klokan** [comment]
This was related OSM2VectorTiles -> OpenMapTiles migration.

Please upgrade to latest version of TileServerGL and download new MBTiles from https://openmaptiles.org/.

The OSM2VectorTiles project has been closed down on request from Mapbox Inc. See: https://github.com/osm2vectortiles/osm2vectortiles/issues/387
