### ISSUE TITLE
Problems behind Proxy

### ISSUE THREAD

**Issue by dondrake** [klokantech/tileserver-gl#99]
I'm attempting to use your Docker image to try out tileserver-gl.  The problem is that I'm behind a corporate firewall with MITM SSL sessions.

I was able to tweak your docker command-line to add `-e http_proxy -e https_proxy` so the proxy configuration will go inside the Docker.  

Now, when it starts, I'm getting the following error:
```
Starting tileserver-gl v1.3.0-beta.1
Downloading sample data (zurich_switzerland.mbtiles) from https://github.com/klokantech/tileserver-gl/releases/download/v1.3.0/zurich_switzerland.mbtiles
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: self signed certificate in certificate chain
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1039:38)
    at emitNone (events.js:67:13)
    at TLSSocket.emit (events.js:166:7)
    at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:603:8)
    at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:445:38)
```

I read that you can disable the SSL checks in npm with `npm config set ca="" ` (https://github.com/npm/npm/issues/7519).  I'm not sure how I can tweak that while using your docker image.

Any suggestions?

**Comment by revenger73** [comment]
Download mbtile yourself, image will not try to download sample data

**Comment by dondrake** [comment]
Sorry, @revenger73, I'm not following your recommendation. I don't need the zurich mbtiles, I have my own, but whenever I start this docker image, it attempts to download them.

**Comment by revenger73** [comment]
Ok, strange. We're using older version which does not seem to have that issue in an environment without internet connection.

**Comment by klokan** [comment]
Have you started the docker image while mapping the volume `/data/` into a directory where you have your already downloaded openmaptiles .mbtiles (or posibly config.json?). I guess not - which triggers the download of the sample map.

**Comment by dondrake** [comment]
I was able to manually download the zurich .mbtiles, place it in the data/ directory and then everything started working when I attempted to start the docker image.

**Comment by klokan** [comment]
Cool, so it seems this ticket can be closed?

**Comment by dondrake** [comment]
Yes, thanks.
